### ISSUE TITLE
Better handling of  escapes dealing with HTML special characters

### ISSUE THREAD

**Issue by rwols** [facelessuser/pymdown-extensions#1019]
The backslash escapes from CommonMark are:

```
!"#$%&'()*+,-./:;<=>?@[\]^_`{¦}~0123456789
```

The backslash escapes from Daring Fireball are:
```
\`*_{}[]()#+-.!
```

The set difference is
```
^9&2%;~=@"':8><?/¦4$360751,
```

It would be nice to have an extension that processes these potential escapes.

See: https://github.com/sublimelsp/LSP-css/pull/16
See: https://spec.commonmark.org/0.15/#backslash-escapes
See: https://daringfireball.net/projects/markdown/syntax#backslash

**Comment by facelessuser** [comment]
Escapeall does this, I think what is explicitly missing from this issue is that it needs to handle HTML special characters...special.

**Comment by rwols** [comment]
Looking at https://github.com/facelessuser/pymdown-extensions/blob/e2d5f6ec7790477c9411aa9eecca2acb3cf17b1d/pymdownx/escapeall.py#L54 perhaps we can indeed add something like

```python
elif char == '<':
    escape = md_util.AMP_SUBSTITUTE + 'lt;'
elif char == '>':
    escape = md_util.AMP_SUBSTITUTE + 'gt;'
```

**Comment by facelessuser** [comment]
Pull #1020 should fix escapeall.

Title of issue changed as I want to make clear, while we weren't handling escaped HTML characters like we should, we aren't claiming to be Commonmark compatible, but this case should be handled appropriately now.

@gir-bot remove S: triage
@gir-bot add T: bug, C: escapeall

**Comment by rwols** [comment]
Sounds good to me.
