### ISSUE TITLE
remove "language" from css class

### ISSUE THREAD

**Issue by erez-o** [facelessuser/pymdown-extensions#1030]
Hi, 

Question relating to 'pymdownx.highlight':

Is there a way to remove the prefix string "language" in "language-mylanguage"?

I can set `css_class:''`, but I see no option to set the prefix instead of `prefix:'language-'` to `prefix:''`

Highlight.js does support class='mylanguage', without the need to specify class='language-mylanguage'

Thanks

**Comment by facelessuser** [comment]
This is from Highlight.js usage documentation:

> Classes may also be prefixed with either `language-` or `lang-`.
>
> ```html
> <pre><code class="language-html">...</code></pre>
> ```


https://highlightjs.org/usage/

With that said, prefix is not currently controllable. I can potentially consider it, but that should not be your problem as this format is specified in the HTML5 spec, and most highlighters support this format.

**Comment by erez-o** [comment]
Thanks, 

Prefix `language-` is semantically better.

The reason for this feature request has more with redundancy and optimization of shorter class names in the created html, for example, if there are 20+ code tags on the same page.

I assume that's why different js highlighters allow for various shorter options.

For example, Highlight.js allows excluding `language-` and prism.js allows the language to be inherited from an ancestor:

> To make things easier however, Prism assumes that this language definition is inherited. Therefore, if multiple `<code>` elements have the same language, you can add the language-xxxx class on one of their common ancestors. This way, you can also define a document-wide default language, by adding a language-xxxx class on the `<body>` or `<html>` element.

**Comment by facelessuser** [comment]
I'll consider it.

@gir-bot remove S: triage
@gir-bot add T: feature, P: maybe, C: highlight

**Comment by erez-o** [comment]
Thanks for the speedy update :)

**Comment by facelessuser** [comment]
np, it's not out the door yet, but I imagine I should have a release within a week or two 🤞.
