### ISSUE TITLE
Fenced code inside lists

### ISSUE THREAD

**Issue by erez-o** [facelessuser/pymdown-extensions#1031]
Hi, 

Regarding, `SuperFences`, can you please add support for fenced code inside lists?

Unless I'm using it wrong, fenced code inside list items are ending the list with a `</ul><pre>...</pre>` instead of rendered as `<pre>...</pre>` inside the `<li>`.

I created an example in https://github.com/erez-o/fenced-code-md/blob/master/README.md/. The way github renders it is the way I expect.

Looking at babel, I think it's relatively common for fenced code to be supported inside lists.

[babel](https://babelmark.github.io/?text=%23%23+Type+info%0A%0AParagraph%3A%0A%0A*+First+element+in+list%3A%0A++%0A++%60%60%60cpp%0A++auto+id+%3D+5%3B%0A++%60%60%60%0A++%0A++Some+paragraph%0A++%0A*+Second+element%0A++%0A++%60%60%60cpp%0A++auto+name+%3D+type_info%3Cmy_type%3E%3A%3Aname()%3B%0A++%60%60%60%0A++%0A++Another+par%3A%0A++%0A++%60%60%60cpp%0A++struct+my_type+%7B+%2F*+...+*%2F+%7D%3B%0A++%60%60%60%0A%0ANew+paragraph%0A)

If it helps to reproduce, I activated with `extensions = ['pymdownx.highlight', 'pymdownx.extra']`.

Thanks

**Comment by facelessuser** [comment]
I'm going to leave this here:

- https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#overview
- https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#nested-fence-format

In short, we support them in lists, just check out the docs.

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add T: support

**Comment by erez-o** [comment]
Thanks, 

I didn't notice the requirement for 4 spaces preceding the fenced code. My example had only 2 spaces.
