### ISSUE TITLE
Loading "pymdownx.superfences" alongside "markdown.extensions.fenced_code"

### ISSUE THREAD

**Issue by itopaloglu83** [facelessuser/pymdown-extensions#1056]
I don't know if this causes any problems but [usage notes](https://facelessuser.github.io/pymdown-extensions/usage_notes/) states that `pymdownx.superfences` replaces `markdown.extensions.fenced_code`. But when I check the build logs for the MkDocs, it says that both of them are loaded at the same time. Does this cause any issues anywhere?

> (.env) user@computer project.github.io % mkdocs build -v
> ...
> DEBUG   -  Config value: 'markdown_extensions' = ['toc', 'tables', 'fenced_code', 'footnotes', 'attr_list', 'def_list', 'pymdownx.tilde', 'pymdownx.tasklist', 'admonition', 'pymdownx.details', 'pymdownx.highlight', 'pymdownx.magiclink', 'pymdownx.superfences', 'pymdownx.tabbed', 'plantuml_markdown']
> ...
> (.env) user@computer project.github.io %

**Comment by facelessuser** [comment]
It "replaces" in the sense that you should use them as opposed to their counterpart. I also cleary state:

> but if you choose to use one of the packages below, you should use it instead of the Python Markdown one; they cannot be loaded at the same time.

So don't use them both 🙂.

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add T: support

**Comment by itopaloglu83** [comment]
So, as long as I only use `pymdownx.superfences` and not `markdown.extensions.fenced_code` everything should be fine. I don't know which one [Material for MkDocs](https://github.com/squidfunk/mkdocs-material) uses after loading. I'll check in their code. 

Thank you!

**Comment by facelessuser** [comment]
They use SuperFences because it is the only one that does nesting in lists and other constructs. I actually worked pretty close with the developer to deliver some features per his request.
