### ISSUE TITLE
Tabbed: Allow title content to be parsed for Markdown syntax

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/pymdown-extensions#1063]
Tabbed uses a syntax very similar to Details and Admonitions. The title is within quotes, but the difference is that while this quoted content is parsed as Markdown for Details and Admonitions, it isn't for Tabbed. We should probably have Tabbed work the same way. While I wouldn't normally advise inserting anything there, there are some useful things, like emojis or something to make tabs a little more expressive.

**Comment by Vasperous** [comment]
Would this change allow the use of [attr_list](https://github.com/Python-Markdown/markdown/blob/master/docs/extensions/attr_list.md) to assign a tab a specific class/id?

**Comment by facelessuser** [comment]
> Would this change allow the use of attr_list to assign a tab a specific class/id?

To what? to the entire tab? It'd work for things withing the tab title. Not sure if it'd work for the tab without special handling, but maybe, I'd have to test. If we really wanted, we could add it. We almost added custom classes in the same way admonitions defined them, but I can't imagine a scenario where a specific class is useful to be assigned to a specific tab, but maybe that is due to a lack of imagination on my part 🤷 .

**Comment by Vasperous** [comment]
Basically a unique (or common) class across a set of different tabs.  I am trying to implement #1089 and the best way I could think of (btw I am far from an expert) was to detect the change/click using JS and update the page + relevant tab sets.  I couldn't find a way to associate a tab type with another across several pages etc.  so when I saw this I was hopeful it would help solve that problem.  As you can guess, I already tried using attr_list and all different combinations but with no luck.

Thank you!!!

**Comment by Vasperous** [comment]
@facelessuser  thank you I think that might do it.  Like the picture in #1089 I have some tabs that have the same name across my documentation.  When a user selects that tab I ideally would like that tab label/id etc. to be selected by default on the rest of the page and on other pages (until the user changes it again).  My initial though was to use attr_list to get the ID and have it be the same across my documentation which as noted wasn't working with tabs.  Based on your thorough description I believe I can achieve this so thank you!

**Comment by facelessuser** [comment]
I didn't see this until now. Yeah, all of this is possible, and I've done something similar in a work project for some internal display of metrics. You have to use local data storage on your site. You can read that data in, and after page load, initialize all the tabs.

I know all of this is possible as I've done very similar things at work. I don't really have this info in front of me, and it would have to be adapted for Material docs etc.

I don't really have time right now to adapt my solution from work over to this, but maybe when I get some time I can at least share how I attach an event.

**Comment by Vasperous** [comment]
@facelessuser thank you for the help and ideas, I think I figured it out. I am sure someone can write it much more elegantly than I (google is my friend 💯  ).
``` js
var elements = document.getElementsByClassName('tabbed-set');

const PROCESSORS = [
    'Test1',
    'Test2',
    'Test3'
];

const LS_PROCESSOR = 'selectedProcessorTab';

var InputTest2 = [];
var InputTest3 = [];
var InputTest1 = [];


var tabClicked = function() {
    var tabText = this.textContent;
    if (PROCESSORS.indexOf(tabText) >= 0 && tabText !== getLocalStorageProcessor()) {
        setLocalStorageProcessor(tabText);
        selectTabs();
    }
};

function setLocalStorageProcessor(processor) {
    localStorage.setItem(LS_PROCESSOR, processor);
}

function getLocalStorageProcessor() {
    return localStorage.getItem(LS_PROCESSOR);
}

function selectTabs() {
    var lsTab = getLocalStorageProcessor();
    var tabsToSelect = [];
    switch(lsTab) {
        case 'Test2': {
            tabsToSelect = InputTest2.slice(0);
        }   break;
        case 'Test3': {
            tabsToSelect = InputTest3.slice(0);
        }   break;
        case 'Test1': {
            tabsToSelect = InputTest1.slice(0);
        }   break;
    }

    for (var z = tabsToSelect.length - 1; z >= 0; z--) {
        tabsToSelect[z].checked = true;
    }
}

function initialProcessTabs() {
    console.log('Processing initial tabs...');
    // Loop through each 'tabbed-set'
    for (var i = 0; i < elements.length; i++) {
        var elInput = elements[i].getElementsByTagName('input');
        
        for (var y = elInput.length - 1; y >= 0; y--) {
            var selector = 'label[for=' + elInput[y].id + ']';
            var label = document.querySelector(selector);

            switch(label.innerHTML) {
                case 'Test2': {
                    InputTest2.push(elInput[y]);
                    label.addEventListener('click', tabClicked, false);
                }   break;
                case 'Test3': {
                    InputTest3.push(elInput[y]);
                    label.addEventListener('click', tabClicked, false);
                }   break;
                case 'Test1': {
                    InputTest1.push(elInput[y]);
                    label.addEventListener('click', tabClicked, false);
                }   break;
            }
        }
    }

    selectTabs();
}

initialProcessTabs();
```

**Comment by facelessuser** [comment]
Glad you figured it out! Maybe this will be useful for people who stumble on it in the future.

You can maybe target these events (the second is relevant to instant loading):

```js
    document.addEventListener("DOMContentLoaded", fn)
    document.addEventListener("DOMContentSwitch", fn)
```

Sorry that I can't provide JavaScript for all of this, it's just out of scope for the plugin itself, even if it is related. There will always be a new custom solution or variant that someone is looking to solve, and I have to draw a line so I'm not doing full-time custom code development for people 😄 .

**Comment by Vasperous** [comment]
@facelessuser that was it! 🥇  Thank you!

**Comment by facelessuser** [comment]
While I'd like to rework the logic here to be a little more sane, I've decided to just relax the logic to allow the content to be parsed as Markdown for now. I'd like to have more sane logic of allowing escaped quotes within the quoted titles etc., but currently, Admonitions and Details do not have this logic either, so really, I'm just making Tabbed behave like those currently do now. In the future, I'd like to make the logic better, but as people are already desiring to put emoji and such in tabbed titles, I'll go ahead and relax the constraint.
