### ISSUE TITLE
Problem with installing on makrdown 3.2

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [facelessuser/pymdown-extensions#1068]
Hi, im trying to install it and i get this error:
```
# pip install pymdown-extensions
Collecting pymdown-extensions
  Using cached https://files.pythonhosted.org/packages/d3/1f/e1ed33f5784d80c75db685fcc6e51de8011c7588752e184fba443590eb2a/pymdown_extensions-8.0-py2.py3-none-any.whl
Collecting Markdown>=3.2 (from pymdown-extensions)
  Could not find a version that satisfies the requirement Markdown>=3.2 (from pymdown-extensions) (from versions: 1.7, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.3, 2.3.1, 2.4, 2.4.1, 2.5, 2.5.1, 2.5.2, 2.6, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.6.7, 2.6.8, 2.6.9, 2.6.10, 2.6.11, 3.0, 3.0.1, 3.1, 3.1.1)
No matching distribution found for Markdown>=3.2 (from pymdown-extensions)
```
Isn't it compatible with 3.2? I cant get anywhere info about that

**Comment by facelessuser** [comment]
What version of Python are you on?

**Comment by Kryniowesegryderiusz** [comment]
2.7.17

**Comment by facelessuser** [comment]
Latest version of pymdown-extensions only runs on Python 3.5+: https://github.com/facelessuser/pymdown-extensions/blob/master/setup.py#L53

Latest version of Markdown requires python 3.5+: https://github.com/Python-Markdown/markdown/blob/master/setup.py#L77

It's probably an issue with it not finding the right requirement on Python 2.7. We don't really support 2.7 anymore.

**Comment by Kryniowesegryderiusz** [comment]
What is the last version that supported 2.7?

**Comment by facelessuser** [comment]
Maybe try 6.2.0? If that doesn't work, you may have to go earlier.

**Comment by facelessuser** [comment]
In many projects I mark when I drop an older Python, unfortunately, I did not document well when we dropped it here. I may even have been accidentally releasing Py2 releases even though they depended on Python Markdown versions that no longer supported Python 2.

I'll make a better effort moving forward to document when a Python version is dropped to make it clear.

**Comment by facelessuser** [comment]
Closing as the question has been answered.
