### ISSUE TITLE
Details without Title don't render

### ISSUE THREAD

**Issue by squidfunk** [facelessuser/pymdown-extensions#107]
I don't know if I'm getting something wrong, but if I omit the title for a details block, the whole block is not rendered. As this is possible with Admonition, I would expect it to be handled the same way.

**Actual behavior:**

![bildschirmfoto 2017-08-29 um 18 32 09](https://user-images.githubusercontent.com/932156/29818963-bc4784fa-8ce8-11e7-8481-5a6e01691f0f.png)

**Expected behavior:**

I would expect the following configurations to be valid:

*  `??? "Title"`: render without optional class, but with "Title" as text
* `??? note`: render with class `note` and "Note" as text
* `??? note "Title": render with class `note` and "Title" as text

**Comment by facelessuser** [comment]
I'll look into this. I personally never use admonitions without a title, so I never bothered to support that with details. I'll take a look to better understand what admonitions does and see if I can mimic that.

**Comment by facelessuser** [comment]
I'm marking this as an enhancement as details was consciously designed to be this way.  But I can see how this may be desired as something intuitive due to familiarity with admonitions.  I personally don't like "magic" titles, but this is fine for consistency.

I will not allow no class **and** no title though.  I know that isn't suggested here, but just figured I'd formally state it...cause details with no titles would just be weird 😮 .

**Comment by squidfunk** [comment]
> I'm marking this as an enhancement as details was consciously designed to be this way. But I can see how this may be desired as something intuitive due to familiarity with admonitions. I personally don't like "magic" titles, but this is fine for consistency.

Yes, it's not a big deal, really, I only mentioned it for reasons of consistency. Maybe I'm biased because I just implemented details as an extension of admonitions, so it may be no good example.

> I will not allow no class and no title though. I know that isn't suggested here, but just figured I'd formally state it...cause details with no titles would just be weird 😮 .

Agree, that makes no sense.

**Comment by facelessuser** [comment]
It should be pretty easy to throw together.  I may have some time in the next couple of days to get to this.

**Comment by facelessuser** [comment]
This will be available in the next release.

**Comment by squidfunk** [comment]
Awesome!
