### ISSUE TITLE
mkdocs-material example

### ISSUE THREAD

**Issue by ptcane** [facelessuser/pymdown-extensions#1073]
hi, would you be able to provide a simple example for including a HTML file in /docs in another .md file in /docs when using mkdocs-material?

I have the check-paths option enabled so I can see all the combinations i can think of are failing due to file not being found (rather than some other issue).

many thanks

**Comment by facelessuser** [comment]
1. This sounds like a Material question, or maybe even a MkDocs question, not a pymdown-extensions question. This would be more appropriate to maybe ask over in the discord channel, but even better if asked in the appropriate repository issue tracker.

2. I'm not even exactly sure what the question is asking. When posing this question, maybe an example would help clarify.

@gir-bot remove S: triage
@gir-bot add S: invalid

**Comment by facelessuser** [comment]
Hmm, maybe even posing this on StackOverflow would make more sense.

**Comment by ptcane** [comment]
ok, thanks.
