### ISSUE TITLE
Tabbed: Preserve user selection

### ISSUE THREAD

**Issue by Vasperous** [facelessuser/pymdown-extensions#1089]
Great project and really appreciate solution!

One item that I have seen in some custom solutions that I thought would be great to have is the ability to preserve the users selected tab.  The reason for the request is in situations where you may have various sets of sample code in different languages.  In those cases you want to select a tab and have the rest of the documentation load with that tab selected.

As an example, you can go to the Android documentation for the [Bluetooth API](https://developer.android.com/guide/topics/connectivity/bluetooth?hl=en#SettingUp) and click between Kotlin and Java.  You will notice that the preference for one over the other will remain regardless of the page your navigate to.

![image](https://user-images.githubusercontent.com/8703632/92520627-e4694680-f1e9-11ea-8b14-dc202596dce0.png)

Thank you!

**Comment by facelessuser** [comment]
They are using local storage to do so. You can do this with some JavaScript if you'd like, but not really something I can back in. You'd add some event listeners to the elements, and when changed, change the rest on the page and store the preference in local storage. When loading a new page, you'd read that preference from local storage, and set all the tabs accordingly.

**Comment by facelessuser** [comment]
As the question has been answered, and the solution *should* be implemented with JavaScript, not directly through Tabbed, I will consider this issue answered/closed.

@gir-bot remove S: triage
@gir-bot add S: wontfix
