### ISSUE TITLE
[Question] Embed whole code\part of it from a github repo

### ISSUE THREAD

**Issue by Maxiride** [facelessuser/pymdown-extensions#111]
This is not an issue, but a question since your extensions do a lot of things.

I'm googling around, without success so far, to find an easy way with mkdocs and its plugins to embed code froma github repo.
Most likely like the SuperFence where one can also specify the line numbering and from where to start to count, but picking the lines of code from a specified file from a repo.

So that one could hypothetically "quote" code or part of it. Is there anything like that around? 

I know that is already possibile with gists, but I am talking about actual repository files.

**Comment by facelessuser** [comment]
You'd have to probably write your own Python Markdown extension.  I'd check out their documentation and check extension examples. You could possibly create a custom language like SuperFences does with UML, but you would have to write the code to pull code from a repository and format it etc.  See SuperFences documentation for info.

Unfortunately, I don't know of an extension of the top of my head that does this, but it should be possible, but you'd have to put in the work to accomplish it.

All I can generally say is that what you want is most likely possible, but I really just don't have the time to look into the logistics of it.

**Comment by Maxiride** [comment]
So, with a friend we managed to write a python script that get a file from a repo and then outputs the interested lines.

The challanging part is to make it a python markdown extensions D:

**Comment by facelessuser** [comment]
If you have specific questions, I'll be happy to answer them.  I'd read Python Markdown's documentation on writing your own extension, and look at some simple examples (complex examples can be tricky).  In your case, I imagine you'd just use some kind of special URL that would be identified and then it would pull the code in question and create correct HTML. But I'm not exactly sure how you plan on using it, so the actually end code could be quite different. I imagine if you are pulling code from GitHub, there is probably an API to get all of that and special CSS to render it, but I don't know.

**Comment by Maxiride** [comment]
I'm starting to think that it might just be an overkill solution to embed code from a repo and that a simple copy paste would suffice everytime.. :thinking:

**Comment by facelessuser** [comment]
That's my opinion, but that may just be me. I'll go ahead and close this as there is no actionable item for me.
