### ISSUE TITLE
[Feature Request] Link Tabbed Across Sets

### ISSUE THREAD

**Issue by ms-lolo** [facelessuser/pymdown-extensions#1124]
I'm not sure if this is already possible but I was having trouble figuring out what to search for. I would love the ability to have multiple tab sets be linked together so that the tabs on the entire page toggle together. For example, if I'm writing a doc about how to install some tooling and the steps differ slightly between OSX and Linux, I might have a few tabbed pieces of content across the page containing the commands needing to be run at the various stages of the process. It would be nice to toggle all the "OSX" tabs if the user selected to see the commands needing to be run on OSX for the first portion of commands.

You can see an example of this on the spark examples docs where you can choose the programming language you want to see samples for: https://spark.apache.org/examples.html

**Comment by facelessuser** [comment]
Any sites where you see this kind of behavior, you can be pretty certain it is done with JavaScript. As this extension simply generates HTML, you would have to provide your own JavaScript to do so.

So, yes it is possible, but you will have to develop the JavaScript and include it in your final HTML after Markdown generation.

**Comment by ms-lolo** [comment]
ah I see and we're just using radio boxes here. is there maybe some additional metadata we could add to the elements in order to make the javascript easy to generalize? or would you suggest we use `attr_list` extension to add the needed information?

**Comment by facelessuser** [comment]
Easy is relative, but there should be enough info already. Each input already has ids. I'd just look at the tabsets and gather the ids for the tabs, creating a mapping of ids to specific matching labels. Maybe attach an event to the inputs when someone changes one, then you just reference all the ids whose associated label matches the one that got selected. That's the short of it. You may have to add a little logic to prevent running the events again when you are selecting the other tabs while processing the event for a tab getting selected.

Anyways, it is something that you'd have to do maybe a little research on, but this is completely doable. Unfortunately, I don't have time to help code up custom solutions for people.

**Comment by ms-lolo** [comment]
No problem, thanks for the guidance. I'll go ahead and close since it's something that would live on our side!
