### ISSUE TITLE
There is a white line in Block math

### ISSUE THREAD

**Issue by izlyforever** [facelessuser/pymdown-extensions#1131]
I config Mathjax followed your [official doc](https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/) , but there is a white line in my Block math as follow:

![white line](https://i.loli.net/2020/10/21/HMrpvt81bgT3h9k.png)

I config the same where Arithmatex appear: [my blog](https://izlyforever.com/mathjaxTest/) and [my mkdocs.yml](https://github.com/izlyforever/izlyforever.github.io/blob/master/mkdocs.yml)

> I also see there is the same issue in [MKDocs-matrial official site](https://squidfunk.github.io/mkdocs-material-insiders/reference/mathjax/)

**Comment by facelessuser** [comment]
Unfortunately with the info you've provided, I cannot debug this:

1. I don't know what browser you are using.
2. I don't know what OS this is occurring on.
3. I don't know what version of anything you are using.
4. While you are stating you followed my instruction in the docs, I do not see any config posted here, so I cannot confirm if there were typos.

Doing some quick testing:

1. I do not see this issue on the official MkDocs-Material site.
2. I do not see this issue on my own site as either.
3. I cannot reproduce this issue when I use the latest versions.
4. I do not see this issue on Chrome, Firefox, or Safari.

Assuming I could reproduce, this would also be a theming issue that should most likely be reported to mkdocs-material not here.

@gir-bot remove S: triage
@gir-bot add S: support

**Comment by izlyforever** [comment]
I use mathjax2 instead, anyway, thanks for your reply~

> See [end of this Material page](https://squidfunk.github.io/mkdocs-material-insiders/reference/mathjax/) and **choose dark theme in order to see the white line.**

**Comment by facelessuser** [comment]
> See end of this Material page and choose dark theme in order to see the white line.

Yeah, I could not get it to show as you did, even with dark mode. It seems very specific to your local environment.

Regardless, this would most likely be a styling issue with Material if it isn't related to something local.
