### ISSUE TITLE
Don't swallow exceptions in custom SuperFence source formatter

### ISSUE THREAD

**Issue by mschwerhoff** [facelessuser/pymdown-extensions#1136]
When using the SuperFences extension in one of my projects, I noticed that exceptions raised inside a custom formatter are apparently caught — at least they never seem to reach stdout/stderr. Consider e.g. the following trivial source formatter:

```py
def source_formatter(source, language, css_class, options, md, **kwargs):
  print('[START]')  
  raise Exception('Boom!') ######## Raised but swallowed
  print('[END]')
  return f'<code>todo</code>'
```

Raising the exception appears to terminate `source_formatter` (`[END]` is never printed), but not the overall Markdown processing, which makes me suspect that the exception is either caught by SuperFences or by Python-Markdown itself.

**Question:** How can I prevent SuperFences (or Python-Markdown) from catching exceptions?

-------

Here is the minimal working example:

    import markdown
    import pymdownx.superfences

    def source_validator(language, inputs, options, attrs, md):
      return True

    def source_formatter(source, language, css_class, options, md, **kwargs):
      print('[START]')  
      raise Exception('Boom!') ######## Raised but swallowed
      print('[END]')
      return f'<code>todo</code>'

    superfences_config = {
      'custom_fences': [
        {
          'name': 'foo',
          'class': 'highlight',
          'format': source_formatter,
          'validator': source_validator
        }
      ]
    }

    source = '''
      ```foo
      x := y
      ```
    '''

    html = markdown.markdown(
      source, 
      extensions=['pymdownx.superfences'], 
      extension_configs={'pymdownx.superfences': superfences_config})

    print(html)

**Comment by facelessuser** [comment]
I would suggest maybe exception handling should be added to your custom formatter. SuperFences usually attempts to handle these situations gracefully. This was something that wasn't something that was missed but chosen.

You could easily just do something like this:

```py
def source_formatter(source, language, css_class, options, md, **kwargs):
  try:
	  print('[START]')  
	  raise Exception('Boom!') ######## Raised but swallowed
	  print('[END]')
	  return f'<code>todo</code>'
  except Exception:
      # Print and reraise
      import traceback
      print(traceback.format_exc())
	  raise
```

**Comment by mschwerhoff** [comment]
Thank you for the quick reply and the concrete suggestion! I'll go with that.

Two suggestions, though: It would be helpful to have this documented in the docs; linking to this issue would probably already suffice. Additionally, SuperFences could log exceptions, using Python-Markdown's logging infrastructure, so that users can see them in e.g. debug mode.

**Comment by facelessuser** [comment]
We can maybe mention that custom fences will swallow exceptions. Logging is a possibility, but users can also add their own logging if they desire.

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add T: maintenance, C: docs
