### ISSUE TITLE
Magiclinks and issue tags need sane headers

### ISSUE THREAD

**Issue by nonstdout** [facelessuser/pymdown-extensions#1164]
Just a quick FYI, might be worth a document update to say you need to include sane headers when using the magiclinks plugin with `#` issues.  Without it the pull requests (using `!1`), work but `#1` gets picked up as an `<h1>`.  

I know this is pretty obvious but it took me a while to figure out which extension was causing the issue, so I think a quick note might help here.

Cheers for the extensions, they are awesome!

**Comment by facelessuser** [comment]
Yeah, that was one of the motivating factors when creating SaneHeaders. While the documentation already mentions this behavior when referencing the SaneHeaders extension, I don't think we mention anything about SaneHeaders when referencing MagicLinks. We can add a note there as well.
