### ISSUE TITLE
snippets not loading

### ISSUE THREAD

**Issue by mbdraks** [facelessuser/pymdown-extensions#1184]
Hi,

First thanks for the extensions, they're great!

I'm having an issue trying to use the snippets extension. It simply does not load the file, I'm sure it may be something obvious but after troubleshooting (testing locally, docker image, github pages) I was not able to solve it.

If someone can take a quick look I would appreciate the help.

repo: https://github.com/mbdraks/test-mkd

extension config:
https://raw.githubusercontent.com/mbdraks/test-mkd/main/mkdocs.yml
```
markdown_extensions:
  - admonition
  - pymdownx.snippets
  # Content Tabs
  - pymdownx.tabbed
  - pymdownx.superfences
  # collapsible Admonitions
  - pymdownx.details
```

md:
https://raw.githubusercontent.com/mbdraks/test-mkd/main/docs/snippet_test.md
```
# snippets

--8<--
filename.md
filename.log
--8<--


--8<-- "filename.md"
```

and the result (a blank page, just the title): https://mbdraks.github.io/test-mkd/snippet_test/

**Comment by facelessuser** [comment]
Doesn't seem like you configured your base folder. Files should be relations to your configured base.

**Comment by mbdraks** [comment]
I see, after reviewing this doc https://facelessuser.github.io/pymdown-extensions/extensions/snippets/ I was under the impression that the default value of '.' (docs dir because I'm using the default value) would suffice and no additional config would be required.

Your suggestion is to declare the docs_dir value even if I'm using the default or I misunderstood the tip?

**Comment by facelessuser** [comment]
It is `.` from the current working directory (CWD). You are assuming the CWD is changed to your docs directory, but I don't think mkdocs does that. It looks in the docs directory, but the CWD is still in your project root.

**Comment by mbdraks** [comment]
Absolutely right, after changing the reference to `--8<-- "docs/filename.md"` instead of simply `--8<-- "filename.md"` it worked.

Thanks again for the help!
