### ISSUE TITLE
Handle GitHub Discussions in Magiclink

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/pymdown-extensions#1187]
Discussions, like issues and bugs all can be references in GitHub with `#<number>`. We handle bugs and issues like GitLab and use `!<number>` for pulls` and `#<number>` for issues. And we can deduce from bug links and pull requests links which way they should be rendered.

Discussions are a new kind of issue and we should probably shorten them to `#<number>` like you can for bugs or pulls. But maybe give a shorthand for them as well, maybe `?<number>`?

**Comment by cainmagi** [comment]
Have you considered making magiclink supporting a link from Github gist? I think it would be helpful in some cases.

**Comment by facelessuser** [comment]
At most, we'd probably just shrink the links. I'm not sure we'd bother with a special syntax for them.

**Comment by facelessuser** [comment]
I have not planned anything for gist links though, and I'm not sure if I will or not.

**Comment by cainmagi** [comment]
Thank you!

**Comment by facelessuser** [comment]
So I wanted to see how GitHub shortens its own gists:

https://gist.github.com/facelessuser/85c2682f1651ad8e63b2c695abf4bf2a

Doesn't look like they do anything really.

**Comment by facelessuser** [comment]
If you want to embed them, you can already just do:

```html
<script src="https://gist.github.com/facelessuser/85c2682f1651ad8e63b2c695abf4bf2a.js"></script>
```

So, I'm not really sure there is much we can do for gists.

I mean, maybe you could shorten the hash:

[gist.github.com/facelessuser/85c2682f](gist.github.com/facelessuser/85c2682f1651ad8e63b2c695abf4bf2a)

I guess that could be reasonable 🤷.
