### ISSUE TITLE
Unable to function in stand-alone app

### ISSUE THREAD

**Issue by kakkarja** [facelessuser/pymdown-extensions#1198]
Dear Sir, 
I have tried to built app with pyinstaller, and compile to one-file. Pymdown-extensions working find in ide, but it could not work after compile to  one-file. The raise exception said "no module pymdownx...". How do i resolve this? Thanks in advance.🙏

**Comment by facelessuser** [comment]
Unfortunately, I have no context at all. I don't know what you are doing. I have no error context of anything. It could simply be that Python Markdown itself has trouble finding extensions when bundled via Pyinstaller and needs special adjustments to work properly.

**Comment by facelessuser** [comment]
1. Without more information, I can't possibly begin to answer this question.
2. We don't do anything in particular which should prevent this from packaging via pyinstaller. I've used pyinstaller before, but it has been quite some time.
3. Most likely, this is an issue with either packaging the pymdown-extensions properly, or (maybe even more likely) Python Markdown's ability to source plugins; their approach in sourcing plugins may not work properly in pyinstaller, and may require some kind of monkey patch on your part.

In the end, this may be an upstream issue as we don't do any clever imports or anything like that. Or this is simply a bad pyinstaller setup. Additionally, I have absolutely no info go on to even begin to debug this, and, to be honest, nowhere do we guarantee this will work in pyinstaller.

@gir-bot add S: more-info-needed

**Comment by kakkarja** [comment]
Thank you for your reply answer, you are probably right, i never thought about it before. I shall see again into it and produce more reliable info of debug to be analyze. Thank you so much. 🙏

**Comment by kakkarja** [comment]
I found out that the module was not added to one file,  because the extension was expressed as a string in extensions. The probable solution could be:
1. I add new hook for pyisntaller. However, it may still not work, because of the string expression.
2. I can use with "add hidden module". Will probably work.
3. Or add as data, which i do not really know how, because which appropriate files are suppose to be added.

By the way, thank you for your response. I really appreciate it. 🙏

**Comment by facelessuser** [comment]
Yeah, I've only used Pyinstaller with a handful of projects in the past. It's definitely not a use case I plan for or test for. When I did use it, I do recall having to hack around to get certain modules and dependencies working, it's just the nature of using Pyinstaller, especially when it comes to anything less common like dynamic module imports like Python Markdown does with extensions.

**Comment by facelessuser** [comment]
This seems to be an issue outside of pymdown-extensions, and more a configuration issue of pyinstaller, so I will close this issue.
