### ISSUE TITLE
Bug: Comments remover is "too hungry"

### ISSUE THREAD

**Issue by deep9** [facelessuser/pymdown-extensions#1199]
This code
```
<!-- END INCLUDE --></li>
Wrongly removed content
<!-- BEGIN INCLUDE -->

```
will end up removing all the content

If there is no new line, it works as expected. The problem lies (i think) in the lookahead rule. If it is not there, it works.

Used version: pymdown-extensions             8.0.1

I have used the RE from master branch, and the problem persist.

**Comment by deep9** [comment]
The simpliest reproducible test is

````

<!-- END INCLUDE -->I want to survive<!-- BEGIN INCLUDE -->
```

Also looking at the RE, why is it eating all the whitespace? In my opinion the whitespace is significant for MD and I would rather have the newlines as written in the file, than those being eaten by comment remover.

**Comment by facelessuser** [comment]
@deep9 I cannot reproduce:

Input

```
import markdown
import pymdownx

print(f"Markdown: {markdown.__version__}")
print(f"Pymdown Extensions: {pymdownx.__version__}")

print("\n------ Results ------\n")

content = r'''
<!-- END INCLUDE -->I want to survive<!-- BEGIN INCLUDE -->

<!-- END INCLUDE --></li>
Wrongly removed content
<!-- BEGIN INCLUDE -->
'''

print(markdown.markdown(content, extensions=['pymdownx.striphtml']))

```

Output

```
Markdown: 3.3.3
Pymdown Extensions: 8.1.1

------ Results ------

<p>I want to survive</p>
<p></li>
Wrongly removed content</p>
```

@gir-bot remove S: triage
@gir-bot add T: bug, S: needs-confirmation

**Comment by deep9** [comment]
@facelessuser Thanks for the reply.

I've based my issue on the result I get when this extension is used in mkdocs, while disabling it does not remove the text, and also on the result of RE tests https://regex101.com/r/fhdIOA/1 where if you add/remove newlines will give you the wrong result (correct without newlines)

Running the standalone example works for me as well.

I'll give it another try and disable other extensions.

**Comment by facelessuser** [comment]
Yes, we need to narrow it down to the minimum requirements to reproduce. I'm happy to look into a fix once I understand what breaks it.

**Comment by deep9** [comment]
@facelessuser Sorry, did not see the reply. but for sure I know the problem is in the RE. I don't understand why simple `<!--[/s/S]*?-->` is not enough and there is the whitespace removal as well. I think I miss the use case :)

**Comment by deep9** [comment]
```
import markdown
text = r'''

Comments test:
<!-- BEGIN INCLUDE -->

- One
- Two
- Three
<!-- END INCLUDE -->

## Paragraph

<!-- BEGIN INCLUDE ../../_snippets/devices-operated-by-suitestdrive.md   -->
- One
- Two
- Three
<!-- END INCLUDE -->
Comments test end
'''

html = markdown.markdown(text, extensions=['pymdownx.striphtml'], extension_configs = {'pymdownx.striphtml': {'strip_js_on_attributes': False}})
html
```

This renders ok.

**Comment by facelessuser** [comment]
I have a fix. It's specifically the case that is expecting the comment to be on a line by itself. We strip non-essential new lines surrounding the comment in these cases, but the regex can be too greedy (as you pointed out) in certain cases. Simply adjusting the pattern to ensure `-` are not part of `-->` will allow us to properly gather the comment in this case:

```
"(?:(?:(?:\r?\n?\s*)<!--(?:-(?!->)|[^-])*?-->(?:\s*)(?=\r?\n)|<!--[\s\S]*?-->))"ga
```

There are sometimes subtle differences between regex engines which is why it maybe didn't manifest except under certain conditions with Python.

**Comment by deep9** [comment]
@facelessuser Thanks! 👍
