### ISSUE TITLE
Can I use page.canonical_url in snippets?

### ISSUE THREAD

**Issue by funkypenguin** [facelessuser/pymdown-extensions#1208]
Hey folks!

I'm trying to make better use of snippets in my mkdocs site, by including a "footer" snippet, which includes `{{ page.canonical_url }}`. The snippet folder is outside of my `docs` folder. The value of `{{ page.canonical_url }}` is not being replaced though - presumably because the snippet is just a markdown insertion.

Is there anything I can do to make this variable render in the snippet?

Thanks!
D

**Comment by facelessuser** [comment]
I mean, you can insert that content into your file via a snippet, but I'm not sure what is handling that template variable. Snippets is not a template engine, so it will not handle template variables on its own, but it will make that text available in the file. Are you using a plugin while parsing Markdown to handle template variables? Are template variables being handled pre/post Markdown parsing?

I have no idea what kind of document build system you are using, so I'm afraid I may not be much help.

**Comment by funkypenguin** [comment]
Sorry, context! I'm using mkdocs, if that's any help :)

**Comment by facelessuser** [comment]
Maybe something like this can help in conjunction with Snippets: https://github.com/rosscdh/mkdocs-markdownextradata-plugin. I can't promise it will, but it might. There may be other plugins or extensions, but something to be aware of.

Snippets can be configured to insert snippets that are outside of the docs directory, you just have to specify the [`base_path`](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#options). This is of course is documented. And Snippets is generally run before other Markdown plugins (though certainly, some plugins could potentially insert even earlier, but I am not currently aware of any that do.

Markdown processing is just one step in the MkDocs process. Python Markdown, which Snippets is run under, does not have the MkDocs projects' metadata of templates and such, it is just the page content.
So the best way is to use a MkDocs plugin, that maybe inserts that, not a Python Markdown extension, which does, in fact, have access to the Jinja environment. 

Now, is the above information enough? I don't know. Snippets was designed to simply be an easy way to inject content from one file to another before the actual Markdown processing begins.

Anyway, that is probably all I can offer at this time.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by facelessuser** [comment]
As there is no actionable item here, I will close this issue. If further discussion is desired, you can open up a thread in [Discussions](https://github.com/facelessuser/pymdown-extensions/discussions). I can't promise I have a solution, but it will give others an opportunity to potentially chime in and discuss what they do (if anyone has gone down this path).
