### ISSUE TITLE
Version differences in<details> section formatting?

### ISSUE THREAD

**Issue by zmontes-dev** [facelessuser/pymdown-extensions#1235]
From a post a few days ago on the mkdocs github. I should note I have been using .md files, I'm not sure if that makes a difference. 

In details sections, markdown is not rendering. It is working on:
`mkdocs, version 1.1 from c:\miniconda3\envs\old_env\lib\site-packages\mkdocs (Python 3.7`
and not working on:
`mkdocs, version 1.1.2 from c:\miniconda3\envs\new_env\lib\site-packages\mkdocs (Python 3.7)`

I am wondering what version differences with syntax or packages installed could be the cause. Running on windows

Please let me know what other info, if any, you will need to help us troubleshoot! Thanks

Example code:
```
##  **chart/calculate/**

<details>
<summary>Perform a calculation on two fluids</summary><br>

> **Required Arguments**:  

1. Requires `chartid`, `classA`, `classB`, `fileA`, `fileB`, `fluidA`, `fluidB`, `itemA`, `itemB`, `operation`  

> **Where**:    
1. `chartid`: Unique chart identifier, given as a string (e.g., first, A)    
2. `classA`: Fluid class for first fluid (e.g., field, region, well, wellid, etc.)     
3. `classB`: Fluid class for first fluid (e.g., field, region, well, wellid, etc.)     
4. `fileA`: First input fluid file name  (may have .obs, .ss_, .plt, .prod or .vdb extension)    
5. `fileB`: Second input fluid file name (may have .obs, .ss_, .plt, .prod or .vdb extension)    
6. `fluidA`: First input fluid name     
7. `fluidB`: Second input fluid name    
8. `itemA`: First input item    
9. `itemB`: Second input item    
10. `operation`: Desired operation to perform (given as: add, subtract, multiply, divide, average)    

> **Return values**:    
1. `error`: An error message. Set when *status is false*    
2. `status`: True if command succeeds, or false if it fails. If false, there will also be an error returned    
3. `newpid`: The unique ID for the calculated line; use this to reference it   
<summary>Examples</summary>
<details open>
<summary>Simple</summary> <br>    

>     -C "chart/calculate fileA=n_spe9_sss_sal.ss_wells classA=wellid itemA=P10 fluidA=\"Cumulative Production Oil\" fileB=n_spe9_sss_sal.ss_wells classB=wellid itemB=P11 fluidB=\"Cumulative Production Oil\" chartid=A operation=subtract" \  
</details> 
<details open>
<summary>Contextual</summary> <br>    

>     cv_chartserver -server "15324" & \    
>     cv_viewclient -c "15324" -o out/outA.png \    
>         -C "chart/create chartid=A height=800 width=1200 type=timeseries" \   
>         -C "chart/dataseries/add file=n_spe9_sss_sal.ss_wells class=wellid item=P10 fluid=\"Cumulative Production Oil\" chartid=A" \    
>         -C "chart/dataseries/add file=n_spe9_sss_sal.ss_wells class=wellid item=P11 fluid=\"Cumulative Production Oil\" chartid=A" \  
>         -C "chart/calculate fileA=n_spe9_sss_sal.ss_wells classA=wellid itemA=P10 fluidA=\"Cumulative Production Oil\" fileB=n_spe9_sss_sal.ss_wells classB=wellid itemB=P11 fluidB=\"Cumulative Production Oil\" chartid=A operation=subtract" \  
>         -C "window/refresh" \  
>         -C "exit" \  
</details>
</details>
```

**Comment by facelessuser** [comment]
I had assumed you were using the [Details extension](https://facelessuser.github.io/pymdown-extensions/extensions/details/), but you are not, you are using raw HTML.

So, Markdown version is probably the difference. Python Markdown rewrote how they handle raw HTML, and I believe `details` tags are now handled as block instead of inline. Inline tags have the Markdown parsed automatically, but not block tags.

So you have two options:

1. Use the raw HTML for details and use the [Markdon in HTML extension](https://python-markdown.github.io/extensions/md_in_html/) and mark your raw HTML block tag with the attribute `markdown="1"` to make it parse the content within.

2. Use the [Details extension](https://facelessuser.github.io/pymdown-extensions/extensions/details/) and specify Details with the syntax provided there.

**Comment by zmontes-dev** [comment]
Okay, well thanks for your help. I've never used the pymdownx extensions so it took me a bit to get up and running, but there is no bug here. Now I'm just looking at a lot of editing thanks to python's changes.
