### ISSUE TITLE
a tooltip extension

### ISSUE THREAD

**Issue by roipoussiere** [facelessuser/pymdown-extensions#1249]
I just created [a tooltip extension](https://roipoussiere.frama.io/mkdocs-tooltips/) for MkDocs, I just wonder if you are interested to include it in pymdown-extensions.

**Comment by facelessuser** [comment]
While I think the idea of the extension is neat, there are a couple of reasons why I would not support it here, the first being the most important:

1. I do not have time to support everyone's extensions, I only support mine. I encourage people to support their own extensions as I do not have the time to assume the burden. Pymdown Extensions is not a one-stop shop for all extensions, just a collection that I didn't find elsewhere and needed, so I wrote them.
2. I never inject CSS into Markdown output. Python Markdown is not guaranteed to be outputting a full HTML page, it may be outputting a small snippet meant to inject in a larger HTML. CSS and JS should be managed by the user, not the extension. I have no problem outputting content formatted for a JS library or for a specific CSS stylesheet, but I never include them automatically, see Arithmatex as an example.
3. While the concept is neat, I worry that the syntax conflicts with existing sytnax shipped with Python Markdown by default. For instance, let's say I have a reference. One of the things is that if the reference is not directly specified after the square bracketed syntax, and the name matches the reference name, the reference is used, then if I pair the `attr_list` extension to specify a class, I can get a conflict:

    ```
    [test]{.class}

    [test]: https://google.com
    ```

    I would at least consider maybe tweaking the syntax some.

Anyways, I think the idea is neat, but I, unfortunately, do not have the time to invest in everyone's plugin ideas, even if I think they are neat.

@gir-bot remove S: triage
@gir-bot add T: feature, S: wontfix

**Comment by roipoussiere** [comment]
Thank you for your long answer. Your first argument is indeed good enough to close the issue.

> 2. I never inject CSS into Markdown output. [...]

I don't manage CSS or JS as well, only small html blocks, and [the user have to add the CSS stylesheet](https://roipoussiere.frama.io/mkdocs-tooltips/installation/#2-get-hintcss) himself.

I'm concerned about 3., good point. I didn't know that `[ref]` alone was a valid syntax for references. To prevent conflicts with `attr_list` I could just check if the tooltip content starts with a `.` or `#` (that could be escaped). Do your think it's a good solution for this issue, or a better syntax is necessary?

**Comment by facelessuser** [comment]
I'm concerned about 3., good point. I didn't know that `[ref]` alone was a valid syntax for references. To prevent conflicts with `attr_list` I could just check if the tooltip content starts with a `.` or `#` (that could be escaped). Do your think it's a good solution for this issue, or a better syntax is necessary?

If you take a look at the syntax of `attr_list`, you'll see that that may not be enough: https://python-markdown.github.io/extensions/attr_list/#syntax.

I would probably do something unique at the beginning, something that cannot appear logically in `attr_list`. For instance, they allow an optional `:` at the beginning to be compatible with other implementations. I would just pick something else, maybe `?`. `?` does not start a class or id or an attribute value they Python Markdown accepts. So something like `[text]{?top|message}` may be fine. `?` is just the first thing that came to my mind, you can use anything unique really: `@`, `%`, etc. Or, maybe require it to use double braces: `text]{{top|message}}`. I really haven't thought about this much, but just throwing out some random ideas 🤷‍♂️.
