### ISSUE TITLE
[Question] Approach for mermaid with `superfences` here vs `mermaid2` plugin

### ISSUE THREAD

**Issue by polarathene** [facelessuser/pymdown-extensions#1254]
I noticed in [your `mkdocs.yml` you add `extra_javascript` with a content hash](https://github.com/facelessuser/pymdown-extensions/blob/e809f20f672cc350e2cb2c6c2d86e8438f329765/mkdocs.yml#L148) generated from your `gulp` build process. Are you manually running `gulp`, viewing the output hash and updating the entry manually in `mkdocs.yml`?

The docs for setting up mermaid were helpful but still a tad vague in the setup (which I understand based on the statement it's not something you want to provide support for). I didn't want to adopt the whole `gulp` process, so I just did a global install of [`parcel`](https://parceljs.org/) and ran `parcel build extra-uml.js` (doesn't create a content hash by default for the entry file).

From there I was able to reproduce your approach and realize it was unrelated to the `mermaid2` plugin that mentions `superfences` and I've seen you both discuss issues together about supporting `mermaid.js`. 

---

### Are you able to briefly confirm the difference between the `mermaid2` plugin and your alternative approach?

- `mermaid2` is a MkDocs plugin with minimal setup but has noticeable gotchas / incompatibilities to account for.
- For `superfences` MkDocs deployed here, you've avoided a tailored plugin and use `snippets` to inject two script tags to an HTML document? (the `mermaid.js` lib itself and a mermaid config for styling, additionally there's a SCSS partial)
  - In addition there is two JS files (`extra-uml.js`, `uml.js`) you've written (that are bundled into a single JS file for `extra_javascript` in `mkdocs.yml` and thus are included into every HTML page) cover detecting `mermaid` codefences and converting them through `mermaid.js` as well as detecting dark/light mode to toggle theme?
    - Is there a specific reason it's not just referenced from the `docs_dir` in your snippet? My understanding is that `extra_javascript` appends the script tag to all the built HTML files, but assets included in your `docs_dir` seem to still be carried over with builds if you don't need that.
    - I have seen that there's an additional copy of the JS output made after `gulp` processing located in [`src/markdown/_snippets/.code/extra-uml.js`](https://github.com/facelessuser/pymdown-extensions/tree/main/docs/src/markdown/_snippets/.code), albeit the `.` prefix prevents it being copied over for a build.
    - Then again, you have a 2nd [`mkdocs.yml`](https://github.com/facelessuser/pymdown-extensions/blob/e809f20f672cc350e2cb2c6c2d86e8438f329765/docs/src/mkdocs.yml#L148) in this `docs/src/` the only difference being the referenced assets have content hashes pointing to [`docs/theme/assets`](https://github.com/facelessuser/pymdown-extensions/tree/main/docs/theme/assets/pymdownx-extras) due to your [`theme: custom_dir:`](https://github.com/facelessuser/pymdown-extensions/blob/e809f20f672cc350e2cb2c6c2d86e8438f329765/mkdocs.yml#L12).
    - I assume there is some value in this approach, but the asset itself is still bundled manually and injected in a separate script tag, instead of `mkdocs build` including it in the main theme bundle js?

Apart from that, I gather `mermaid2` plugin is transforming the codefence to a div at build time (where I see it as a mess of text content until the JS kicks in), while the `superfences` approach you've deployed here doesn't modify content at all until run time (specific to `mermaid.js` that is and generic codefence handling/generation with `superfences`). Useful since your approach isn't impacted by the `minify` plugin bug and had no issue showing up in a `<details>` block (`mermaid2` rendered a blank), and that your use of Shadow DOM is to work around some style leakage issues with `mermaid.js` element IDs.

Did I miss anything? It'd seem your approach has notable advantages over the plugin besides the additional setup complexity and needing to include a snippet on pages that use `mermaid.js` as an optimization. I'm not aware of any other advantages/disadvantages between the two, or whatever MkDocs Material is doing differently.

---

### A slightly different approach

I'm going to investigate into a slightly different approach with `parcel` (which I'm new to using myself). It should be possible to have a lightweight entrypoint via code splitting, that can load on demand the other JS modules only when `mermaid` codefences are encountered. This should remove the optimization requirement of using a snippet (which is fine for me, but I want to minimize inconvenience for third-party contributors), and generate content hashes that are all handled implicitly, the entrypoint is just referenced in the `extra_javascript` for `mkdocs.yml` then.

For Github Pages at least, caching is a little annoying as we can't configure the cache-control headers (`max-age: 600`). If that's an issue I believe `parcel` can alternatively target the build output of `mkdocs` and go through each html file identifying the referenced JS file in script tag and modify the filename to include a content hash whilst doing the same for the JS file copied over.

`parcel` covers CSS (SCSS) too, I remember using `gulp` years ago, and while quite flexible `parcel` may be simpler and easier to maintain if it fits your needs too. Would you be interested in hearing how this approach pans out? If it does work out, it may be useful to extract that JS src out so it's not as tied to this project?

**Comment by polarathene** [comment]
>     4\. I do keep a `mkdocs.yml` in my docs directory. It is the source. The `mkdocs.yml` is the processed one where we inject the built/bundled CSS and JS.

> A matter of fact, once built, I package up the assets in this repo, so my other projects can just get the assets.

Ah ok, I was wondering why you'd have it like that if this was just for deploying to github pages it seemed unnecessary to commit such to the same repo. I have CI make a build and commit that to a `gh-pages` branch and is the only situation that content hashes are really relevant (shouldn't impact local dev/iteration).

> We choose to store the code in pre, code blocks instead of divs because we want things to fallback code blocks if Mermaid has issues loading

Is it a good fallback to have? I've considered that most users I'll have as an audience probably won't care for mermaid syntax which isn't always straight forward to ingest if you're not familiar with it and depending on what you're doing.

I'm still new to MkDocs ecosystem, but a little curious why no one seems to have considered just avoiding the JS payload of mermaid.js in production by processing the SVGs it can build and outputting that as that's the desired end result anyway and quite possibly lighter than the mermaid.js lib itself.

> Adoption of a different approach for me would be based on whether I'm experiencing enough pain to reinvent what I'm currently doing, but it is always nice to have more information for if/when I get to a point where I wish to rework things.

It'd be mostly what you've got setup already, just a little bit improved and can be extracted out from this repo (or rather benefit others like me from getting confused about the 3 different active approaches that seem to be commonly discussed, their differences and relevance to one another... originally I got the impression that `superfences` was backed by `mermaid2` due to MkDocs Material and `mermaid2` docs referencing each other and `superfences`).

> Keep in mind, I am not a web developer.

Yeah, I noticed that from a discussion between you and the `mermaid2` maintainer both mentioning your comfort zone is more in python. I'm the opposite :)

If I have any success with this and it's worthwhile, I'll let you know. I have no problem tackling JS package distribution either.

**Comment by facelessuser** [comment]
> Is it a good fallback to have?

For me? Yes. The syntax isn't helpful, but my personal opinion is that if/when Mermaid cannot be retrieved, it *looks* better. It is purely for aesthetic, not functional.

> I'm still new to MkDocs ecosystem, but a little curious why no one seems to have considered just avoiding the JS payload of mermaid.js in production by processing the SVGs it can build and outputting that as that's the desired end result anyway and quite possibly lighter than the mermaid.js lib itself.

Sure, I've considered it, and frankly, if I did, I'd probably use PlantUML. Originally I had some UML examples using some different JS libraries which don't seem to be well maintained anymore. They were pretty easy to setup. Generally, people really preferred Mermaid, and since it is at least maintained, I switched over to it. Overtime issues were discovered, and I dug in and found workarounds, which added more complexity on the back end.

The whole idea was something you could easily drop in, much as we do with MathJax. But obviously, it has become somewhat more complicated than that.

I don't want to have to require a more complex backend on all my other projects where they have to install PlanUML or a Mermaid CLI to generate docs. I prefer having just one project, which came about to improve my docs, where I build the assets for all my other projects than to have to replicate some UML backend on other projects. I also like that now that it is all set up, I can easily have the style change for light and dark mode, so I'm happy.

Would I do it the same if I had to start from scratch all over again? Especially for how rarely I use UML in my docs? Maybe not, but it is working, I like the current aesthetics, so this is what I have. It's not worth my time to invest more research and development when I have something I'm currently happy with.

> It'd be mostly what you've got setup already, just a little bit improved and can be extracted out from this repo (or rather benefit others like me from getting confused about the 3 different active approaches that seem to be commonly discussed, their differences and relevance to one another... originally I got the impression that `superfences` was backed by `mermaid2` due to MkDocs Material and `mermaid2` docs referencing each other and `superfences`).

SuperFences is mostly used in Material because Python Markdown's `fenced_code` extension doesn't nest well in lists and other constructs. That was my whole motivation in writing it. The custom fence stuff that is used to display Mermaid came about because once I wrote SuperFences, I never wanted to go through the hackery involved to do fenced type blocks ever again, so I added a way to reuse SuperFences by specifying special classes. There is a reason that `fenced_code` doesn't work so well, the architecture in Python Markdown has some big weaknesses, so SuperFences had to do a lot of work to give something more like people expected.

The fact that there are multiple ways to get Mermaid in MkDocs was never a concern to me. I use Mermaid in these docs just to show you can use SuperFences for other kinds of content with the custom fences. It could save people going through the pains of writing a SuperFences like extension. Mermaid2, I think, tries to package a lot of what I'm doing. Material tries to implement, to some extent, something similar. All of this is in an effort to make things easier for end users. They **want** to provide support so users can get Mermaid into their documents. I do not. My Mermaid work was so I can use it, but I am happy to document what I do to help reduce questions about Mermaid.

**Comment by polarathene** [comment]
> Sure, I've considered it, and frankly, if I did, I'd probably use PlantUML. Originally I had some UML examples using some different JS libraries which don't seem to be well maintained anymore. They were pretty easy to setup. Generally, people really preferred Mermaid, and since it is at least maintained, I switched over to it.

I actually was referring to using `mermaid.js` still, but at build converting the codefence to an SVG. There is a `mermaid-cli` that would allow for this. You can probably avoid the nodejs environment requirement and bundle a binary executable, albeit it might be a bit large for what it does. There's also a Docker image for such, but that's probably not acceptable for a lib to depend on.

I'm not familiar with the python side of things, but I assume there would be a way for `superfences` to identify `mermaid` codefences during `mkdocs build` (and I guess at `mkdocs serve`), where instead of the current formatter, it sends the content to an executable call and replaces the codefence with SVG markup returned (or an `<img>` element referencing an SVG file).

Those could additionally be run through something like [SVGOMG](https://jakearchibald.github.io/svgomg/) (which also has a CLI) as a minification/optimization step for further size reductions if desirable. But perhaps both of these things would be a hassle to support, I'm not familiar enough with the non-JS side of things.

Is it something a `superfences` custom formatter plugin can support? Does it then end up as something like `mermaid2` for installing separately via `pip install` and adding a customer formatter for it to `superfences` config?

Probably loses some of the `mermaid.js` features that aren't strictly SVG, but for anyone that doesn't want to do anything fancy it's probably a better solution.

> I don't want to have to require a more complex backend on all my other projects where they have to install PlanUML or a Mermaid CLI to generate docs. I prefer having just one project, which came about to improve my docs, where I build the assets for all my other projects than to have to replicate some UML backend on other projects. 

Yeah sure that's understandable. A simpler backend would just send the data to a URI and get the response back. There's a mermaid HTTP server for something like that AFAIK, and for those comfortable with docker, it would amount to 1 command in CI or copy/paste to have running. Might not meet your expectations but that'd decouple complexity and maintenance/requirements a bit too if it's just a formatter plugin that can make an HTTP request and apply the response. (I'm not asking this of you btw, just throwing the idea out there)

> I like the current aesthetics, so this is what I have. It's not worth my time to invest more research and development when I have something I'm currently happy with.

That's perfectly understandable, no worries :+1: 

> They want to provide support so users can get Mermaid into their documents. I do not. My Mermaid work was so I can use it, but I am happy to document what I do to help reduce questions about Mermaid.

Understood. Thanks for documenting what you have and being so responsive and helpful :)

**Comment by facelessuser** [comment]
> Is it something a `superfences` custom formatter plugin can support? Does it then end up as something like `mermaid2` for installing separately via `pip install` and adding a customer formatter for it to `superfences` config?

Sure, we actually use the custom formatter, we just don't do anything fancy. We put it in a code block, attach the mermaid class, and preserve the text while skipping the default highlighter. But you could easily have a custom formatter call out to some executable, etc.

https://github.com/facelessuser/pymdown-extensions/blob/main/mkdocs.yml#L87
