### ISSUE TITLE
Code-only bug: `Highlight(use_pygments=False, inline=True)` double-escapes the input

### ISSUE THREAD

**Issue by oprypin** [facelessuser/pymdown-extensions#1257]

**Comment by oprypin** [comment]
I say "code-only bug" because this never affects usage in Markdown:

```python
from markdown import Markdown

md = Markdown(extensions=['pymdownx.highlight', 'pymdownx.inlinehilite'], extension_configs={'pymdownx.highlight': {'use_pygments': False}})
md.convert('`#!c foo&bar`')
# '<p><code class="language-c highlight">foo&amp;bar</code></p>'
```

---

But if you use the class directly, the output doesn't make sense:

```python
from pymdownx.highlight import Highlight
from xml.etree.ElementTree import tostring

el = Highlight(use_pygments=False).highlight('foo&bar', inline=True, language='c')  # <Element 'code'>
el.text
# 'foo&amp;bar'
tostring(el)
# b'<code class="language-c highlight">foo&amp;amp;bar</code>'
```

So, this is double-escaped

---

Why this happens:

The input is escaped here:
https://github.com/facelessuser/pymdown-extensions/blob/29873da7921e7f2edf6c0e214ea90f501e1854b0/pymdownx/highlight.py#L321
Then escaped code is used as the text of a tag:
https://github.com/facelessuser/pymdown-extensions/blob/29873da7921e7f2edf6c0e214ea90f501e1854b0/pymdownx/highlight.py#L358-L359
which signals the intent that it should be escaped again.

The reason that this isn't causing any immediate problem is that the only place that uses this combination *doesn't* escape the output, even though it should:
https://github.com/facelessuser/pymdown-extensions/blob/e809f20f672cc350e2cb2c6c2d86e8438f329765/pymdownx/inlinehilite.py#L145-L148

**Comment by facelessuser** [comment]
@oprypin, Unfortunately, I'm dealing with Python Markdown's handling. You see if I use Python Markdown's serializer, it works fine:

```py
from markdown import Markdown
from markdown.serializers import _write_html
from pymdownx.highlight import Highlight
from xml.etree.ElementTree import tostring

md = Markdown(
    extensions=['pymdownx.highlight', 'pymdownx.inlinehilite'],
    extension_configs={'pymdownx.highlight': {'use_pygments': False}}
)
print(md.convert('`#!c foo&bar`'))
# '<p><code class="language-c highlight">foo&amp;bar</code></p>'

el = Highlight(use_pygments=False).highlight('foo&bar', inline=True, language='c')  # <Element 'code'>
el.text
# 'foo&amp;bar'
print(_write_html(el))
# '<code class="language-c highlight">foo&amp;bar</code>'
```

So you must approach this from the perspective of how Python Markdown is doing this. At least in Python Markdown's case, you have to look at `etree` simply as a structure to hold the content. Python Markdown runs it through its own serializer.

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add S: wontfix

I'm marking this as `wontfix` for now. I currently can't see a reason to change this, even if technically what you say is true, when compared with the context of how it is actually used, the statement, in practice, is false.

**Comment by oprypin** [comment]
Oh... hmmm but actually that doesn't help much for this case:

```python
from markdown import Markdown
from pymdownx.highlight import Highlight
from markdown.serializers import _write_html

el = Highlight().highlight('foo&bar', inline=True, language='c')  # <Element 'code'>
el.text
# '<span class="n">foo</span><span class="o">&amp;</span><span class="n">bar</span>'
_write_html(el)
# '<code class="highlight">&lt;span class="n"&gt;foo&lt;/span&gt;&lt;span class="o"&gt;&amp;&lt;/span&gt;&lt;span class="n"&gt;bar&lt;/span&gt;</code>'
```

Markdown's serialization is actually never involved here, it always goes through `htmlStash` for `inline=True`.

**Comment by oprypin** [comment]
But yeah even then there's no real-world advantage to changing this. And it's difficult to handle the case *with* Pygments. What are you supposed to do, unescape it? :/

What I would personally do is to not wrap it into an actual element but return it as a string, just with an opening and closing tag (again, as a string) added around it.

But it's also not trivial to do and, again, what's the point of changing it.


Thanks for the explanation

**Comment by oprypin** [comment]
> What I would personally do is

Well, I *did* actually do that elsewhere

For reference:
https://github.com/mkdocstrings/mkdocstrings/blob/e111f12014cfebd6becc7823fbf503babe318f17/src/mkdocstrings/handlers/base.py#L194-L195
https://github.com/mkdocstrings/mkdocstrings/blob/c29ba6b6b9babce7f17372e7e5b3a1299814e6f8/src/mkdocstrings/handlers/base.py#L206-L210
