### ISSUE TITLE
[Feat]: Snippets support relative paths

### ISSUE THREAD

**Issue by polarathene** [facelessuser/pymdown-extensions#1275]
I'm not sure if you have context on the location of the file being parsed, but would it be possible to support snippets relative to the file with detected snippet syntax `--8<--` declaration?

Eg.

```
project/
├─ _snippets/
│  ├─ some_snippet.txt
│  ├─ nested_docs_snippets/
│  │  ├─ snippet_a.md
│  │  ├─ snippet_b.md
├─ docs/
│  ├─ docs_category/
│  │  ├─ subcategory/
│  │  │  ├─ another_directory/
│  │  │  │  ├─ .snippets/
│  │  │  │  │  ├─ snippet_a.md
│  │  │  │  │  ├─ snippet_b.md
│  │  │  │  ├─ nested_docs_page.md
│  ├─ index.md
mkdocs.yml
```

Could `nested_docs_page.md` instead include a `.snippets` directory relative to it as above and refer to the contents like:

```
--8<-- "./.snippets/snippets_a.md"

...

--8<-- "./.snippets/snippets_b.md"
```

As opposed to a top-level shared directory that all pages need to organize their snippets within? 

Supporting such should work fine if the path was checked prior to prepending a base path to join to, unless the extension can only receive the file contents and has no way to know the received files path to check the snippet relative path?

https://github.com/facelessuser/pymdown-extensions/blob/63de7ea258b3e4141c24b8f84a3ec276499866b5/pymdownx/snippets.py#L110

For larger projects, it's handy for maintenance to have the snippets co-located if they're tied to that specific file.

**Comment by facelessuser** [comment]
Python Markdown parsers buffers, and so file context is not available. There are hacky ways to get that info. You could do this by having a plugin inject that info into the meta data structure via the `meta` extension, but it is not a standard thing. That is why we specify a base directory. To make things easy, I usually just have a flat snippet folder, so relative to file vs relative to the base is a non-issue. I don't have complex needs in this area, but, if I did, I could see how this would be desirable. Regardless, whether desirable or not, there is not an easy way to handle this as the context is just not there.

**Comment by polarathene** [comment]
Ah...no worries then. I was a bit tired when writing that out, I ended up keep the snippets local and just writing the longer path from docs dir (content) to the files snippets folder like so:

```markdown
???+ example

    --8<-- "content/contributing/documentation/.snippets/examples-tabbed-content.md"
```

That works well enough and is mostly copy/paste a prefix path used elsewhere in the document or find/replace if updating references from moving the doc page or other restructuring above it like renaming a category.
