### ISSUE TITLE
Include only specific lines from snippet

### ISSUE THREAD

**Issue by julwin** [facelessuser/pymdown-extensions#1288]
Hi,

would it be possible to include only specific lines from a referenced file as snippet?
Where would you suggest implementing something like this?

```python
--8<-- "docs/snippet.py:13-25"
```

**Comment by facelessuser** [comment]
This is not supported, and I'm not sure if would be. Snippets was designed to be a simple way to insert reusable files. Parsing a file to get a subset of a file is probably an unlikely direction for this extension. At least at this time.

**Comment by facelessuser** [comment]
As we do not have any intention at this time to provide such functionality, we will close this issue.
