### ISSUE TITLE
Potential double-unescaping in pymdownx.highlight

### ISSUE THREAD

**Issue by oprypin** [facelessuser/pymdown-extensions#1290]
Comparing this piece of code:

https://github.com/facelessuser/pymdown-extensions/blob/29873da7921e7f2edf6c0e214ea90f501e1854b0/pymdownx/highlight.py#L373-L378

with the bug that this pull request fixed:

https://github.com/Python-Markdown/markdown/pull/990/files#diff-934821cde110094c262f0f04b5e98feadce02b43ea311dd1c3d72d77b5c44860

-- I assume that the same issue affects this code and needs to be fixed in the same way.

I haven't run into this myself, though, and haven't confirmed the issue.

**Comment by facelessuser** [comment]
Pull requests are welcome as well. Either way, thanks for the report!
