### ISSUE TITLE
How did you get the "Source" and "Edit this page" icon and links to work ?

### ISSUE THREAD

**Issue by akharrou** [facelessuser/pymdown-extensions#1356]
I really like how you got the two buttons "Edit this page" and "Source" on your website and I really want to do something like that, and also have a link to a PDF version of the page. I was wondering how you get that effect ?

![image](https://user-images.githubusercontent.com/36056254/120919445-48aa2f80-c6c2-11eb-93e3-899634201e9d.png)

Thanks.

**Comment by facelessuser** [comment]
All I do is add this before my first title header:

```
[:octicons-file-code-24:][_critic]{: .source-link }

# Title
```

I'm using the [`attr_list` extension](https://python-markdown.github.io/extensions/attr_list/) to assign `.souce-link` class to the link. I'm also using the [`pymdownx.emoji` extension](https://facelessuser.github.io/pymdown-extensions/extensions/emoji/) to assign the image. In this case though, I'm accessing the Material theme's icon resources by using [this Material addition](https://github.com/facelessuser/mkdocs-material-extensions) with the emoji extension.

Lastly, I style the icon by targetting the class `source-link`: https://github.com/facelessuser/pymdown-extensions/blob/main/docs/src/scss/_general.scss#L13. The link provided links to the SCSS source that is then compiled to CSS.

Anyways, that's basically it.

I will go ahead and move this question to discussions as this is neither a bug or feature request.
