### ISSUE TITLE
Snippets - maintaining indent when used in a list

### ISSUE THREAD

**Issue by slutske22** [facelessuser/pymdown-extensions#1392]
Thank you for this great extension!  I am trying to use a snippet within an ordered list. (This is in an mkdocs-material project).  Is there any way to keep the code block positioned with the left margin in line with the list?  For example, if I write this:

    6. In the Configuration tab, ...

    ```sh
    --8<--
    docs/jenkins/agents/agentsetup.sh
    --8<--
    ```

The result is this:

<kbd>
<img width="765" alt="Screen Shot 2021-07-20 at 8 18 06 AM" src="https://user-images.githubusercontent.com/52637023/126350121-f4714269-e7ef-424b-b514-45928617fe35.png">
</kbd>

It doesn't really look like this codeblock is part of that list item.  I can indent the filename:

    6. In the Configuration tab, ...

    ```sh
    --8<--
        docs/jenkins/agents/agentsetup.sh
    --8<--
    ```

But this indents the code *within* the file, not the block itself:

<kbd>
<img width="601" alt="Screen Shot 2021-07-20 at 8 18 52 AM" src="https://user-images.githubusercontent.com/52637023/126350249-b312db45-9aa6-4055-bcf9-381ab3380551.png">
</kbd>

I know this is nitpicky, but I was wondering if you had any ideas on if the block can be indented, or made to match its parent list.  I read #114, which seems related, but was having a hard time connecting the dots in a list context.  

Thanks!

**Comment by facelessuser** [comment]
You mean like this?

````
6. In the Configuration tab, ...

    ```sh
    --8<--
    docs/jenkins/agents/agentsetup.sh
    --8<--
    ```
````

Or maybe I am misunderstanding something?

**Comment by facelessuser** [comment]
I am, of course, assuming you are using SuperFences which allows for nesting fenced blocks under lists. The built-in `fenced_code` extension that ships with Python Markdown will not allow this.

**Comment by slutske22** [comment]
SuperFences!  That did it for me.  Thank you!
