### ISSUE TITLE
Tests fail on latest Pygments 2.1.1

### ISSUE THREAD

**Issue by bcaller** [facelessuser/pymdown-extensions#14]
Empty span blocks appear. If you rerun Travis on the current working build it will fail.

```
--- C:\Users\Ben\DEV\PycharmProjects\pymdown-extensions\tests\extensions\superfences (no indent blocks).html
+++ C:\Users\Ben\DEV\PycharmProjects\pymdown-extensions\tests\extensions\results.html
@@ -1,18 +1,18 @@
 <h1>Neseted Fences:</h1>
-<div class="codehilite"><pre>This will not be parsed
+<div class="codehilite"><pre><span></span>This will not be parsed
 as a normal indented code block.
 It will be parsed as a fenced block.
 </pre></div>

```

**Comment by bcaller** [comment]
Possibly relevant:
https://bitbucket.org/birkenfeld/pygments-main/commits/164574c13533
https://bitbucket.org/birkenfeld/pygments-main/issues/1111/an-empty-line-at-first-has-been-ignored

**Comment by facelessuser** [comment]
Understood and thanks for the info.  You don't need to worry about anything outside the scope of this pull.  As long as lint and your tests are passing, things are okay.

**Comment by facelessuser** [comment]
I should have said your pull instead of this.  Didn't realize this was a new issue.

**Comment by facelessuser** [comment]
Fixed in the following commit: https://github.com/facelessuser/pymdown-extensions/commit/87057283e0b232714f94687db105410aa926df8a.
