### ISSUE TITLE
A problem with Arithmatex

### ISSUE THREAD

**Issue by Dup4** [facelessuser/pymdown-extensions#1445]
Hi.

I tested the arithmatex and found a problem

The `requirements.txt` I use:

```plaintext
# Direct dependencies
mkdocs>=1.2.2
Pygments>=2.10.0
markdown>=3.3
mkdocs-material >= 7.2.6
mkdocs-material-extensions>=1.0

pymdown-extensions>=8.2
mkdocs-minify-plugin >= 0.4.0
mkdocs-git-revision-date-localized-plugin >= 0.9.3
pyspelling >= 2.7.3
git+https://github.com/facelessuser/pymdown-lexers.git
```

The version of mathjax I use: `https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js`

The arithmatex configuration I use: 
```yaml
- pymdownx.arithmatex:
    generic: true
```

The mathjax configuration I use: 
```js
window.MathJax = {
  tex: {
    inlineMath: [ ["\\(","\\)"] ],
    displayMath: [ ["\\[","\\]"] ],
    processEscapes: true,
    processEnvironments: true
  },
  options: {
    ignoreHtmlClass: ".*|",
    processHtmlClass: "arithmatex"
  }
};
```

The mathematical formula that went wrong:

```latex
$$
% outer vertical array of arrays 
\begin{array}{c}
% inner horizontal array of arrays
\begin{array}{cc}
% inner array of minimum values
\begin{array}{c|cccc}
\text{min} & 0 & 1 & 2 & 3\\
\hline
0 & 0 & 0 & 0 & 0\\
1 & 0 & 1 & 1 & 1\\
2 & 0 & 1 & 2 & 2\\
3 & 0 & 1 & 2 & 3
\end{array}
&
% inner array of maximum values
\begin{array}{c|cccc}
\text{max}&0&1&2&3\\
\hline
0 & 0 & 1 & 2 & 3\\
1 & 1 & 1 & 2 & 3\\
2 & 2 & 2 & 2 & 3\\
3 & 3 & 3 & 3 & 3
\end{array}
\end{array}
\\
% inner array of delta values
\begin{array}{c|cccc}
\Delta&0&1&2&3\\
\hline
0 & 0 & 1 & 2 & 3\\
1 & 1 & 0 & 1 & 2\\
2 & 2 & 1 & 0 & 1\\
3 & 3 & 2 & 1 & 0
\end{array}
\end{array}
$$
```

I found that this math formula is rendered empty.

But if I remove the comment statement, such as `% outer vertical array of arrays`, the rendering is work.

The complete mathematical formula after remove comment statement is as follows:

```latex
$$
\begin{array}{c}
\begin{array}{cc}
\begin{array}{c|cccc}
\text{min} & 0 & 1 & 2 & 3\\
\hline
0 & 0 & 0 & 0 & 0\\
1 & 0 & 1 & 1 & 1\\
2 & 0 & 1 & 2 & 2\\
3 & 0 & 1 & 2 & 3
\end{array}
&
\begin{array}{c|cccc}
\text{max}&0&1&2&3\\
\hline
0 & 0 & 1 & 2 & 3\\
1 & 1 & 1 & 2 & 3\\
2 & 2 & 2 & 2 & 3\\
3 & 3 & 3 & 3 & 3
\end{array}
\end{array}
\\
\begin{array}{c|cccc}
\Delta&0&1&2&3\\
\hline
0 & 0 & 1 & 2 & 3\\
1 & 1 & 0 & 1 & 2\\
2 & 2 & 1 & 0 & 1\\
3 & 3 & 2 & 1 & 0
\end{array}
\end{array}
$$
```

The rendering result is as follows:

![image](https://user-images.githubusercontent.com/38343778/132940704-1e96ccf3-6553-423f-9373-493b9901b81a.png)

Therefore, I guess it is the annotation that caused the rendering that did not meet expectations.

So I tested the math formula source code that has not been rendered by mathjax but only processed by pymdown-extensions.

The result is as follows:

![image](https://user-images.githubusercontent.com/38343778/132940803-bf72a8ce-42b3-496f-973e-ee44014da145.png)

I found that the source code after pymdown-extensions processing has no newline characters, which may cause all content after% to be recognized as comments, this may be the cause of the problem.

In addition, I also tested it, if the newline character is preserved, the rendering is work.

The result is as follws:

![image](https://user-images.githubusercontent.com/38343778/132940887-04a70039-23a4-46d3-86fa-d7293e0c59c1.png)

You can use this [website](http://mathjax.pastego.cn) to reproduce.

So can arithmatex preserve line breaks when parsing mathematical formulas?

**Comment by facelessuser** [comment]
Just to let you know, I am not seeing this issue. But, I'm using the Default version, not the Generic output. Expand the example below. (FYI, I'm using MathJax 3).

<details>
<summary>Example</summary>
Input with comments:

```
# Arithmatex

$$
% outer vertical array of arrays 
\begin{array}{c}
% inner horizontal array of arrays
\begin{array}{cc}
% inner array of minimum values
\begin{array}{c|cccc}
\text{min} & 0 & 1 & 2 & 3\\
\hline
0 & 0 & 0 & 0 & 0\\
1 & 0 & 1 & 1 & 1\\
2 & 0 & 1 & 2 & 2\\
3 & 0 & 1 & 2 & 3
\end{array}
&
% inner array of maximum values
\begin{array}{c|cccc}
\text{max}&0&1&2&3\\
\hline
0 & 0 & 1 & 2 & 3\\
1 & 1 & 1 & 2 & 3\\
2 & 2 & 2 & 2 & 3\\
3 & 3 & 3 & 3 & 3
\end{array}
\end{array}
\\
% inner array of delta values
\begin{array}{c|cccc}
\Delta&0&1&2&3\\
\hline
0 & 0 & 1 & 2 & 3\\
1 & 1 & 0 & 1 & 2\\
2 & 2 & 1 & 0 & 1\\
3 & 3 & 2 & 1 & 0
\end{array}
\end{array}
$$
```

Output:

<img width="482" alt="Screen Shot 2021-09-11 at 6 28 55 AM" src="https://user-images.githubusercontent.com/1055125/132947967-66eb0760-1afd-4534-b7f7-b6a68c1059a1.png">
</details>

Now, using Generic mode, I can see that the issue occurs, but we are in fact preserving everything. Do not look at the output, on the viewable HTML, but let's look at the actual source code. It is all there:

```html
<div class="MathJax_Preview">
% outer vertical array of arrays 
\begin{array}{c}
% inner horizontal array of arrays
\begin{array}{cc}
% inner array of minimum values
\begin{array}{c|cccc}
\text{min} &amp; 0 &amp; 1 &amp; 2 &amp; 3\\
\hline
0 &amp; 0 &amp; 0 &amp; 0 &amp; 0\\
1 &amp; 0 &amp; 1 &amp; 1 &amp; 1\\
2 &amp; 0 &amp; 1 &amp; 2 &amp; 2\\
3 &amp; 0 &amp; 1 &amp; 2 &amp; 3
\end{array}
&amp;
% inner array of maximum values
\begin{array}{c|cccc}
\text{max}&amp;0&amp;1&amp;2&amp;3\\
\hline
0 &amp; 0 &amp; 1 &amp; 2 &amp; 3\\
1 &amp; 1 &amp; 1 &amp; 2 &amp; 3\\
2 &amp; 2 &amp; 2 &amp; 2 &amp; 3\\
3 &amp; 3 &amp; 3 &amp; 3 &amp; 3
\end{array}
\end{array}
\\
% inner array of delta values
\begin{array}{c|cccc}
\Delta&amp;0&amp;1&amp;2&amp;3\\
\hline
0 &amp; 0 &amp; 1 &amp; 2 &amp; 3\\
1 &amp; 1 &amp; 0 &amp; 1 &amp; 2\\
2 &amp; 2 &amp; 1 &amp; 0 &amp; 1\\
3 &amp; 3 &amp; 2 &amp; 1 &amp; 0
\end{array}
\end{array}
</div>
```

So, the question is what the real issue is. I and I believe it is that MathJax, with the given generic configuration, as a difficult time parsing the valid code. I believe it is having difficulty somehow dealing with the comments when reading from the `<div>`. I'm not sure why as the info is all there.

Now, could that be that we need to do something more when post-processing? Maybe, I'm not sure yet.

**Comment by facelessuser** [comment]
The config for Generic was written early in MathJax 3.0 beta releases. The config requirements must have changed. I've been able to get MathJax in "generic" mode to partially parse by modifying the config.

As a workaround, I'd use the suggested "default" configuration as I'm still working through what an appropriate "generic" configuration would be.

**Comment by Dup4** [comment]
Now, using the `default` configuration, it works.

Thank you and your awesome project.

**Comment by facelessuser** [comment]
Okay, turned out I was being dumb. I forgot to turn `generic: true` on in my config. Generic works fine for me as well. I'm using the default suggested config with no issues.

I did have to turn of the `mkdocs-minify-plugin >= 0.4.0` plugin. It removes whitespace. It seems so obvious now 🤦🏻. `default` works around this as it wraps the math in scripts and the minify plugin won't touch that.

So, in the end, all is working fine 🙂.

**Comment by facelessuser** [comment]
FAQ entry has been added about this very issue: https://github.com/facelessuser/pymdown-extensions/commit/cdb93e927ecc01c7fa536312d46ebd20adbb9fe8. This effectively resolves this issue. Docs will be updated in the next, upcoming release.
