### ISSUE TITLE
cannot find module 'tools.pymdownx_md_render' during the serve document process

### ISSUE THREAD

**Issue by Dup4** [facelessuser/pymdown-extensions#1446]
I try to clone the repo and build documents locally.

Follow this [tutorial](https://facelessuser.github.io/pymdown-extensions/about/development/#building-and-editing-documents) as follows:

![image](https://user-images.githubusercontent.com/38343778/133027287-1e1cee58-27bc-42d7-9a17-b22cb61e1223.png)

But I failed, the following is my operation process:

[![asciicast](https://asciinema.org/a/435367.svg)](https://asciinema.org/a/435367)

I try to find the source of the problem.

In [`mkdocs.yml`](https://github.com/facelessuser/pymdown-extensions/blob/main/mkdocs.yml#L96) , need a function named `tools.pymdownx_md_render.md_sub_render`, the function is located in the [`tools/pymdownx_md_render.py`](https://github.com/facelessuser/pymdown-extensions/blob/main/tools/pymdownx_md_render.py).

But the `tools` directory is excluded in [`setup.py`](https://github.com/facelessuser/pymdown-extensions/blob/main/setup.py).

Therefore,  if we only install the [`pymdown-extensions`](https://github.com/facelessuser/pymdown-extensions), the function will not be included.

So I am particularly curious, how did you build the documents for this repo.

**Comment by facelessuser** [comment]
Because I'm running some code directly from tools you need to the do the following:

```
python3 -m mkdocs serve
```

That will include the CWD directory so that the "tools" module will be found.

**Comment by Dup4** [comment]
> Because I'm running some code directly from tools you need to the do the following:
> 
> ```
> python3 -m mkdocs serve
> ```
> 
> That will include the CWD directory so that the "tools" module will be found.

It works. Thank you.

**Comment by facelessuser** [comment]
I do not ship `pymdownx_md_render` in `pymdown-extensions`.  It is only used for my documentation, so you cannot access it simply by installing `pymdown-extensions`.

I have no idea what you are doing or how your project is organized. Based on the error, I can only assume you did not copy my personal, custom script into your project.

Keep in mind that I do not provide support for my own personal scripts that I do not document and do not include in the released package. You use them at your own risk and are often left to figure out how to use them yourself.

**Comment by SPyofgame200** [comment]
Also the collapsible block feature (which I really want to have), hmmmmmm, it isn't render as expected right now

**Comment by facelessuser** [comment]
Anything in this project's tool folder you can copy into your project as it is all licensed under MIT. Currently, I have not opted to officially support anything in the tool folder and distribute them in any of my releases.

You are free to copy the files from tools to your project and adapt them as required. I provide no documentation and do not provide any support currently for them. 

I am not exactly sure what you are referring to when you mention "collapsible" blocks. If you are talking about Details, we have to different extensions that can handle that. If you are talking about my custom script in the tools folder to provide collapsible code blocks, those are undocumented and unsupported, but they will require custom CSS.

**Comment by SPyofgame200** [comment]
I thought [Progressbar](https://facelessuser.github.io/pymdown-extensions/extensions/progressbar/#progressbar) has its own documentation, but there are [issues](https://github.com/squidfunk/mkdocs-material/issues/862) related to it ?

**Comment by facelessuser** [comment]
If you have an issue with progressbar, please open a new issue and provide a reproducible example and explain your issue.

**Comment by facelessuser** [comment]
What you've linked is an issue about material not providing CSS for progressbar. If it doesn't provide CSS, you have to provide your own.
