### ISSUE TITLE
Deactivate linenums on a per-codeblock basis, when linenums are set to True in mkdocs.yml

### ISSUE THREAD

**Issue by rodrigoschwencke** [facelessuser/pymdown-extensions#1486]
### Description

Would it be possible to add the following feature (to be used with mkdocs, and mkdocs material) :
1°) Activate automatic linenumbering for all codeblocks, by default, in the file `mkdocs.yml` with the syntax :
```
markdown_extensions:
  - pymdownx.highlight:
      linenums: True
```
AND
2°) Deactivate automatic linenumbering on a per-codeblock basis, for example with the following syntax in a specific codeblock:

    ```python linenums="0"
    print("That would be reeeaally great, and thank you sooo much!")
    ```

### Benefits

A new feature that might be really useful to some users :)

**Comment by facelessuser** [comment]
So this looks completely doable. We never allowed negative values for `linenums` anyways, and in the case of zero, we just remapped it to one. Instead, we will ensure that the start is only allowed when one or greater. This will essentially disable line lines, even when globally enabled if this condition is not met.

Branch is available at https://github.com/facelessuser/pymdown-extensions/commit/4c87d04a66b18c23c21f4222f6d875811793da60. Tests still need to be written, but the feature will target the 9.1 release.
