### ISSUE TITLE
Adding attributes to SuperFences does not work when `linenums: true`

### ISSUE THREAD

**Issue by DominikaK** [facelessuser/pymdown-extensions#1505]
### Description

[`data-` attributes added to code blocks](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#injecting-classes-ids-and-attributes) are ignored when `linenums` is set to `true` in `markdown_extensions.pymdownx.highlight`.

When `linenums` are disabled, the attribute is set correctly on the `<div>` element.

### Minimal Reproduction

1. Configure Superfences, Highlight and `attr_list` markdown extensions:
```
markdown_extensions:
    - attr_list
    - pymdownx.highlight:
        linenums: true
    - pymdownx.superfences
```
2. Crate a code block with a custom class and attribute:
` ``` {.python3 .test-class data-attr-test="test-value"}`
3. Preview the content. The results look like:
```
<table class="test-class highlighttable">
    <tr>
        <td class="linenos">
            <div class="linenodiv">
                <pre>
                <!-- -->
                </pre>
            </div>
        </td>
        <td class="code">
            <div class="test-class highlight">
            <!-- -->
            </div>
        </td>
     </tr>
</table>
```

When `linenums: true` is removed, the result is:
```
<div class="test-class highlight" data-attr-test="test-value">
     <pre>
          <span></span>
         <code>
         <!-- -->
         </code>
     </pre>
</div>
```

### Version(s) & System Info

- Operating System: Windows 10
- Python Version: 3.2.8
- Package Version: 9.0

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add S: confirmed

Yeah, this is a bug. Apparently, we forgot to add logic to insert data attributes when a Pygments table formatted code block is returned (which is used with line numbers).

Hmm, I guess we need to decide where to stick the attributes. Do we attach them to the top-level `table` element? Or do we attach them to the code content `pre` or `code` element?

**Comment by facelessuser** [comment]
I have it working locally with tables now:

```html
<table class="test-class highlighttable" data-attr-test="test-value"><tr><td class="linenos"><div class="linenodiv"><pre><span></span><span class="normal">1</span></pre></div></td><td class="code"><div class="test-class highlight"><pre><span></span><code><span class="o">...</span>
</code></pre></div>
</td></tr></table>
```

The main question is whether it makes sense to attach it to the table like it is above or target the `<div>` with the code content.

**Comment by facelessuser** [comment]
The alternative would be this which targets the code content div.

```html
<table class="test-class highlighttable"><tr><td class="linenos"><div class="linenodiv"><pre><span></span><span class="normal">1</span></pre></div></td><td class="code"><div class="test-class highlight" data-attr-test="test-value"><pre><span></span><code><span class="o">...</span>
</code></pre></div>
</td></tr></table>
```

**Comment by facelessuser** [comment]
I think it may make sense to just do what we do with other Pygments blocks and just attach to the top level element, in this case table.
