### ISSUE TITLE
MagicLink: Autolink should not occur in anchor tags

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/pymdown-extensions#151]
Currently there is no way to prevent autolinking inside a link easily.  There is some discussion on passing ancestors to inline patterns over at Python Markdown.  This would alleviate the issue for auto-linking repository pull, commit, issue, and mentions as well as auto-linking bare links.

This issue is a reminder that MagicLinks should take advantage of the solution **if** it gets implemented in Python Markdown.

https://github.com/Python-Markdown/markdown/issues/596

**Comment by waylan** [comment]
Amusingly, I checked your MagicLink extension for GitHub shorthand features and only implementing mine after not finding an existing solution. Now that I have a working solution, you've enhanced this to match and then some. But then, I probably wouldn't use this anyway because I don't need everything else that comes with pymdown.

**Comment by facelessuser** [comment]
I had the link shortening for the 3 big (only?) git providers for a while and had the intention of adding the repo auto-links, but I have been lazy. When I saw your solution via mkdocs pull, I considered just using yours, but when I saw it was very GitHub centric, I decided to finally get off my butt and implement it for the 3 biggest popular git services.  The big 3 use similar syntax at times, but not quite, so I had to pick what generally made the most sense for all 3.

But having a GitHub implementation makes sense as well as it is probably the single biggest provider, and for many people is probably all they need or want.  And yours is more true to GitHub syntax than mine when it comes to commits. I really liked your take on repo mentioning syntax though, so I blatantly stole that syntax 🙂 .

> But then, I probably wouldn't use this anyway because I don't need everything else that comes with pymdown.

That's fair.  They can be used separately, but I totally get it. I suspect most people only use a very small subset of them.  In retrospect, I maybe should of had them as separate extensions than one giant pack.  At the time I didn't think many people would be using them.  I'm kind of surprised as many people have adopted them as is.

**Comment by waylan** [comment]
I agree, the two extensions can easily both exist. I was just amused that my work prompted you to do your work.

By the way, I like your URL shortening stuff. I intended to do something similar, so I may borrow that from you.

**Comment by facelessuser** [comment]
> By the way, I like your URL shortening stuff. I intended to do something similar, so I may borrow that from you.

Feel free.  I think it really adds the complete feel with both of them, but I am biased :slightly_smiling_face: .

**Comment by facelessuser** [comment]
I believe 2.6.10 now has the fix for this, so work can begin.
