### ISSUE TITLE
Make content fill the whole screen

### ISSUE THREAD

**Issue by unison3** [facelessuser/pymdown-extensions#1514]
### Description

having to scroll across to view code in code boxes is kind of embarrassing in this day and age, it would seem quite simple to change a fixed value to fill the rest of the screen real estate with a percentage value instead

### Benefits

less people would be put off in joining the computer programming industry if the documentation was more inviting to them and those already leaning from it on a daily basis would also find it very beneficial. Also would help with RSI as moving the mouse unnecessarily can be a pain for a wanker like my mate who is always complaining that it takes time out that he could be doing his 5 knuckle shuffling! lol

### Solution Idea

change one line of code!

**Comment by facelessuser** [comment]
I'm getting the impression this is a complaint about our project's documentation? General formatting and styling are handled upstream by the theme we are using: https://squidfunk.github.io/mkdocs-material/. Styling is subjective, and there will always be some that like certain aspects of our documentation, and some that don't. I do not have any intentions to make large formatting overrides to the current theme we use.

**Comment by facelessuser** [comment]
If you are not referring to my documentation, then I believe you need to locate the project that is causing your documentation to not fill the whole screen as we do not provide any CSS styling, we just generate HTML elements.

**Comment by facelessuser** [comment]
I read over this again, as I was pretty confused. We do not generate any styling to restrict width in any way. If you are unhappy with any styling of anything that is generated, it is because **you** are providing the styling, or **you** are using some external styling (possibly by some documentation theme). Again, we are not responsible for whatever theme you are using.
