### ISSUE TITLE
Allow [[key]] syntax in addition to ++key++

### ISSUE THREAD

**Issue by alkisg** [facelessuser/pymdown-extensions#1517]
### Description

[This is a very nice vscode extension](https://marketplace.visualstudio.com/items?itemName=jebbs.markdown-extended) that allows live-preview to markdown documentation writers, without having to press `Alt+Tab` to switch to a `mkdocs serve` browser and wait for 5 seconds for the build to finish.

It's [compatible with admonitions](https://marketplace.visualstudio.com/items?itemName=jebbs.markdown-extended#extended-syntaxes) and many others of the pymdown-extensions. But unfortunately not with kbd, as it's using [[Ctrl+Esc]] instead of ++Ctrl+Esc++.

### Benefits

If the [[key]] syntax was supported in addition to ++key++ (or even just as [[key]]), then people would be able to preview the result while writing documentation in vscode.
And, it would improve the world's markdown compatibility!
https://xkcd.com/927/

**Comment by kgidarakos** [comment]
This feature affects me too.  I hope it will be added soon! 
Thank you in advance.

**Comment by facelessuser** [comment]
It cannot be expected that all people that create an extension for a different Markdown Parser have to conform to one unified syntax unless that syntax is part of the core Markdown behavior, which it isn't.

And who is to decide what that unified syntax should look like? I understand you have a leaning towards the Markdown-it implementation that is used in VSCode, but currently, I have a number of sites that all use the current `kdb` syntax I cooked up for Python Markdown. I get that you may prefer `[[key+key]]`, but right now I prefer `++key+key++`. Why must we change and not them? *I pose this question only to illustrate a point as I don't expect them to, nor would I ever ask them to.*

I currently have no intention of maintaining a Markdown-it compatibility bridge.

**Comment by alkisg** [comment]
Personally I have no preference as my documentation was written in mediawiki previously and it was using a completely different syntax. If I was to decide from scratch, I'd use ``` :kbd:`C-x C-f` ``` like [Sphinx roles define](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html).
As you can see from the link above, I also asked the same question in markdown-it:
https://github.com/jGleitz/markdown-it-kbd/issues/440

Agreeing on the same markdown syntax would merge the userbases and make it more possible for others like e.g. pandoc to eventually support the same syntax.
Not agreeing and supporting both syntaxes is also OK, it would allow both userbases to keep their existing documents without modifications.
The users that use both projects would be happier, as they would be able to both preview-while-editing and publish content.

Of course what you said is also understandable and your existing efforts are already very appreciated. It was just a feature request.

So far I wasn't affected by any other incompatibilities, I didn't see the need for a bridge.

**Comment by squidfunk** [comment]
I second @facelessuser – as long as it's not standardized, it doesn't make sense to add more and more flavors. Furthermore, wait until you see what other Markdown parsers are missing that you take for granted when using SuperFences.

**Comment by facelessuser** [comment]
> Of course what you said is also understandable and your existing efforts are already very appreciated. It was just a feature request.

Understood. Hopefully, I didn't come off too strong, but for these types of requests, I like to lay out my thinking process.

While many rely on just pymdown-extensions, this extension set was never meant to be THE extensions. There are many out there, and people are free to create their own or even fork some of mine to better suit their needs. This doesn't mean I'm not open to new ideas and such, but I'm just one guy maintaining this project, and every new thing that gets added, is something new I have to maintain, so I'm kind of selective on what I add.

**Comment by alkisg** [comment]
Thank you guys. Seeing that it's hard to end up in a common convention, we ended up using this syntax:
`` **`Ctrl`**+**`Alt`**+**`Del`** ``

Benefits:

- It renders nicely anywhere, even here on Github: **`Ctrl`**+**`Alt`**+**`Del`** 
- With a custom css for `strong > code` we are able to add a shadow etc to make it look even more like a key

Drawbacks:

- The markdown source code is a big long and ugly.

Then we started extending that idea to other areas, e.g. we're now using `***` (=strong>em) for menus and GUI labels:
Launch ***Applications*** ▸ ***Utilities*** ▸ ***Calculator*** and then press the ***OK*** button.

This displays nicely in any markdown environment, and with a custom css we're giving them a button-like appearance.
