### ISSUE TITLE
Allow custom superfences formatter to raise exceptions

### ISSUE THREAD

**Issue by timvink** [facelessuser/pymdown-extensions#1526]
### Description

I would like to be able to raise an exception from a custom fence formatter, like so:

```python
def fence_custom(source, language, class_name, options, md, **kwargs):
    raise Exception("hi")
```

Now, if an error occurs, it is ignored and input is formatted as a code block.

A [validator](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#validators) is not an option because I'm interested in validating the `source`.  

P.s. Really like your work on custom fence formatters & the documentation on your approach with mermaid really helped! 

### Benefits

I'm writing a new mkdocs plugin ([link](https://github.com/timvink/mkdocs-charts-plugin)), and this would help end users find errors their input code blocks instead of silently failing. 

### Solution Idea

Some ideas:

- Add a new validator for the source
- Add a boolean flag argument to the custom fence function to allow raising errors
- Add an option to the `pymdownx.superfences.custom_fences` to allow raising errors

**Comment by facelessuser** [comment]
1. The idea is to provide graceful handling, that is the intention.
2. Validator is mainly for validating input options in the fence header, so that wouldn't really work for you.

With all of that said, maybe we can provide a specific exception that we allow, like `SuperFenceException`.
And the user can raise it from whatever other exception they want: https://docs.python.org/3/tutorial/errors.html#exception-chaining.

So the user would catch their exception and raise it with `SuperFenceException` from whatever they captured. We would ignore all exceptions except an explicit `SuperFenceException`.

Something to think about.

@gir-bot remove S: triage

**Comment by timvink** [comment]
Sounds like an elegant solution. I'd love to be able to choose to raise a helpful error, but I also see why you ignored all errors in the first place (the fallback option is graceful).

**Comment by facelessuser** [comment]
Okay, so this is what I've currently prototyped:

````py
import markdown
import codecs
from pymdownx.superfences import SuperFencesException

md = """
```custom
text
```
"""


def custom_fail(source, language, class_name, options, md, **kwargs):
    """Broken format."""

    raise SuperFencesException from Exception('Boom!')


html = markdown.markdown(
    md,
    extensions=['pymdownx.superfences'],
    extension_configs={
        "pymdownx.superfences": {
            'custom_fences': [
                {
                    'name': 'custom',
                    'class': 'custom',
                    'format': custom_fail,
                }
            ]
        }
    }
)

print(HTML)
````

Here we can see how it works. By default, exceptions will get swallowed and never seen, but if you purposefully raise the exception with a `SuperFencesException`, the exception will raise. So, it will be up to the user to capture the exception and decide whether they want to pass it on.

Output:

```console
➜  pymdown-extensions git:(main) ✗ python3 example.py
Exception: Boom!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/facelessuser/Code/github/pymdown-extensions/example.py", line 18, in <module>
    html = markdown.markdown(
  File "/usr/local/lib/python3.9/site-packages/markdown/core.py", line 387, in markdown
    return md.convert(text)
  File "/usr/local/lib/python3.9/site-packages/markdown/core.py", line 261, in convert
    self.lines = prep.run(self.lines)
  File "/Users/facelessuser/Code/github/pymdown-extensions/pymdownx/superfences.py", line 873, in run
    return self.search_nested(lines)
  File "/Users/facelessuser/Code/github/pymdown-extensions/pymdownx/superfences.py", line 710, in search_nested
    self.eval_fence(ws, content, start, end)
  File "/Users/facelessuser/Code/github/pymdown-extensions/pymdownx/superfences.py", line 425, in eval_fence
    self.process_nested_block(ws, content, start, end)
  File "/Users/facelessuser/Code/github/pymdown-extensions/pymdownx/superfences.py", line 474, in process_nested_block
    code = self.formatter(
  File "/Users/facelessuser/Code/github/pymdown-extensions/pymdownx/superfences.py", line 207, in _formatter
    return _fmt(src, language, class_name, options, md, **kwargs)
  File "/Users/facelessuser/Code/github/pymdown-extensions/example.py", line 14, in custom_fail
    raise SuperFencesException from Exception('Boom!')
pymdownx.superfences.SuperFencesException
```

I imagine we can do this with validators as well.

**Comment by timvink** [comment]
Yeah that's perfect for my use case (warning user about incorrect vega-lite syntax in mkdocs-charts-plugin).

Looking forward to the release :)
