### ISSUE TITLE
tests: additional fixes for the latest python markdown

### ISSUE THREAD

**Issue by sandrotosi** [facelessuser/pymdown-extensions#1539]
### Description

here attached a patch that provides additional fixes needed to get the test suite to pass on debian unstable with an up-to-date python markdown

[tests-more-fixes-for-latest-markdown.patch.txt](https://github.com/facelessuser/pymdown-extensions/files/7772811/tests-more-fixes-for-latest-markdown.patch.txt)

### Minimal Reproduction

n/a

### Version(s) & System Info

n/a

**Comment by facelessuser** [comment]
I don't understand what this patch is "fixing". All of the results are incorrect because it appears Pygments isn't running. Pymdown Extensions should not be running any different on Debian than it does on any other distro, or operating system for that matter. I imagine whatever is being fixed is a specific local issue on your machine, not with our test suite.

**Comment by sandrotosi** [comment]
argh.. pygments is not mentioned in requiremets/project.txt or test.txt only in extra.txt; is extra.txt actually needed to run tests?

**Comment by facelessuser** [comment]
Pygments is required in https://github.com/facelessuser/pymdown-extensions/blob/main/requirements/extra.txt. It is an extra as it is not explicitly required. Highlighting can be done with a JavaScript highlighter instead of Pygments if Pygments is not desired, but we must test Pygments.

**Comment by sandrotosi** [comment]
sounds like it belongs in tests.txt then, but i got the tip of knowledge i need and tests pass on debian.

**Comment by facelessuser** [comment]
> sounds like it belongs in tests.txt then, but i got the tip of knowledge i need and tests pass on debian.

It is required in more than just tests, so it is included in extra.txt so we can include it in other CI tasks: https://github.com/facelessuser/pymdown-extensions/blob/main/tox.ini#L20.

**Comment by sandrotosi** [comment]
you can also define that dependencies in tests.txt by adding a line `-r extra.txt` in it, https://stackoverflow.com/a/11704396

**Comment by facelessuser** [comment]
Sure, there are a number of ways we *could* do it, but this is the way we are currently doing it. We instead configure such things in `tox` as that is how we currently run our tests.
