### ISSUE TITLE
Keep the specified language CSS class when colorizing a code block

### ISSUE THREAD

**Issue by oprypin** [facelessuser/pymdown-extensions#1572]
### Description

For a code block like this,

    ```python
    a = True + 1
    ```

the HTML that `pymdownx.highlight` produces starts with the following:

`<div class="highlight"><pre><span>`

The code block is highlighted with the correct language and then the language specifier is not present anywhere in the output.

---

And note that the highlighted case actually differs from the "un-highlighted" use of `fenced_code_blocks`:

https://python-markdown.github.io/extensions/fenced_code_blocks/#language says:

> Either of the above examples will output the following HTML: `<pre><code class="language-html"`...

### Benefits

I think that keeping the language identifier in the output would let users make customizations more safely. For example, one could write this CSS to make "`$ `" terminal prompts non-selectable with mouse:

```css
.highlight.language-console .gp { /* Generic.Prompt */
  user-select: none;
}
```

([live example with this](https://mkdocstrings.github.io/crystal/))

But right now one is forced to write this unqualified:

```css
.highlight .gp { /* Generic.Prompt */
  user-select: none;
}
```

which also can affect blocks in other languages where it may not have been expected.

---

Another major use case might just be to provide a different look per language, say, a background color or an icon preceding it.

### Solution Idea

So I think `pymdownx.highlight` should be able to produce HTML that includes the language as a CSS class, for example:

`<div class="highlight language-console"><pre><span>`

---

Right now there's only a workaround to achieve such an output -- to write, for example,

    ```{.console .language-console}
    $ pip install pip
    ```

**Comment by facelessuser** [comment]
This will most likely be behind an optional feature flag to enable. I don't think it would hurt anything to have it in by default, but it is also not needed unless you need it. I'm not sure I have strong feelings about this, but just the way I'm leaning right now.

**Comment by eitansuez** [comment]
i was hoping to use the language-class to define a prompt for shell codeblocks

```
pre code.language-shell::before {
  content: '$ ';
}
```

the above comments seem to imply there's already support for a prompt with code blocks?  can you point me to where i can find out more?

**Comment by facelessuser** [comment]
> the above comments seem to imply there's already support for a prompt with code blocks? 

What comment implies this?

In the future, there are plans to attach the language class to Pygments code blocks (on the outer div). This is already done when Pygments is disabled so that JS highlighters can target code blocks and use the appropriate language, but hasn't been supported on Pygments code blocks in the past.

**Comment by facelessuser** [comment]
@eitansuez, it's possible I misunderstood your question. If you are just looking for a console highlighter with a terminal prompt, you can try using the language `console`:

````markdown
```console
$ echo "test"
test
```
````

**Comment by alkisg** [comment]
@eitansuez, just a note, eventually you might need to write some complicated code, for example:

```shell
$ command <<EOF
A heredoc string
$(a command inside the heredoc string)
EOF

$ for f in *; do
command
done

$ printf "A
multiline
string"
```

In these cases, having the `$` added automatically in each and every line will break your instructions, as it will be inserted inside heredocs, inside loop, inside strings etc. It would need to be done by a very intelligent shell parser, not highlighter, that would understand all the shell syntax and that would know where each command starts and where it ends.

**Comment by facelessuser** [comment]
Yes, auto injecting prompts can be very complicated. It isn't impossible, but you'd have to implement special custom fences. To some extent, I've done this in custom fences in this project: https://facelessuser.github.io/coloraide/.

It's not trivial though. We wanted to have code blocks where you just enter Python code and then that code would be run and translated to an output that looked like an interactive Python console:

So this:

```py
from coloraide import Color
c = Color('red')
c.coords()
c.to_string()
```

would become this:

```py
>>> from coloraide import Color
>>> c = Color('red')
>>> c.coords()
[1.0, 0.0, 0.0]
>>> c.to_string()
rgb(255 0 0)
```

It requires us to use Python's AST parser though on each code block, further, we run Python in the browser using Pyodide to let people interact within on the page (but that is a whole other topic 🙂).

Anyways, definitely, something that is difficult to generically provide.

**Comment by eitansuez** [comment]
so i came across this example documentation -- https://learnk8s.io/kubernetes-network-packets
note how bash blocks are styled like a shell and yaml codeblocks are styled like a text editor.  that's the sort of thing i want to be able to achieve.  and highlights the importance of keeping the metadata in the html.  anyhow, i gotta figure out how they do that.. :-)

**Comment by facelessuser** [comment]
FWIW, the language class will be included in the next release. A new release should happen sometime soon. It'll be interesting to see the kinds of things people do with it 🙂.
