### ISSUE TITLE
Addition of touch-id-sensor for keys extension

### ISSUE THREAD

**Issue by mrmanc** [facelessuser/pymdown-extensions#1582]
### Description

It looks like the [key map](https://facelessuser.github.io/pymdown-extensions/extensions/keys/#key-map-index) for the keys extension does not include an entry for the touch ID sensor on some Macbooks (and potentially other laptops). I noticed that there is also no entry for a power key.

### Benefits

It would be possible to refer to the key when writing documentation about how to easily lock your screen.

**Comment by facelessuser** [comment]
Can you provide what the proposal is? I'm honestly not sure what you mean by:

> entry for the touch ID sensor on some Macbooks

I'm a mac user, but I'm not sure what you are referring to.

**Comment by mrmanc** [comment]
Apologies… I will try to be more clear 😃 

Using the ‘keys’ extension I can represent keystrokes using `++control+command+q++` or individual keys such as `++option++`. I wanted to represent the new touch-sensitive power button that has appeared on recent Macbooks such as the M1 Macbook Pro. I believe the touch ID sensor button and power button are semantically different given the note at the bottom of [this Apple docs section](https://support.apple.com/en-us/HT201236#sleep). However, I was unable to find a key mapping in [the docs](https://facelessuser.github.io/pymdown-extensions/extensions/keys/#key-map-index) that represented these keyboard buttons.

**Comment by facelessuser** [comment]
There are always going to be some niche keys on some systems, or maybe some inputs outside the normal ASCII realm. We mainly provide ASCII inputs and some common, general inputs.

Keep in mind that you can also do custom keys as well: `++"my-custom-button"++. Just quote the content and you can enter whatever you like:

<img width="232" alt="Screen Shot 2022-01-26 at 12 12 33 PM" src="https://user-images.githubusercontent.com/1055125/151230661-464d6915-819c-4f88-9a9c-766c51defb44.png">

You can also add the to your `key_map` [(as described in the docs)](https://facelessuser.github.io/pymdown-extensions/extensions/keys/#extendingmodifying-key-map-index) and drop the needed quotes. Just map the key ID to some text:

<img width="221" alt="Screen Shot 2022-01-26 at 12 12 39 PM" src="https://user-images.githubusercontent.com/1055125/151230682-e7fed92d-329d-4dee-a926-8785c980adf8.png">

With all of that said, could maybe add this as some defaults. I mean, `power` is pretty universal, I think I'm okay adding that. Touch is a bit specific to certain systems, but yeah, it is making its way into other systems. Granted, I think "Touch ID" is an Apple-specific term, so maybe a more generic term like `touch` or `fingerprint` or something like that would make more sense as a generic term. Though, maybe we could have `touch-id` and `fingerprint` depending on if you are talking about a mac system or non-mac system. I don't know though, I'm not sure if I'd prefer a single generic term or multiple variants....

**Comment by mrmanc** [comment]
I thought it might be considered a little niche, but since there were entries for things like `option`, I thought I’d raise the question. I agree that `power` is pretty universal. Something generic like `fingerprint` sounds great. I think `touch` on it’s own feels mildly ambiguous, as people might think it relates to the touch bar, or even some other form of touch interface. I think you are right that Touch ID refers specifically to the Apple technology.

Thanks for the pointer about custom keys and adding to `key_map`. My eyes were drawn to the table of keys and I hadn’t scanned the text above! I’ll see if I can figure out how to add entries via mkdocs configuration in the meantime.

**Comment by facelessuser** [comment]
Sounds good, I'll put this feature on my Todo list.

**Comment by mrmanc** [comment]
Awesome, thanks so much! Love the keys extension.
