### ISSUE TITLE
GitHub extension deprecation

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/pymdown-extensions#159]
Let's be honest, the `github` extension is not a true GFM emulator.  And even though it includes extensions that come closish to GitHub features, it doesn't, and will never, emulate true GFM. Further, I have no intentions of following changes of GFM and ensuring we are synced up.  Recent repository link shorthand feature is GitHub like, but honestly closer resembles GitLab.

The GitHub extension represents something that is really no longer a goal in any way, shape, or form for pymdown-extensions. Yes some features are inspired by GitHub, but I'm not looking to match GitHub.

Let's deprecate the extension and let people pick and choose what extensions they like.  And if they pick extensions that closely resemble GitHub's GFM, then that is fine.

**Comment by sleepyhollo** [comment]
First off, great project. Thanks for this!

Did not want to create a new issue so thought I will mention this here.

The "GitHub-ish Configurations" in the [FAQ][1] was a little confusing for me. I am trying to use `python-markdown` to generate html outputs form local markdown files. The default formatting is ugly, so I was looking for a cookie-cutter config/extension that would make my markdown look prettier.

It took me some time before I could get the instructions in [FAQ][1] to work, so I am requesting that they be changed. I tried copy pasting the the text into a json file and running it; but the file is not formatted as a json. I used the following JSON file.

```
{
  "extension_config": {
      "pymdownx.magiclink": {
          "repo_url_shortener": true,
          "repo_url_shorthand": true,
          "provider": "github",
          "user": "facelessuser",
          "repo": "pymdown-extensions"
      },
      "pymdownx.tilde": {
          "subscript": false
      },
      "pymdownx.emoji": {
          "emoji_index": "pymdownx.emoji.gemoji",
          "emoji_generator": "pymdownx.emoji.to_png",
          "alt": "short",
          "options": {
              "attributes": {
                  "align": "absmiddle",
                  "height": "20px",
                  "width": "20px"
              },
              "image_path": "https://assets-cdn.github.com/images/icons/emoji/unicode/",
              "non_standard_image_path": "https://assets-cdn.github.com/images/icons/emoji/"
          }
      }
  }
}
```
It also took me some time to realize that I have to include all the extensions separately as below.

```
python -m markdown -x markdown.extensions.tables -x pymdownx.magiclink -x pymdownx.betterem -x pymdownx.tilde -x pymdownx.emoji -x pymdownx.tasklist -x pymdownx.superfences -c githubish.json md_file.md > out.html
```
I am most probably not doing it right, but if I am then I feel the FAQ should be expanded to include this two bits of information for people with less knowledge on these things.

[1]: https://facelessuser.github.io/pymdown-extensions/faq/#github-ish-configurations
