### ISSUE TITLE
Highlight: Improve documentation on extend_pygments_lang 

### ISSUE THREAD

**Issue by wilhelmer** [facelessuser/pymdown-extensions#1622]
### Description

While using the `extend_pygments_lang` option of the Highlight extension, I faced some minor issues:

1. [This](https://github.com/facelessuser/pymdown-extensions/blob/bbe726b498453ef9e40a9730e5a6e7684614f20a/docs/src/markdown/extensions/highlight.md?plain=1#L77) line in the docs should read "extend_pygments_lang" instead of "extend**ed**_pygments_lang".
2. It wasn't clear to me how to translate the config example to proper YML code for `mkdocs.yml`. Luckily, I found [this test](https://github.com/facelessuser/pymdown-extensions/blob/439c386976345c666189665af2c88fe0b8dfd60a/tests/extensions/superfences/tests.yml#L54) in your sources, that helped a lot. 
3. The `name` value is case-sensitive, which wasn't expected. So if you use, e.g., `PHP-inline` in your code and define `name: php-inline`, syntax highlighting won't work. Normally, the language aliases are case insensitive. (Not sure whether that's a Pygments issue or can be fixed in your extension.)

### Minimal Reproduction

See description.

### Version(s) & System Info

- Operating System: macOS Monterey
- Python Version: 3.9.10
- Package Version: 9.0

**Comment by facelessuser** [comment]
> [This](https://github.com/facelessuser/pymdown-extensions/blob/bbe726b498453ef9e40a9730e5a6e7684614f20a/docs/src/markdown/extensions/highlight.md?plain=1#L77) line in the docs should read "extend_pygments_lang" instead of "extended_pygments_lang".

Most likely a typo.

> It wasn't clear to me how to translate the config example to proper YML code for mkdocs.yml. Luckily, I found [this test](https://github.com/facelessuser/pymdown-extensions/blob/439c386976345c666189665af2c88fe0b8dfd60a/tests/extensions/superfences/tests.yml#L54) in your sources, that helped a lot.

Unfortunately, pymdown-extensions is really directly related to YAML. Packages like MkDocs happen to use YAML to configure underlying things like pymdown-extensions.  I've added a section in the [FAQ](https://facelessuser.github.io/pymdown-extensions/faq/#function-references-in-yaml) for less common YAML usage (specifying Python functions etc.) to avoid lots of questions, but it is difficult to document "how to use YAML" in general. To use MkDocs, there is assumed to be some familiarity with YAML.

> The name value is case-sensitive, which wasn't expected. So if you use, e.g., PHP-inline in your code and define name: php-inline, syntax highlighting won't work. Normally, the language aliases are case insensitive. (Not sure whether that's a Pygments issue or can be fixed in your extension.)

This is probably a reasonable issue. Frankly, it is probably something I overlooked. I usually specify my extended languages as lower case and I use them as lower case in Markdown files. It's something I must have just forgotten to handle.

This is definitely an action item I should look into.

**Comment by facelessuser** [comment]
I've fixed the typo. I will also address the case-sensitivity issue sometime soon.

**Comment by facelessuser** [comment]
I have a PR up for the other issue. I need to write some tests and such, but it should make it into the next release.
