### ISSUE TITLE
Fenced code does not apply language class when Sphinx is installed

### ISSUE THREAD

**Issue by eddiezab** [facelessuser/pymdown-extensions#1635]
### Description

When using a virtualenv (not tested outside of virtualenv) once Sphinx is installed, fenced code does not apply the classes to the code elements.

[01-test.md](https://github.com/facelessuser/pymdown-extensions/files/8253914/01-test.md)

### Minimal Reproduction

Using the attached test file:

```
python3 -m venv .env
. .env/bin/activate
pip install pymdown-extensions==9.2
python -m markdown -x pymdownx.superfences 01-test.md`
```

The output renders as expected:
```
<h1>This is a H1</h1>
<pre class="highlight"><code class="language-bash">whoami</code></pre>
```

```
pip install Sphinx==4.4.0
python -m markdown -x pymdownx.superfences 01-test.md
```

Observe, the difference in rendering:

```
<h1>This is a H1</h1>
<div class="highlight"><pre><span></span><code>whoami
</code></pre></div>
```

### Version(s) & System Info

- Operating System: Debian GNU/Linux 11
- Python Version: 3.9.2
- Package Version: 9.2

**Comment by facelessuser** [comment]
I do not use sphinx. Does installing `sphinx==4.0.0` change any of your other dependencies? Anyways, this sounds like a sphinx issue, not a pymdown-extension issue. We don't include sphinx, we don't use sphinx, so if sphinx is messing things up, you'd have to take it up with them. Unless something can be shown that we are doing wrong, I'm not sure what to say.

**Comment by facelessuser** [comment]
As no more info has been provided, I can only assume this is a local, environment issue. Closing as a "won't fix" for now.
