### ISSUE TITLE
pygments v2.12.0 breaks pymdownx.superfences

### ISSUE THREAD

**Issue by MichaIng** [facelessuser/pymdown-extensions#1665]
### Description

Since [pygments update today](https://github.com/pygments/pygments/blob/master/CHANGES), code fences are not correctly translated when using `pymdownx.superfences`, e.g.:
````markdown
```sh
code
```
````
is translated to:
```html
<code>sh code</code>
```
i.e. what should have been a `<pre>` tag with shell syntax highlighting has become a `<code>` tag with `sh` as plain text content.  Also without code highlighting, it becomes a `<code>` tag only. This was observed with MkDocs. Downgrading `pygments` to `<2.12` solves the issue.

I'm not sure whether this is an issue with `pymdown-extensions`, requiring an update or `pygments` introducing an unintended change/bug, but reporting it here did fit better since code fences, including `markdown.extensions.codehilite`, without `pymdownx.superfences` works well.

#### OOT

In this context I btw found interesting that with `pymdownx.superfences` enabled, `pymdownx.highlight` is used automatically even when only `markdown.extensions.codehilite` is enabled explicitly. Generally not an issue, I guess this is even necessary in our case to have code fences in `pymdownx.tabbed` correctly highlighted, but I just want to verify, so we can remove `markdown.extensions.codehilite` safely from our MkDocs config.

### Minimal Reproduction

Reproducing on Debian/APT based distros:
````sh
sudo apt install python3-distutils
curl -sSfO 'https://bootstrap.pypa.io/get-pip.py'
sudo python3 get-pip.py
rm get-pip.py
pip3 install mkdocs pymdown-extensions pygments
cat << '_EOF_' > mkdocs.yml
site_name: Test
markdown_extensions:
- pymdownx.superfences
_EOF_
mkdir docs
cat << '_EOF_' > docs/index.md
```sh
code
```
_EOF_
mkdocs build
grep code site/index.html
````

To resolve:
```sh
pip3 install 'pygments<2.12'
mkdocs build
grep code site/index.html
```

### Version(s) & System Info

- Operating System: Debian Bullseye and Bookworm
- Python Version: 3.9.2 and 3.10.4
- Package Version:
    ```
    Markdown==3.3.6
    mkdocs==1.3.0
    Pygments==2.12.0
    pymdown-extensions==9.3
    ```

**Comment by facelessuser** [comment]
> In this context I btw found interesting that with pymdownx.superfences enabled, pymdownx.highlight is used automatically even when only markdown.extensions.codehilite is enabled explicitly. Generally not an issue, I guess this is even necessary in our case to have code fences in pymdownx.tabbed correctly highlighted, but I just want to verify, so we can remove markdown.extensions.codehilite safely from our MkDocs config.

SuperFences does not use Codehilite. This is documented.

With that said, I was notified of this issue today. I'm hoping to get around to resolving the issue today or tomorrow.

**Comment by MichaIng** [comment]
> SuperFences does not use Codehilite. This is documented.

Thanks for clarification, makes sense anyway.

> I'm hoping to get around to resolving the issue today or tomorrow.

Great, many thanks! I can test a solution once available.

**Comment by facelessuser** [comment]
I do have a solution in the works

**Comment by facelessuser** [comment]
A branch is now available for testing. I still have to update documentation and test with a couple other projects to make sure I have proper support for my projects.

@squidfunk This may or may not require some downstream changes to styling for MkDocs Matrerial. Mainly Table code blocks. I don't use Table code blocks, so I cannot confirm the impact to Material yet.

**Comment by MichaIng** [comment]
Works here, tested, starting with above replication steps, then:
```sh
pip3 install -U 'https://github.com/facelessuser/pymdown-extensions/archive/bugfix/pygments.tar.gz' 'pygments>=2.12'
mkdocs build
grep code site/index.html
```
And the code fence is translated to `<pre>` tag successfully.

**Comment by facelessuser** [comment]
The release will require Pygments 2.12+ moving forward. I didn't want to abstract it as the changes were going to be too messy to abstract.
