### ISSUE TITLE
[Feature Request] Highlight pymdownx.snippets embedded files with pymdownx.highlight

### ISSUE THREAD

**Issue by tylernguyen** [facelessuser/pymdown-extensions#1673]
### Description

Hello,

It seems that files embedded with`pymdownx.snippets` are not highlighted with `pymdownx.highlight`

Options such as `linenums: true` also do not seem to applied to these embedded files.

The syntax I'm using is

```lua "file.lua"
--8<-- "includes/file.lua"
```

### Benefits

I like to host files on multiple repos and then embed them as a Git submodule. This way, changes are reflected without also having to change things in my docs.

**Comment by tylernguyen** [comment]
It seems my syntax was wrong. On a second look, embedded files do get highlighted.

**Comment by facelessuser** [comment]
Glad you figured it out :)
