### ISSUE TITLE
snippets check_paths does not work for nested includes

### ISSUE THREAD

**Issue by OmarTawfik** [facelessuser/pymdown-extensions#1682]
### Description

Currently, the `check_paths` option works well for 1st level includes, for example, if `two.md` in the example below does not exist, an error would be raised. However, that doesn't happen for nested includes, so if `three.md` doesn't exist, it will fail silently.

### Minimal Reproduction

`docs/one.md`:

```md
--8<-- "docs/two.md"
```

`docs/two.md`:

```md
--8<-- "docs/three.md"
```

`docs/three.md`:

```md
content here.
```

### Version(s) & System Info

Tested on `v9.4` and above.

**Comment by facelessuser** [comment]
I would need to understand more about your setup. We have tests that validate this behavior. We also use nested snippets in our own documentation without issues.

@gir-bot add needs-confirmation, more-info-needed

**Comment by facelessuser** [comment]
I guess I didn't read this closely. I see it mentions check paths, so I'll take a closer look

**Comment by OmarTawfik** [comment]
Thank you. To be clear, the include works well (if the file exists), but fails silently if it can't find it (regardless of whether `check_paths` is set or not). Please let me know if you need any more info.

**Comment by facelessuser** [comment]
I think I know exactly what the issue is. I'll try to get a fix in sometime this week.

**Comment by facelessuser** [comment]
It'll be available in the next release, when that occurs

**Comment by OmarTawfik** [comment]
@facelessuser thank you! Will wait for the new release then.

**Comment by OmarTawfik** [comment]
@facelessuser I see the last update was more than 5 weeks ago, and a few fixes have went in since. Is it possible to put a new patch release with these fixes?
Thanks!

**Comment by facelessuser** [comment]
I'm working to get the external URLs for Snippets working for the next release. The plan was to finish that up and make a release. The nested `check_paths` issue has been there for a while, so it's not a new regression or anything, so I wasn't rushing to get a release out.

I'm close to getting the external URL feature done, I really just need to get proper testing in and it should be good to go. Just  trying to fit it into my free time to get it out the door.

**Comment by OmarTawfik** [comment]
Thank you!
