### ISSUE TITLE
Allow overriding language guessing in InlineHilite

### ISSUE THREAD

**Issue by SuibianP** [facelessuser/pymdown-extensions#1696]
### Description

The language guessing in InlineHilite is controlled by `highlight.guess_lang`, and cannot be turned off as long as that option is true. The current `style_plain_text` option allows one to override `guess_lang` to true, but not the other way around.

### Benefits

It should be a legitimate use case where language guessing is desired for code blocks but not for inline code.

### Solution Idea

`style_plain_text` should be deprecated in favor of another option (perhaps also named `guess_lang`) which would exclusively control the language guessing behaviour for InlineHilite.

**Comment by SuibianP** [comment]
Thanks for the explanation. As such, is there any way to only guess language for code blocks, but not inline code?

**Comment by facelessuser** [comment]
Not currently

**Comment by SuibianP** [comment]
Would it be good to allow overriding any sensible options from `highlight` in `inlinehilite` as well, for the precise goal of different configurations for inline and block code?

**Comment by facelessuser** [comment]
TBH, very few options even apply to InlineHilite. Personally, I don't like and do not use `guess_lang`. Pygment's ability (and frankly most JS highlighters' ability) to guess a language is only "okay" at best. It really suffers if you are using plain text as it will often attribute a language when it should not. I guess in those cases it is better to specify `text` to ensure it is treated as text.

I imagine that InlineHilite has a more difficult time when language guessing is applied as you only have a single line to derive the language from and only a single line. Out of all the options, `guess_lang` is probably the only option that I could see a benefit of setting inline differently from block code handling. Again, I've never seen issues as I never turn on `guess_lang` myself.

It is possible we could always disable language guessing when using inline as it is probably not very helpful on average with inline, or augment the current option to allow specifying `True`, `False`, `"block"`, or `"inline"` ( I can't imagine `"inline"` specifically ever being used, but it would make sense to provide it for completeness).
