### ISSUE TITLE
syntax highlighting of .ini language doesn't parse comments present on same line

### ISSUE THREAD

**Issue by birdybro** [facelessuser/pymdown-extensions#1733]
### Description

My apologies if this is not the proper place to submit the issue, I'm not knowledgeable enough of the entire stack to be 100% sure where it belongs.

It appears that the Highlight extension isn't parsing for comments on same line with the .ini language. See examples

https://mister-devel.github.io/MkDocs_MiSTer/developer/test/#code-syntax-highlighting-for-ini-incorrect

![image](https://user-images.githubusercontent.com/16388068/173257139-26b1be12-c6da-426e-8aba-745bed025760.png)

Ini example 1 and ini example 2 show that it doesn't respect the comment starting unless it's on a new line. The expected result should be something like how it looks in VSCode:

![image](https://user-images.githubusercontent.com/16388068/173256159-f83d851c-cc17-441c-8536-26de948b829d.png)

I got the same results regardless of browser I viewed it in, regardless of using Pygments or not using Pygments, and didn't know what else to test to remedy it.

Thank you for your time.

### Minimal Reproduction

1. Make multiple code blocks with .ini language specified for syntax highlighting the same way as my examples.

### Version(s) & System Info

- Operating System: Windows 11 
- Python Version: 3.10.5
- Package Version: Whatever version Material for MkDocs is using currently.

**Comment by facelessuser** [comment]
Can you post a plain text example of the Markdown you are using? Something copy/pastable. I cannot tell what you are using as you are only showing the final render, and I cannot make any advise either. If I were to try and replicate, I'd have to manually type everything from an image, so plain text is preferrable.

Most likely, this is either a user error, or an issue with Pygments, but without more information, I cannot tell.

@gir-bot add S: more-info-needed

**Comment by facelessuser** [comment]
Okay, so I just followed things back to your repo, your syntax looks fine.

This is an upstream bug in Pygments: https://github.com/pygments/pygments.

@gir-bot add S: invalid
@gir-bot remove S: triage, S: more-info-needed

**Comment by facelessuser** [comment]
Closed for the reasons listed above.

**Comment by birdybro** [comment]
Thank you!
