### ISSUE TITLE
Snippets not working in mkDocs

### ISSUE THREAD

**Issue by hazam** [facelessuser/pymdown-extensions#1750]
### Description

The snippet extension seems to loaded in mkdocs, but seems to never get triggered.
mkdocs 1.3.0
with or without material

### Minimal Reproduction

```
requirements.txt
mkdocs==1.3.0
```

any --8<-- never triggers.
check_paths never triggers

I'm just clueless

### Version(s) & System Info

- Operating System: Windows WSL
- Python Version: 3.9
- Package Version: 9.5, 9.4

**Comment by facelessuser** [comment]
@hazam any updates providing a failing example for reproduction? I'll be giving this issue about a week more, and I'm afraid that if I hear no response, I'll have to close the issue.

**Comment by facelessuser** [comment]
I am closing this issue as there has been no correspondence; therefore, we cannot when begin to guess what the issue is.
