### ISSUE TITLE
Terraform markdown with `<<` will render code after it twice

### ISSUE THREAD

**Issue by michaelbrewer** [facelessuser/pymdown-extensions#1784]
### Description

The following markdown will render `x` out twice 

````
```terraform
<<a
x
```
````

### Minimal Reproduction

1. `pip install pymdown-extensions`

2. run the following example

````python3
import markdown

MD = """
```terraform
<<a
x
```
"""

print(markdown.markdown(MD,  extensions=['pymdownx.superfences']))
````

will output 

```html
<div class="highlight"><pre><span></span><code><span class="o">&lt;&lt;</span><span class="dl">a</span><span class="sh"></span>
<span class="err">x</span>
<span class="err">x</span><span class="w"></span>
</code></pre></div>
```

expected output

```html
<div class="highlight"><pre><span></span><code><span class="err">&lt;&lt;a</span><span class="w"></span>
<span class="err">x</span><span class="w"></span>
</code></pre></div>
```

### Version(s) & System Info

- Operating System: MacOs
- Python Version: Python 3.9.12
- Package Version: pymdown-extensions 9.5

**Comment by facelessuser** [comment]
This is an upstream [Pygments](https://github.com/pygments/pygments) bug:

<img width="814" alt="Screen Shot 2022-08-11 at 3 10 07 PM" src="https://user-images.githubusercontent.com/1055125/184242819-8cfa6701-1a7b-49ed-9c30-560315e18c94.png">

Sorry to keep bouncing you around. I guess, when I initially tried it out, I spelled terraform incorrectly, and so I couldn't reproduce, but I am able to reproduce. The issue is that it is in Pygments, which you can see with their online demo, they get the same bad results.

**Comment by facelessuser** [comment]
Had this truly been an issue in SuperFences, we probably would have caught it way before now as none of our code is "terraform" specific.  I've never seen a syntax highlighter-specific issue like this before, so it hadn't even occurred to me that it was a Pygments bug until I was able to reproduce it.

**Comment by michaelbrewer** [comment]
Sorry it looks like the actual issue is valid terraform is about how the terminating `EOF` is handled (or maybe trimmed?).

Here is a simple example (not the space before the terminating ` EOF`:

`````python
import markdown

MD = """
```terraform
<<EOF
{}
 EOF
```
"""

print(markdown.markdown(MD,  extensions=['pymdownx.superfences']))
`````

Which outputs 

```html
<div class="highlight"><pre><span></span><code><span class="o">&lt;&lt;</span><span class="dl">EOF</span><span class="sh"></span>
<span class="err">{}</span>
<span class="err"> EOF</span>
<span class="p">{}</span><span class="w"></span>
<span class="w"> </span><span class="err">EOF</span><span class="w"></span>
</code></pre></div>
```

Where as pygments outputs correctly see [here](https://pygments.org/demo/?lexer=terraform&style=default&formatter=html&code=%3C%3CEOF%0A%7B%7D%0A+EOF%0A):

<img width="821" alt="Screen Shot 2022-08-11 at 3 12 44 PM" src="https://user-images.githubusercontent.com/5442469/184251427-35ce2ff4-aac5-4807-8b6d-2a0e8b09c1af.png">


```html
<div class="demo-highlight"><pre><span></span><span class="o">&lt;&lt;</span><span class="dl">EOF</span><span class="sh"></span>
<span class="sh">{}</span>
<span class="dl"> EOF</span>
</pre></div>
````


This is the full example

````
```terraform
terraform {
    required_version = "~> 1.0.5"
    required_providers {
       aws = "~> 3.50.0"
    }
}

provider "aws" {
    region  = "us-east-2"
}

resource "aws_iam_role" "iam_for_lambda" {
    name = "iam_for_lambda"
    assume_role_policy = <<EOF
    {
        "Version": "2012-10-17",
        "Statement": [{
            "Action": "sts:AssumeRole",
            "Principal": {
            "Service": "lambda.amazonaws.com"
            },
            "Effect": "Allow"
        }]
    }
    EOF
}

resource "aws_lambda_function" "test_lambda" {
    filename         = "lambda_function_payload.zip"
    function_name    = "lambda_function_name"
    role             = aws_iam_role.iam_for_lambda.arn
    handler          = "index.test"
    runtime          = "python3.9"
    layers           = ["arn:aws:lambda:us-east-1:017000801446:layer:AWSLambdaPowertoolsPython:29"]
    source_code_hash = filebase64sha256("lambda_function_payload.zip")
}
````

**Comment by facelessuser** [comment]
I don't understand. I'm not sure what the demo is showing, but I have the latest Pygments installed locally, and when I place this in eof.txt (with space in front of EOF).

```txt
<<EOF
{}
 EOF
```

I get this:

```console
➜  pymdown-extensions git:(main) ✗ pygmentize -l terraform eof.txt
<<EOF
{}
 EOF
{}
 EOF
```

This seems to have nothing to do with SuperFences as it is completely removed from the equation.

**Comment by facelessuser** [comment]
One thing I am certain of though, Pygments should not duplicate lines under any circumstance. There is clearly a bug in their code, even if somehow we are triggering it. But based on my experiments, not even using anything but Pygments itself, it appears `terraform` highlighting is busted.

**Comment by michaelbrewer** [comment]
FYI. I have logged it with pygments to fix: https://github.com/pygments/pygments/issues/2205
