### ISSUE TITLE
Alphanumeric Keys in The Keys extension 

### ISSUE THREAD

**Issue by shawnlxf** [facelessuser/pymdown-extensions#1806]
### Description

I hope that Alphanumeric Keys in the Keys extension can be case sensitive.

### Benefits

It's necessary for keyboard shortcuts.

**Comment by shawnlxf** [comment]
shift +  Alphanumeric Keys is a better choice.

**Comment by facelessuser** [comment]
Yes, modifiers like `shift` should be the approach to specify an uppercase key vs a lowercase key.
