### ISSUE TITLE
PyMdown Snippets extension not working

### ISSUE THREAD

**Issue by atipico** [facelessuser/pymdown-extensions#184]
I have I markdown file named "file.md" with the following content:

	#hello world

Than I am trying to run the code:

	echo '--8<-- "file.md"' | /usr/bin/python3 -m markdown -q -o html5 --noisy -x pymdownx.snippets

Resulting in this:

	rgr@atpc: echo '--8<--"file.md"' | /usr/bin/python3 -m  markdown -q -o html5 --noisy -x pymdownx.snippets
	Successfuly imported extension module "pymdownx.snippets".
	Successfully loaded extension "pymdownx.snippets.SnippetExtension".
	<p>--8&lt;--"file.md"</p>rgr@atpc: 

When it should echo:

	<h1>hello world</h1>

The project page is at https://facelessuser.github.io/pymdown-extensions/extensions/snippets/

I also tried the syntax:

	--8<-- 
	filename.md
	filename2.md
	--8<-- 

But with similar results.

By the way:

	pip3 --version
	pip 9.0.1 from /usr/local/lib/python3.4/dist-packages (python 3.4)
	pip --version
	pip 9.0.1 from /usr/local/lib/python3.4/dist-packages (python 3.4)

	/usr/bin/python3 -m pip list 
	DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
	beautifulsoup4 (4.6.0)
	certifi (2017.11.5)
	chardet (3.0.4)
	Cython (0.27.3)
	ez-setup (0.9)
	guess-language-spirit (0.5.3)
	idna (2.6)
	Markdown (2.6.9)
	markdown-extra (0.3.0)
	markdown-include (0.5.1)
	MarkdownHighlight (0.1.3)
	mdx-customspanclass (1.1.1)
	mdx-smartypants (1.5.1)
	namedentities (1.5.2)
	numpy (1.13.3)
	pip (9.0.1)
	pyembed (1.3.3)
	pyembed-markdown (1.1.0)
	pymdown-extensions (4.6)
	pystan (2.17.0.0)
	PyYAML (3.12)
	requests (2.18.4)
	setuptools (38.2.4)
	urllib3 (1.22)
	wheel (0.29.0)
	youtube-dl (2017.12.2)

	/usr/bin/python3 -m pip show pymdown-extensions
	Name: pymdown-extensions
	Version: 4.6
	Summary: Extension pack for Python Markdown.
	Home-page: https://github.com/facelessuser/pymdown-extensions
	Author: Isaac Muse
	Author-email: Isaac.Muse@gmail.com
	License: MIT License
	Location: /home/rgr/.local/lib/python3.4/site-packages
	Requires: Markdown

	/usr/bin/python3 --version
	Python 3.4.3

	lsb_release -a
	No LSB modules are available.
	Distributor ID:	Ubuntu
	Description:	Ubuntu 14.04.5 LTS
	Release:	14.04
	Codename:	trusty

Any light?

**Comment by facelessuser** [comment]
I am currently on a windows machine using the latest release. I assume you are on a Linux or machine (maybe macOS, but I'm going to guess Linux).  I'm not near my 'nix machines,  so  I created a file `file.md` with the following content:

```
#hello world
```

When I run the command, from the folder where the snippet is, I get what is expected:

<img width="731" alt="snippets" src="https://user-images.githubusercontent.com/1055125/33674549-28d40f4a-da6d-11e7-9a87-2aa5b2f9a2f2.png">

So, I'd need more information on your specific scenario.

1. Where is the snippet in relation to the current working directory from which the command is executed?

2.  What version of pymdown-extensions are you using?

**Comment by atipico** [comment]
I tried to run the file in some different ways. At the same directory, in a subdirectory, with and without ".md" extension...

	/usr/bin/python3 -m pip show pymdown-extensions
	Name: pymdown-extensions
	Version: 4.6
	Summary: Extension pack for Python Markdown.
	Home-page: https://github.com/facelessuser/pymdown-extensions
	Author: Isaac Muse
	Author-email: Isaac.Muse@gmail.com
	License: MIT License
	Location: /home/rgr/.local/lib/python3.4/site-packages
	Requires: Markdown


	/usr/bin/python3 --version
	Python 3.4.3


	lsb_release -a
	No LSB modules are available.
	Distributor ID:	Ubuntu
	Description:	Ubuntu 14.04.5 LTS
	Release:	14.04
	Codename:	trusty

**Comment by atipico** [comment]
I updated my question with the result of the command-line:

	rgr@atpc: echo '--8<--"file.md"' | /usr/bin/python3 -m  markdown -q -o html5 --noisy -x pymdownx.snippets
	Successfuly imported extension module "pymdownx.snippets".
	Successfully loaded extension "pymdownx.snippets.SnippetExtension".
	<p>--8&lt;--"file.md"</p>rgr@atpc:

**Comment by atipico** [comment]
Worked at the same directory:

	rgr@atpc: ls
	agenda.md  file.md  home  in  teste
	rgr@atpc: cat file.md 
	#hello world
	rgr@atpc: echo '--8<-- "file.md"' | /usr/bin/python3 -m  markdown -q -o html5 --noisy -x pymdownx.snippets
	Successfuly imported extension module "pymdownx.snippets".
	Successfully loaded extension "pymdownx.snippets.SnippetExtension".
	<h1>hello world</h1>rgr@atpc:

**Comment by facelessuser** [comment]
Okay, I see your issue now.  What you posted in the opening is not the same as what you you posted earlier. This `echo '--8<--"file.md"'` does not equal this `echo '--8<-- "file.md"'`.  Notice the space after `--8<--`  You need a space between the `--8<--` and `"file.md"`.

**Comment by facelessuser** [comment]
I just tried this out on Ubuntu 15.04, and it works fine for me.

**Comment by facelessuser** [comment]
If `file.md` is not in the cwd, then you need to give a `base_path` that snippet paths are relative to: https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#options.

**Comment by atipico** [comment]
Thank you very much.

**Comment by facelessuser** [comment]
Does that mean it's working now?

**Comment by atipico** [comment]
Sure thing. It was my fault all the time.

**Comment by facelessuser** [comment]
No problem. Been there :).
