### ISSUE TITLE
Support .order file

### ISSUE THREAD

**Issue by rafalschmidt97** [facelessuser/pymdown-extensions#1893]
### Description

Hi, do you have any plans to add or have seen an extension which adds support for `.order` file?

I would love to move from azure wiki pages to mkdocs but don't want to manually create `nav:` section.
https://learn.microsoft.com/en-us/azure/devops/project/wiki/wiki-file-structure?view=azure-devops#order-file

### Benefits

The .order file defines the sequence of pages within the wiki. The following visual shows an example of a wiki TOC and it's corresponding .order file.
The default hierarchy is in alphabetical sequence, however you can change this hierarchy in the .order file. For more information about how to reorder wiki pages, see [Add and edit wiki pages, Reorder a wiki page](https://learn.microsoft.com/en-us/azure/devops/project/wiki/add-edit-wiki?view=azure-devops#reorder-a-wiki-page).

**Comment by facelessuser** [comment]
This request makes absolutely no sense for a collection of plugins for a Markdown parser. We don't deal in plugins for a documentation site, but for a Markdown parser.

Also, please don't spam requests to multiple repos. I see you made one request to the logical place, MkDocs, but shotgun requested there and here for some reason.

- https://github.com/mkdocs/mkdocs/issues/3080
