### ISSUE TITLE
Import Snippet Section from XML file

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/pymdown-extensions#1916]
### Discussed in https://github.com/facelessuser/pymdown-extensions/discussions/1914

<div type='discussions-op-text'>

<sup>Originally posted by **maciejwalkowiak** January 19, 2023</sup>
I want to use Snippet Sections in an XML file:

```xml
<dependencies>
    <!-- --8<-- [start:func] -->
    <dependency>
        <groupId>software.amazon.awssdk</groupId>
        <artifactId>dynamodb-enhanced</artifactId>
    </dependency>
    <!-- --8<-- [end:func] -->
</dependencies>
```

`--8<--` within an XML comment makes the XML invalid which as a result breaks the XML tooling. The error is following:

```
in comment after two dashes (--) next character must be > not 8 (position: START_TAG seen ...<dependencies>\n        <!-- --8... @21:17) 
```

Is there a way to use different "tag" than `--8<--` or any other way to make snippet sections work with XML files?</div>

**Comment by facelessuser** [comment]
@maciejwalkowiak I should have a bugfix release how reasonably soon.

**Comment by maciejwalkowiak** [comment]
Fantastic thanks a lot @facelessuser!

**Comment by facelessuser** [comment]
The release has been tagged, so it should be available in PyPI shortly.
