### ISSUE TITLE
Docs: Add a list of available styles presets for _details_ element

### ISSUE THREAD

**Issue by reregaga** [facelessuser/pymdown-extensions#1923]
### Description

Add a list of available styles presets for [details](https://facelessuser.github.io/pymdown-extensions/extensions/details/) element. 
 
Right now I only know about `success`, `warning`, `danger`, `note` styles, maybe there are more? Where can I see the entire list?

### Benefits

Significantly.

**Comment by facelessuser** [comment]
There is an available list of styles for details. There isn't technically an available list of styles for Admonitions either, just recommended names.

The way details, and admonitions work in their respective plugins is that whatever "style" name you give it, gets set as a class. It is the CSS you use that is responsible for determining which details/admonitions get styled based on their class.

**Comment by reregaga** [comment]
Thanks for the clarification, but it would be nice to have a list of **default classes** that are present in a **clean installation**. Now I found another style - `tip` - by experiment, so that new users avoid this **testing a bunch of words**, it would be useful to have a list of styles that are **already** available.
>![test](https://user-images.githubusercontent.com/76629445/214864943-a58e6dc7-b93a-4da5-bbd8-45db3c277a84.png)

**Comment by facelessuser** [comment]
Again, you are linking those styles to your specific documentation theme, other themes may use different styles. What styles would I put that are universal? This plugin doesn't provide styles.
