### ISSUE TITLE
Highlight causes extra new lines to be inserted before `</code>` in rendered indented code blocks

### ISSUE THREAD

**Issue by wangtz0607** [facelessuser/pymdown-extensions#1928]
### Description

Consider the following Markdown text (an indented code block followed by 2 empty lines):

```markdown
    int a;


```

When Highlight is enabled, it is wrongly rendered as

```html
<pre class="highlight"><code>int a;




</code></pre>
```

instead of

```html
<pre class="highlight"><code>int a;
</code></pre>
```

### Minimal Reproduction

```python
import markdown

text = '    int a;\n\n'

print(repr(markdown.markdown(text)))
print(repr(markdown.markdown(text,
                             extensions=['pymdownx.highlight'],
                             extension_configs={'pymdownx.highlight': {'use_pygments': False}})))
```

## Actual Behavior

```
'<pre><code>int a;\n</code></pre>'
'<pre class="highlight"><code>int a;\n\n\n\n\n</code></pre>'
```

## Expected Behaviod

```
'<pre><code>int a;\n</code></pre>'
'<pre class="highlight"><code>int a;\n</code></pre>'
```

### Version(s) & System Info

- Operating System: Ubuntu 20.04 (64-bit)
- Python Version: `python==3.9`
- Package Version: `Markdown==3.4.1 pymdown-extensions==9.9.2`

**Comment by facelessuser** [comment]
Yes, this does appear to be a bug, though a minor, and easy to fix one.

@gir-bot add S: confirmed
