### ISSUE TITLE
[Wish] Fenced divs like Pandoc, Remark, Markdown-it

### ISSUE THREAD

**Issue by twardoch** [facelessuser/pymdown-extensions#1930]
### Pandoc 

Extension: fenced_divs

Allow special fenced syntax for native Div blocks. A Div starts with a fence containing at least three consecutive colons plus some attributes. The attributes may optionally be followed by another string of consecutive colons. The attribute syntax is exactly as in fenced code blocks (see Extension: fenced_code_attributes). As with fenced code blocks, one can use either attributes in curly braces or a single unbraced word, which will be treated as a class name. The Div ends with another line containing a string of at least three consecutive colons. The fenced Div should be separated by blank lines from preceding and following blocks.

Example:

```
::::: {#special .sidebar}
Here is a paragraph.

And another.
:::::
```

Fenced divs can be nested. Opening fences are distinguished because they must have attributes:

```
::: Warning ::::::
This is a warning.

::: Danger
This is a warning within a warning.
:::
::::::::::::::::::
```

Fences without attributes are always closing fences. Unlike with fenced code blocks, the number of colons in the closing fence need not match the number in the opening fence. However, it can be helpful for visual clarity to use fences of different lengths to distinguish nested divs from their parents.

### Remark

https://github.com/remarkjs/remark-directive

### Markdown-it

https://github.com/arothuis/markdown-it-fenced-divs

### Other

https://github.com/stefanfritsch/goldmark-fences

### Benefits

- Compatibility with other popular MD renderer extensions
- General syntax that allows pretty specification of divs

**Comment by facelessuser** [comment]
See discussion https://github.com/facelessuser/pymdown-extensions/discussions/1883

**Comment by facelessuser** [comment]
All of these are implemented differently and are not compatible, just similar.

**Comment by facelessuser** [comment]
We are working on a generic block, but it cannot match all of these slightly differently implemented ways, so we are attending attempting one that distances itself somewhat away from these. If thing ever become more standard, I'm sure we could reconsider. With that said, we are looking for feedback with our current work.

**Comment by facelessuser** [comment]
I'm going to close this as a duplicate for the work in https://github.com/facelessuser/pymdown-extensions/pull/1777.

We will not be implementing the feature as described here because it is quite a bit more limited. I do not plan to have multiple implementations that do the same thing but instead will have a general-purpose block approach. Currently, we've chosen to use `///` opposed to `:::` specifically to avoid people thinking they are a clone of one of the many various approaches that use `:::` (many of which do different things and are implemented slightly different).
