### ISSUE TITLE
[Wish] Bracketed spans like Pandoc, Remark, Markdown-it

### ISSUE THREAD

**Issue by twardoch** [facelessuser/pymdown-extensions#1931]
### Pandoc 

Extension: bracketed_spans

A bracketed sequence of inlines, as one would use to begin a link, will be treated as a Span with attributes if it is followed immediately by attributes:

```
[This is *some text*]{.class key="val"}
```

### Markdown-it

https://github.com/mb21/markdown-it-bracketed-spans

### Remark

https://github.com/sethvincent/remark-bracketed-spans

### Benefits

- Compatibility with other popular MD renderer extensions
- General syntax that allows pretty specification of spans

**Comment by facelessuser** [comment]
See discussion of alpha https://github.com/facelessuser/pymdown-extensions/discussions/1883

**Comment by facelessuser** [comment]
Wrong issue

**Comment by facelessuser** [comment]
This is a possibility, though it would specifically be tied to the `attr_list` extension.

**Comment by facelessuser** [comment]
This can technically already be done with a custom inline block https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/#custom-inline-blocks. 

If someone created a special span inline-block, you could do this.

```
`#!span some content here`{.class}
```

One of the reasons I added custom inline blocks was to allow people to do whatever they want, just like with custom fenced blocks.

I think the main idea behind this is interoperability with specific implementations. As we do already have a solution, it makes this maybe a bit less likely, but I'll leave it as a possibility. I'm personally less concerned with interoperability, but arbitrary span creation is something that I think would get used fairly frequently, so maybe a dedicated approach is not a bad idea.

**Comment by facelessuser** [comment]
The requested syntax would have a direct conflict with references paired with `attr_list`.

```
[test]{.class}

[test]: https://www.google.com/
```

I would suggest something like the custom inline block. Yes, it does not have the interoperability that is being requested, but I don't know what to say about that. I'm not willing to compromise basic working syntax of Python Markdown for such a feature.

For those who'd like to utilize the custom inline blocks:

```python
import xml.etree.ElementTree as etree


def inline_span(source, language, css_class, md):
    """Create a span."""

    el = etree.Element('span')
    el.text = source
    return el
```

And then set it up. In Mkdocs, it'd look like below. We are just going to use something short, so we'll use the name `#`:

```yaml
  - pymdownx.inlinehilite:
      custom_inline:
        - name: '#'
          class: '#'
          format: !!python/name:tools.inline_span.inline_span
```

Then you can just do the following:

```
`#!# This *is* a _span_`{style="background-color: red; color: white;"}
```

<img width="137" alt="Screenshot 2023-02-22 at 8 52 59 PM" src="https://user-images.githubusercontent.com/1055125/220817836-930f5ee2-18c6-4b70-abdf-8e9128a3990c.png">
