### ISSUE TITLE
Unindent for snippets

### ISSUE THREAD

**Issue by Vampire** [facelessuser/pymdown-extensions#1945]
### Description

It would be nice if snippets would be unindented, so that the leading whitespace that is common to all lines in the snippet is removed, so it starts left-most with the first character.
This should imho even be the default behavior if it will be configurable.

### Benefits

No need to cram the snippet code to beginning of line in the source file to have it nice in the docs.

### Solution Idea

Just get the leading whitespace of all lines, take the shortest one and remove that from all lines.
If someone has mixed space and tab indents, it is his own fault. :-D

**Comment by facelessuser** [comment]
Related to this discussion: https://github.com/facelessuser/pymdown-extensions/discussions/1913

If we do this, it would likely only be done when injection "sections" or I guess also when specific line numbers are specified. A full file should already be dedented, and if not, that's on the user. This does run into an issue if you are injecting an indented code block, it would get dedented...but I guess if you indent the snippet syntax, then maybe it'll all work out. I'd have to verify.

This is of course if we just go the simple route and dedent all snippet partials automatically. If we have some syntax (and I don't know what that would even look like) that is meant to signify a dedent should occur, then the user would have complete control of when this does or does not happen.

The actual dedenting should be pretty easy as there are already built-in tools in Python to do so.

Anyways, stuff to think about.

**Comment by Vampire** [comment]
> A full file should already be dedented, and if not, that's on the user.

👍 

> This does run into an issue if you are injecting an indented code block, it would get dedented...but I guess if you indent the snippet syntax, then maybe it'll all work out. I'd have to verify.

Yeah, actually having a way to intentionally indent would probably be nice if you combine different snippets or a snippet with accompanying lines.
Maybe either by indenting the scissors, or by being able to specify how far to indent as number.

**Comment by facelessuser** [comment]
Yeah, snippets can be nested too, so it is something to think about. The idea behind snippets was to just very dumbly insert a file. Feature creep is making it a bit more complicated these days, not that it's a bad thing per se.  I'd need to find a way to extend the syntax in a reasonable way if we want an explicit approach.

**Comment by Vampire** [comment]
Actually I just tried, adding indent is possible by indenting the scissors

**Comment by facelessuser** [comment]
Yeah, that is what I figured. We try to respect the indentation of insertion.

**Comment by facelessuser** [comment]
For now, we are going to add an option that always dedents sectional inserts. Assuming that resolves the problem generally well, we might make it the default in the future. We'll see if that is sufficient or if there is a need for manual dedenting.

**Comment by Vampire** [comment]
I tested the dedent, works perfectly fine here, thanks.
Do you have any idea when 9.10 will be final? :-)

**Comment by facelessuser** [comment]
I have it in beta mainly for the new [general-purpose blocks](https://github.com/facelessuser/pymdown-extensions/discussions/1961). I'm thinking everything is pretty much cemented there, but I'm getting some active feedback, so just making sure there are no more minor tweaks before I pull the trigger.

I'd say soon-ish? I have no plans for any additional features in 9.10. I'm hoping maybe a week or two, but we'll see.

**Comment by Vampire** [comment]
Great, thanks :-)
