### ISSUE TITLE
Fail on missing snippet sections

### ISSUE THREAD

**Issue by Vampire** [facelessuser/pymdown-extensions#1946]
### Description

To prevent typos or accidental section deletions, missing snippet sections should be complained about, either always, or configurable, or together with complaining about missing files option.

### Benefits

Prevent typos, accidential deletions, ...

**Comment by facelessuser** [comment]
We can just attach this check to `check_paths`. It validates whether a snippet can be found. The new "sections" feature should probably fit within this check.
