### ISSUE TITLE
Snippet IDs with dashes and underscores

### ISSUE THREAD

**Issue by Vampire** [facelessuser/pymdown-extensions#1947]
### Description

I tried to use snippet IDs with dashes and / or underscores.
Unfortunately it lead to the whole snippet file not being found (build failing with `SnippetMissingError`).
So it seems currently only camelCase IDs are supported, but neither kebab-case nor snake_case.
Would be nice to add some more flexibility here.

### Benefits

For such IDs I usually prefer kebab-cased IDs for readability.

**Comment by facelessuser** [comment]
I don't think there is any technical limitation in the syntax preventing us from doing this. I will consider adding `-` and `_` as allowable characters.
