### ISSUE TITLE
snippets is incompatible with any mdocs-monorepo-plugin and similar plugins

### ISSUE THREAD

**Issue by ssbarnea** [facelessuser/pymdown-extensions#1986]
### Description

MkDocs has about 3-4 extensions that provide support for combining multiple mkdocs based projects into a single documentation side, with [the most popular](https://github.com/pawamoy/best-of-mkdocs#-site-management) being https://github.com/backstage/mkdocs-monorepo-plugin

## Why this happens with these plugins?

When trying to combine multiple mkdocs sites into a single unified one you endup with a different location of `mkdocs.yml` relative to other files. This means that the inclusion no longer works as the path will always be different.

Sadly this might prove to be quite big problem as AFAIK, mkdocs does not have a concept of "current-file", so making a plugin include a file relative to current markdown file being processed might not really be possible.

I was also wondering if `docs_dir` settings might be used for building a relative path, but that is also problematic because I doubt that when a multi-site plugin runs, it would alter the value of docs_dir for each sub-site build build.

I am sorry that I do not have a clear solution for this issue as it seems to sit somewhere between mkdocs core, inclusion plugin (like snippet) and the multi-site ones, where everyone thinks that it would be for the other sides to find a workaround.

I tried to avoid using inclusions in my documentation but that make very hard when you need to include code samples.

### Minimal Reproduction

N/A yet but I will attempt to build a minimal repo for it.

### Version(s) & System Info

N/A (all)

Related: https://github.com/backstage/mkdocs-monorepo-plugin/issues/92

**Comment by facelessuser** [comment]
Snippets is not a MkDocs plugin, and I don't use the monorepo plugin either. So I have absolutely no insight into your issue.

As this is on the bottom of the stack, I don't see why this repo would get pinned as the responsible party. We have no knowledge of anything regarding MkDocs at our level. MkDocs uses Python Markdown, which Snippets is an extension of, not the other way around.

It may be that you need a MkDocs level snippet extension, or better put, a snippets extension for MkDocs. One that is aware of MkDocs and has the context from MkDocs and can make document-level decisions as opposed to decisions based on the current Markdown buffer, which is all Snippets has the context for.

If you wanted to use Snippets, it seems that what you need is a `mkdocs.yml` that points to the correct snippets base folder for each multi-site repo. That should be managed by whatever plugin controls multiple repos in MkDocs. If they only use one `mkdocs.yml` and deem it not their problem, well, that is the design limitations they've chosen. You will have to find another way, probably a plugin designed for MkDocs that inserts snippets and can get the current document directory context that is necessary.

**Comment by facelessuser** [comment]
I am open to proposals from someone who understands the problem. If a generic way, not specific to MkDocs, could be provided to better facilitate such scenarios, I'm willing to hear it.

**Comment by facelessuser** [comment]
I've received no additional comments for 3 weeks. I'm going to close the issue has the discussion has gone stale.

**Comment by frankkusters** [comment]
This was fixed in mkdocs 1.6. From https://www.mkdocs.org/user-guide/configuration/#paths-relative-to-the-current-file-or-site :

> Example:
>
> ```yaml
> markdown_extensions:
>   - pymdownx.snippets:
>       base_path: !relative  # Relative to the current Markdown file
> ```
>
> This allows the [pymdownx.snippets](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/) extension to include files relative to the current Markdown file, which without this tag it would have no way of knowing.
