### ISSUE TITLE
pymdown-extensions 10.0 seems to break subdirectory imports

### ISSUE THREAD

**Issue by xmatthias** [facelessuser/pymdown-extensions#2038]
### Description

I've got the following file structure (for clarity, really - to keep imported files clearly separated)

```
docs/                                                                                                                                       
├── parent-file.md                                                                                                                 
├── includes
│   ├── includeA.md
│   ├── includeB.md
└── index.md

```

with the following configuration:

```
- pymdownx.snippets:
      base_path: docs
      check_paths: true
```

This config used to work fine until the update of 10.0 - which i understand will restrict imports to relative paths.

```
...
    base_path: docs
```

in the file `parent.md` - 
```
--8<-- "includes/includeA.md"
...
--8<-- "includes/includeB.md"

```

My path is relative to the parent directory, and contained in the parent directory (which shouldn't be a vulnerability).(everything is within the `./docs/` directory) - yet imports fail.

I've tried several possibilities for base_path (`./docs`, `./docs/`,  `docs/`) - but the only possibility that seems to work is to drop the sub-directory component and change the imports 

```
...
    base_path: docs/includes
```

```
--8<-- "includeA.md"
...
--8<-- "includeB.md"

```

Now i would prefer to keep the original structure for clarity, and to avoid problems when other files are imported (imports are with `imports/includeA.md`) but i'd also not want to enable legacy mode, as in my understanding, that will reenable the vulnerability.

### Version(s) & System Info

- Operating System: linux
- Python Version: 3.10
- Package Version: 10.0

**Comment by xmatthias** [comment]
From looking at the diff, it seems that `if not os.path.samefile(base, os.path.dirname(filename)):` is too restrictive, and ignores the comment prior to that `# If the absolute path is no longer under the specified base path, reject the file`).

if base is 'docs' - `'docs/includes/file.md'` should be valid - but based on the above isn't, as 'docs' and 'docs/includes' are not the same filename - yet they are nested within each other - which the comment says would be allowed.

Also the release mentions that:
> Snippets: snippets will restrict snippets to ensure they are under the `base_path` preventing snippets
relative to the `base_path` but not explicitly under it. `restrict_base_path` can be set to `False` for legacy
behavior.

`docs/includes/file.md` is "under" `docs/` - so i think this is unintended behavior.

**Comment by facelessuser** [comment]
Yeah, we didn't have tests, so all of our tests were passing, but we clearly broke this. I'll try to get a fix out soon-ish, hopefully tomorrow.

**Comment by facelessuser** [comment]
Since we are using the same base path to resolve the joined path, this should be all we need:

```py
                    if self.restrict_base_path:
                        filename = os.path.abspath(os.path.join(base, path))
                        # If the absolute path is no longer under the specified base path, reject the file
                        if not filename.startswith(base):
                            continue
```

If we had a test in place for this scenario, it would not have slipped through. I'll add a suitable test to replicate this scenario.

**Comment by facelessuser** [comment]
I had a little time. I'll go ahead and cut a release.

**Comment by xmatthias** [comment]
Oh wow, that was quick! 👍 💯

**Comment by koen-yesplan** [comment]
I _think_ I have the same problem using Material for MkDocs. Is this fix picked up automatically by MfM?

**Comment by facelessuser** [comment]
What is MfM?

**Comment by koen-yesplan** [comment]
Sorry for not being clear: Material for MkDocs

**Comment by facelessuser** [comment]
Oh, wait, "mkdocs for Material" 🤦🏻. Hadn't seen that acronym before.

You may need to `pip install -U pymdown-extensions` locally. The CI should grab the latest, so you should be okay there.

**Comment by facelessuser** [comment]
If you are asking about their docker environment solution...the real answer is I don't know. I use Material, but I don't use any docker provided setup for Material, just GitHub CI directly.

**Comment by xmatthias** [comment]
Assuming they use dependabot (as i do) - then it may depend on their schedule (maybe it's only updating once a week) until the update is pushed.

oddly, i've also had trouble to have dependabot pick the release up - but it was 1h after the release, so it might be too fast - or dependabot has problems with the additional version component (10.0 -> 10.0.1) - but i've never seen / tested this personally
