### ISSUE TITLE
Default GH emoji options slightly wrong

### ISSUE THREAD

**Issue by aes256lamp** [facelessuser/pymdown-extensions#2052]
### Description

Under the [options section](https://facelessuser.github.io/pymdown-extensions/extensions/emoji/#options) on the page for the emojis there is code for configuring the plugin to appear like "the legacy GitHubEmoji extension." I used these settings but ran into two problems which I was able to fix.

1. couldn't import `pymdownx.emoji.gemoji` or `pymdownx.emoji.to_png` in the config options
2. GitHub flavoured emoji images were broken

My solutions:
### 1
`import pymdownx.emoji as pymdownx_emoji` then use `pymdownx_emoji.gemoji` (and same for `to_png`)

### 2 
In the config update `image_path` and `non_standard_image_path` to both use https://github.githubassets.com instead of https://assets-cdn.github.com

Putting that all together:
```python
from pymdownx import emoji as pymdownx_emoji

'pymdownx.emoji': {
                "emoji_index": pymdownx_emoji.gemoji,
                "emoji_generator": pymdownx_emoji.to_png,
                "alt": "short",
                "options": {
                    "attributes": {
                        "align": "absmiddle",
                        "height": "20px",
                        "width": "20px"
                    },
                    'image_path': 'https://github.githubassets.com/images/icons/emoji/unicode/',
                    'non_standard_image_path': 'https://github.githubassets.com/images/icons/emoji/',
                }
```

### Minimal Reproduction

n/a

### Version(s) & System Info

- Operating System: macOS Big Sur 11.6.1
- Python Version: 3.8
- Package Version: pymdown-extensions-10.0.1

**Comment by facelessuser** [comment]
> 1. couldn't import `pymdownx.emoji.gemoji` or `pymdownx.emoji.to_png` in the config options

It works for me:

```py
>>> import pymdownx.emoji
>>> pymdownx.emoji.gemoji
<function gemoji at 0x1106af9c0>
```

> In the config update `image_path` and `non_standard_image_path` to both use https://github.githubassets.com instead of https://assets-cdn.github.com

Yes, this is outdated, internally, we use:

```py
GITHUB_UNICODE_CDN = 'https://github.githubassets.com/images/icons/emoji/unicode/'
GITHUB_CDN = 'https://github.githubassets.com/images/icons/emoji/'

...

    if index == 'gemoji':
        def_image_path = GITHUB_UNICODE_CDN
        def_non_std_image_path = GITHUB_CDN
```
