### ISSUE TITLE
Slugs that combine headers with anchors

### ISSUE THREAD

**Issue by chipsenkbeil** [facelessuser/pymdown-extensions#2098]
### Problem

When using Mkdocs Material, it generates slugs for links being clicked based on the text of the link. In particular, I'm using a feature called [Content Tab Anchor Links](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#anchor-links), where tabs are rendered on a page, and clicking a tab will update the URL based on the tab's text.

<img width="830" alt="image" src="https://github.com/facelessuser/pymdown-extensions/assets/2481802/5e3b4b9c-af3d-486a-83e6-4a8aec460545">

When clicking on the tabs from content tabs that have the same names, I get links like these:

- example.com/#about
- example.com/#value
- example.com/#about_1
- example.com/#value_1

What I'd really like is to have the headers factor into the slug:

- example.com/#log_file-about
- example.com/#log_file-value
- example.com/#log_level-about
- example.com/#log_level-value

I opened a [discussion over at Mkdocs Material](https://github.com/squidfunk/mkdocs-material/discussions/5675), and it was mentioned to see if this was possible or something that could be pursued over here.

Is there any way to achieve this today? I was trying to figure out if I could write my own python function, but I couldn't easily determine that nor could I determine if there was a way to get the header(s) preceding a content tab.

### Benefits

Allows having even more readable slugs by using contextual positioning to fully represent where you are in a page. I've seen this done with HTML output from tools like vimwiki where they keep track of the depth that elements are in within a page, and combine all of the nested headers into part of the anchor.

### Solution Idea

I'm unaware of how Python markdown parsing works in terms of a solid structure. If it forms any kind of tree or association between headers and other content, then it would be trivial to reverse up the stack to see what each header's text was and combine that.

vimiwki handles it by scanning a document from top to bottom and maintaining a stateful track of the current headers as a stack, pushing onto the stack when we see a smaller header, and popping off the stack when we encounter a larger header. When a link is encountered, the current header tracking is used as a prefix to the anchor itself.

```markdown
# One

## Two

some anchor text

## Three

### Four

some anchor text
```

Yields links `example.com/#one-two-some-anchor-text` and `example.com/#one-three-four-some-anchor-text`.

**Comment by facelessuser** [comment]
I won't say this is impossible, but it would definitely require some more complex logic. For now, I'll mark it as a maybe and we'll see as I have time.

@gir-bot remove S: triage
@gir-bot add P: maybe

**Comment by facelessuser** [comment]
I was prototyping this, and it seems like it will be possible. I think I can have a solution for the next version. It will likely be tied to a feature switch, so you'd have to enable it.

@gir-bot remove P: maybe

**Comment by facelessuser** [comment]
I've added support, but it works like this:

If you have a content tab under multiple headers, the header that is used is the closest. We do not stack multiple headers.

```
# One

## Two

some anchor text
```

So we would give `two-some-anchor-text` _not_ `one-two-some-anchor-text`. I do not see how prefixing every level of header to anchored text would be helpful, but I'm okay with prefixing the relevant parent header.

**Comment by chipsenkbeil** [comment]
> I've added support, but it works like this:
> 
> If you have a content tab under multiple headers, the header that is used is the closest. We do not stack multiple headers.
> 
> ```
> # One
> 
> ## Two
> 
> some anchor text
> ```
> 
> So we would give `two-some-anchor-text` _not_ `one-two-some-anchor-text`. I do not see how prefixing every level of header to anchored text would be helpful, but I'm okay with prefixing the relevant parent header.

This is great! I'd say for 95% of the time, this is all that is needed. Thanks for working on this!
