### ISSUE TITLE
b64 extension

### ISSUE THREAD

**Issue by pgdata** [facelessuser/pymdown-extensions#21]
Hi,
could you please add an example for **b64** extension?

Thanks for your work!

**Comment by facelessuser** [comment]
You just give it a base path and the defined img path should be relative to that.  I believe it will assume absolute if the path is defined like `/myimg.png`.  So in the test example, we have Markdown: https://github.com/facelessuser/pymdown-extensions/blob/master/tests/extensions/b64.txt.

Here is the test file that configures the test with b64: https://github.com/facelessuser/pymdown-extensions/blob/master/tests/extensions/tests.yml#L7.  You can see I'm using a template variable for the base path, but the base is the `tests/extensions` folder: https://github.com/facelessuser/pymdown-extensions/blob/master/tests/test_extensions.py#L126.

So it calculates the actual location of the image as the base + the path relative to the base: https://github.com/facelessuser/pymdown-extensions/blob/master/pymdownx/b64.py#L103. Which is exactly where the image is: https://github.com/facelessuser/pymdown-extensions/blob/master/tests/extensions/bg.png.

And the result is here: https://github.com/facelessuser/pymdown-extensions/blob/master/tests/extensions/b64.html.

It's not practical in most cases as people will generate documents for actual sites that have access to assests, but if you want a portal HTML file (which I sometimes, but rarely, do), this can do it.  I had a specific use for it, so once I wrote it, I just kept it around.  There are obviously extensions here that are more useful than others :wink:.

**Comment by pgdata** [comment]
It's the information I need!
Thank you so much, I hope to contribute as soon as I'll improve my Python experience.

**Comment by facelessuser** [comment]
> Thank you so much, I hope to contribute as soon as I'll improve my Python experience.

You're welcome.  Glad I could help.
