### ISSUE TITLE
DeprecationWarning: Testing an element's truth value will raise an exception in future versions.

### ISSUE THREAD

**Issue by pawamoy** [facelessuser/pymdown-extensions#2113]
### Description

Not really a bug :slightly_smiling_face: 

From a pytest run:

```python
              while last_child is not None:
                  if (
  >                   sibling and block.startswith(' ' * self.tab_length * 2) and
                      last_child and last_child.tag in ('ul', 'ol', 'dl')
                  ):
  E               DeprecationWarning: Testing an element's truth value will raise an exception in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.

  __pypackages__/3.12/lib/pymdownx/details.py:90: DeprecationWarning
```

From https://docs.python.org/3.12/whatsnew/3.12.html#deprecated:

> The [xml.etree.ElementTree](https://docs.python.org/3.12/library/xml.etree.elementtree.html#module-xml.etree.ElementTree) module now emits [DeprecationWarning](https://docs.python.org/3.12/library/exceptions.html#DeprecationWarning) when testing the truth value of an [xml.etree.ElementTree.Element](https://docs.python.org/3.12/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element). Before, the Python implementation emitted [FutureWarning](https://docs.python.org/3.12/library/exceptions.html#FutureWarning), and the C implementation emitted nothing.

Also from https://docs.python.org/3.12/whatsnew/3.12.html#pending-removal-in-python-3-14:

> Testing the truth value of an [xml.etree.ElementTree.Element](https://docs.python.org/3.12/library./xml.etree.elementtree.html#xml.etree.ElementTree.Element) is deprecated and will raise an exception in Python 3.14.

### Minimal Reproduction

Use pymdownx on Python 3.12.

### Version(s) & System Info

- Operating System: arch
- Python Version: 3.12
- Package Version: 10.1

**Comment by facelessuser** [comment]
Yes, this is currently an issue. I'll have to take a peak and fix these cases. I've yet to run this lib under Python 3.12, but these should be easy fixes.

@gir-bot remove S: triage
@gir-bot add S: confirmed

**Comment by facelessuser** [comment]
All related deprecations are fixed in the linked branch. Once Python 3.12 officially releases, we'll update the tests to test 3.12 as well, but locally, all issues are fixed, and all tests seem to be passing on all other supported Python versions.
