### ISSUE TITLE
[SuperFences] Leading/trailing empty lines are not preserved

### ISSUE THREAD

**Issue by madduck** [facelessuser/pymdown-extensions#2152]
### Description

Contrary to the behaviour to `fenced_code`, which I believe is true to the Markdown specs, SuperFences chomps up leading and trailing empty lines:

```

In [1]: import markdown

In [2]: markdown.Markdown(extensions=["fenced_code"]).convert('\n\n'.join(('```', 'foo', 'bar', '```'))).splitlines()
Out[2]: ['<pre><code>',
'foo',
'',
'bar',
'',
'</code></pre>']

In [3]: markdown.Markdown(extensions=["pymdownx.superfences"]).convert('\n\n'.join(('```', 'foo', 'bar', '```'))).splitlines()
Out[3]: 
['<div class="highlight"><pre><span></span><code>foo',
 '',
 'bar',
 '</code></pre></div>']

```

(I've included an empty line at the start dn end of the above, to prove the point that such a line is preserved on GitHub too.)

### Minimal Reproduction

See above

### Version(s) & System Info

- Operating System: Debian unstable
- Python Version: 3.11.4
- Package Version: 9.5

**Comment by facelessuser** [comment]
You aren't comparing apples to apples. What you are seeing is what Pygments does by default. If you use `fenced_code` with `codehilite` (for syntax highlighting) and have Pygments installed, it will strip trailing new lines from the start and the end just like SuperFences.

By default, SuperFences enables highlighting, and if Pygments is installed, you get the observed behavior. Turn off Pygments, and you'll see trailing and leading newlines are preserved. Simply explicitly include `highlight` and set its `use_pygments` option to `False`.

```py
markdown.markdown(
    md,
    extensions=['pymdownx.superfences', 'pymdownx.highlight'],
    extension_configs={'pymdownx.highlight': {'use_pygments': False}}
)
```

To preserve leading and trailing new lines in Pygments, we'd have to manually configure the Lexer to do so.

In short, this is not a bug.

**Comment by facelessuser** [comment]
I believe we could expose a generic option that alters the default configuration of Pygments to output with leading and trailing newlines if desired.

I would consider this new option to alter Pygment's defaults as a feature instead of a bug though.

**Comment by facelessuser** [comment]
The next release will include a new option called `stripnl` in the Highlight extension. This option will be enabled by default and must be turned off to retain leading and trailing newlines when using the Pygments syntax highlighter.
