### ISSUE TITLE
Version 10.2 gives AttributeError for Tabbed extension

### ISSUE THREAD

**Issue by mdehollander** [facelessuser/pymdown-extensions#2158]
### Description

After an automatic update of pymdown-extensions in a CI build for a mkdocs-material docs website, there is this error:

```
  File "/usr/local/lib/python3.11/site-packages/pymdownx/tabbed.py", line 117, in parse_content
    if temp_child.tag not in ('ul', 'ol', 'dl'):
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'tag'
```

With version 10.1.0 the build is ok.  

### Minimal Reproduction

1. Install version 10.2 `pip install pymdown-extensions==10.2`
2. Use the Tabbed extensions in mkdocs-material
3. There is an AttributeError when running `mkdocs build --strict --verbose`
4. Downgrading to version 10.1.0 does not have this error 

### Version(s) & System Info

- Operating System: docker image python:latest
- Python Version: 3.11
- Package Version: 10.2

**Comment by facelessuser** [comment]
@mdehollander Can you provide a reproducible example? The only changes made to Tabbed in this release are found here: https://github.com/facelessuser/pymdown-extensions/commit/e6474b38703b45e3dc431d3c1a0b1f24d80ee7fa#diff-8254230e123ced54a005ff3d5205fc6397a7d8d8de7419bc03bf0d2750de6833.

**Comment by mdehollander** [comment]
Narrowed it down. It happens for me when there is a code block in a tab. I use the indentation method for code blocks and that worked before with 10.1.0:

![image](https://github.com/facelessuser/pymdown-extensions/assets/262872/80a611bd-d7cd-484f-a351-9bf588d7e134)


And in code:
```
=== "Tab 1"

        code

=== "Tab 2"

    Text 2

=== "Tab 3"

    Text 3

```

With 10.2 I can't get the code block inside a tab working.

**Comment by facelessuser** [comment]
Okay, let me take a look.

**Comment by facelessuser** [comment]
Minimal reproduction only requires:

```py
import markdown

md = """
=== "Tab 1"

        code
"""

print(markdown.markdown(md, extensions=['pymdownx.tabbed']))
```

I also see what the fix needs to be.

**Comment by facelessuser** [comment]
Release with bugfix has been made: https://github.com/facelessuser/pymdown-extensions/releases/tag/10.2.1

**Comment by mdehollander** [comment]
Thanks fro the quick fix!
