### ISSUE TITLE
When using both `tabbed` and `blocks.tab`, their counters intermix

### ISSUE THREAD

**Issue by oprypin** [facelessuser/pymdown-extensions#2173]
### Description

I am trying to use both `pymdownx.tabbed` and `pymdownx.blocks.tab` within the same page, but unfortunately the tracking of which tab is open stops working properly then. E.g. clicking the 2nd tab group actually affects the first tab group.

### Minimal Reproduction

Enabled extensions:

```yaml
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.tabbed:
      alternate_style: true
```

Input Markdown:

```markdown
/// tab | a
content a
///
/// tab | b
content b
///

---

=== "a"
    content a

=== "b"
    content b
```

What I get:

```html
<div class="tabbed-set tabbed-alternate" data-tabs="1:2"><input checked="checked" id="__tabbed_1_1" name="__tabbed_1" type="radio" /><input id="__tabbed_1_2" name="__tabbed_1" type="radio" /><div class="tabbed-labels"><label for="__tabbed_1_1">a</label><label for="__tabbed_1_2">b</label></div>
<div class="tabbed-content">
<div class="tabbed-block">
<p>content a</p>
</div>
<div class="tabbed-block">
<p>content b</p>
</div>
</div>
</div>
<hr />
<div class="tabbed-set tabbed-alternate" data-tabs="1:2"><input checked="checked" id="__tabbed_1_1" name="__tabbed_1" type="radio" /><input id="__tabbed_1_2" name="__tabbed_1" type="radio" /><div class="tabbed-labels"><label for="__tabbed_1_1">a</label><label for="__tabbed_1_2">b</label></div>
<div class="tabbed-content">
<div class="tabbed-block">
<p>content a</p>
</div>
<div class="tabbed-block">
<p>content b</p>
</div>
</div>
</div>
```

What I would expect:

```html
<div class="tabbed-set tabbed-alternate" data-tabs="1:2"><input checked="checked" id="__tabbed_1_1" name="__tabbed_1" type="radio" /><input id="__tabbed_1_2" name="__tabbed_1" type="radio" /><div class="tabbed-labels"><label for="__tabbed_1_1">a</label><label for="__tabbed_1_2">b</label></div>
<div class="tabbed-content">
<div class="tabbed-block">
<p>content a</p>
</div>
<div class="tabbed-block">
<p>content b</p>
</div>
</div>
</div>
<hr />
<div class="tabbed-set tabbed-alternate" data-tabs="2:2"><input checked="checked" id="__tabbed_2_1" name="__tabbed_2" type="radio" /><input id="__tabbed_2_2" name="__tabbed_2" type="radio" /><div class="tabbed-labels"><label for="__tabbed_2_1">a</label><label for="__tabbed_2_2">b</label></div>
<div class="tabbed-content">
<div class="tabbed-block">
<p>content a</p>
</div>
<div class="tabbed-block">
<p>content b</p>
</div>
</div>
</div>
```

### Version(s) & System Info

- Package Version: master

**Comment by facelessuser** [comment]
Yes, this is known. `pymdownx.blocks.tab` is supposed to replace `pymdownx.tabbed`, it is not a companion. They generate exactly the same output for backward compatibility to make it so no new styling needs to be generated, you just swap out the syntax and everything works exactly the same. The downside is that they cannot be used together because they generate exactly the same output and confuse each other.

I thought I had put a note in the docs about this, but it is possible I did not.

So I do not view this as a bug. You need to pick one or the other, but not both. I do need to put in a note about using these together. I know in my initial beta discussion I made this clear to people, but that info may not have made it into the docs.

**Comment by facelessuser** [comment]
I will add this or something similar on all related replacement extensions: Tabbed, Admonition, Details, and Definition. It needs to be clear that these are replacements, not alternate ways to do the same things that can live together.

**Comment by facelessuser** [comment]
Moving forward, this notice will be prominently displayed:

<img width="793" alt="Screenshot 2023-09-10 at 6 02 05 AM" src="https://github.com/facelessuser/pymdown-extensions/assets/1055125/72b11e4f-6672-4f54-a5c7-5bb63d8fe7f0">

**Comment by facelessuser** [comment]
Documentation has been updated on main via https://github.com/facelessuser/pymdown-extensions/pull/2174. Closing.
