### ISSUE TITLE
Auto Append Raises Permission Errors

### ISSUE THREAD

**Issue by CollinHeist** [facelessuser/pymdown-extensions#2178]
### Description

When specifying a markdown file to be auto-appended to all pages in Mkdocs, any specification of `auto_append` causes MKdocs to fail building, raising:

```py
Traceback (most recent call last):
  File "C:\Users\{USERNAME}\AppData\Roaming\Python\Python311\site-packages\mkdocs\livereload\__init__.py", line 190, in _build_loop
    func()
  File "C:\Users\{USERNAME}\AppData\Roaming\Python\Python311\site-packages\mkdocs\commands\serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "C:\Users\{USERNAME}\AppData\Roaming\Python\Python311\site-packages\mkdocs\commands\build.py", line 322, in build
    _populate_page(file.page, config, files, dirty)
  File "C:\Users\{USERNAME}\AppData\Roaming\Python\Python311\site-packages\mkdocs\commands\build.py", line 175, in _populate_page
    page.render(config, files)
  File "C:\Users\{USERNAME}\AppData\Roaming\Python\Python311\site-packages\mkdocs\structure\pages.py", line 271, in render
    self.content = md.convert(self.markdown)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\markdown\core.py", line 251, in convert
    self.lines = prep.run(self.lines)
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\{USERNAME}\AppData\Roaming\Python\Python311\site-packages\pymdownx\snippets.py", line 364, in run
    return self.parse_snippets(lines)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\{USERNAME}\AppData\Roaming\Python\Python311\site-packages\pymdownx\snippets.py", line 316, in parse_snippets
    with codecs.open(snippet, 'r', encoding=self.encoding) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 906, in open
PermissionError: [Errno 13] Permission denied: '{DOC DIRECTORY}'
```

This goes away immediately if the YAML section is removed. 

---

The permission errors are present independent of the auto-appended file's path, whether the files exist or not, whether the Mkdocs is launched as an Administator or not, or the permissions of the reported folder.

### Minimal Reproduction

1. Create a simple `mkdocs.yml` config file
    ```markdown
    site_name: PlanningDocs
    theme:
      name: material

    markdown_extensions:
       - pymdownx.snippets:
           auto_append:
             includes/abbreviations.md
    ```
2. Launch mkdocs with `mkdocs serve` - build will fail
3. Remove / comment out the `markdown_extensions` section - build will pass

### Version(s) & System Info

- Operating System: Windows 10 Enterprise 21H2
- Python Version: 3.11.4
- Package Version: MKdocs v1.5.2; pymdown-extensions 10.1

**Comment by facelessuser** [comment]
It sounds like you have a specific permission issue locally. Considering that we use this feature, with MkDocs, in our own documentation (https://github.com/facelessuser/pymdown-extensions/blob/main/mkdocs.yml#L160), it is more likely you have misconfigured something or have some permission issue on your machine. Unless you can provide a minimal, reproducible example, I cannot debug this.

Please provide a zip containing the minimal, reproducible example and I'm happy to attempt a verification of your issue.

**Comment by CollinHeist** [comment]
I thought that as well - so I used a completely fresh install of Python + Mkdocs on a brand new Windows VM and had the exact same issue. 

Are there different permissions utilized for the auto append code when compared to elsewhere?

**Comment by facelessuser** [comment]
Again, I cannot predict what is wrong with your setup without having a minimal reproducible example. There shouldn't be a permission issue, but I have no idea what your document environment looks like, only what you've told me which is very little.

Please follow this guide and provide a minimal reproducible example: https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/?h=repr. Once you provide this, the issue should become quite clear to me if I can reproduce on my system.

**Comment by CollinHeist** [comment]
[MRE](https://github.com/facelessuser/pymdown-extensions/files/12675637/9.3.2-auto-append-permissions.zip); although it does not provide much more than the initial issue.

**Comment by facelessuser** [comment]
It seems the issue is simply a misconfiguration.

1. I don't see `includes/abbreviations.md` anywhere in what you sent me, but that is a side issue.
2. The problem is that you didn't define the file in a list as specified in the docs which is what `auto_append` takes. Below should fix the failure.

```yaml
markdown_extensions:
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
 ```

**Comment by CollinHeist** [comment]
1. Yes I intentionally did not include that because it wasn't necessary for the error
2. That seems to have fixed it - thanks for your help. I was stuck trying to identify and resolve permission errors, should have double checked the syntax. Perhaps better handling of non-list values (i.e. a different error message) could be useful.

Thanks again
