### ISSUE TITLE
Uncaught ReferenceError: Missing element: expected ".tabbed-labels" to be present

### ISSUE THREAD

**Issue by pawamoy** [facelessuser/pymdown-extensions#2225]
### Description

Adding tabs (with the blocks.tab syntax) causes a Javascript error (see title). Tabs are not displayed correctly. Other Javascript based functionality becomes non-responsive (such a Material for MkDocs palette toggle).

### Minimal Reproduction

````bash
cd $(mktemp -d)
python -m venv .venv
. .venv/bin/activate
pip install mkdocs
mkdocs new .
cat <<EOF >>mkdocs.yml
theme:
  name: material
markdown_extensions:
- pymdownx.blocks.tab
EOF
cat <<EOF >>docs/index.md
/// tab | Linux / Mac OS
\`\`\`bash
export DEVBOARD_PROJECTS=~/path/to/your/projects
\`\`\`
///

/// tab | Windows
\`\`\`sh
setx DEVBOARD_PROJECTS ~/path/to/your/projects
\`\`\`
///
EOF
pip install $(mkdocs get-deps)
mkdocs serve
````

### Version(s) & System Info

- Operating System: Linux
- Python Version: 3.11
- Package Version: 10.3.1

**Comment by facelessuser** [comment]
Already covered here: https://github.com/facelessuser/pymdown-extensions/discussions/1973#discussioncomment-7470305

Use:

```yaml
  - pymdownx.blocks.tab:
      alternate_style: True
```

**Comment by pawamoy** [comment]
Oh, thanks, and sorry, I forgot this was needed for the block extension too!
