### ISSUE TITLE
Unneeded deep copy for emoji db

### ISSUE THREAD

**Issue by maartenbreddels** [facelessuser/pymdown-extensions#2239]
### Description

Hi,

In https://github.com/facelessuser/pymdown-extensions/pull/900 you have added a deepcopy.
What there a need for this?
I was doing benchmarking a tracking memory usage and noticed this part using quite some memory, I've fixed this using https://github.com/widgetti/solara/pull/382 but I thought it would be good to report.

Regards,

Maarten

### Benefits

Less memory usage

**Comment by facelessuser** [comment]
We copy in case a user tries to add a custom emoji or override existing emoji. We want it to be added to the current instance, not the default structure.

**Comment by maartenbreddels** [comment]
Ah, if this is a public API I guess you can't change that anymore. Thank you for explaining the decision. My guess Python users/devs would understand that.

Does it make sense to create the markdown object once and re-use it to render many markdown snippets? This would avoid memory copying and initialization of all the extensions.

**Comment by facelessuser** [comment]
Yes, it would make sense to do this. With each new Markdown thing you'd like to parse you can run `md.reset()` on your `Markdown` object.
