### ISSUE TITLE
pymdownx.keys may break base64 encoded images

### ISSUE THREAD

**Issue by changbowen** [facelessuser/pymdown-extensions#2243]
### Description

With a base64 encoded image, given the fact that a base64 encoded string can contain something like `++a++`, the pymdownx.keys would convert it to `A` which will corrupt the content.

pymdownx.keys should perhaps not process strings within a link since the link URL should always be left as-is.

### Minimal Reproduction

1. Enable pymdownx.keys in mkdocs.yml.
2. Create a markdown file with content like this: `![](data:image/png;base64,aaaaa++a++aaaa)`
3. Build and browse to the site, and the resulting image is `<img alt="" src="data:image/png;base64,aaaaaAaaaa">`

### Version(s) & System Info

- Operating System: Windows 10
- Python Version: 3.12
- Package Version: latest

**Comment by facelessuser** [comment]
Currently, "keys" attempts to run right after inline code blocks. This is to ensure content within custom keys don't get processed by the Markdown parser: `++"custom"++`.  The flaw in this this is that it gets run before URL handling.

I think to fix this we need an early processor that process keys with with quoted values, which will not occur in base64 URLs. Then later, we run the problematic cases when other inline processing happens (after URL handling): `++unquoted++`.

This should steer us clear of mangling base 64 URLs.

**Comment by facelessuser** [comment]
I have one more thing in the pipe, but after that, I should be able to cut a release.
