### ISSUE TITLE
CommonMark sublists are not rendered correctly

### ISSUE THREAD

**Issue by YQisme** [facelessuser/pymdown-extensions#2279]
### Description

- a
  - b
- c

Can convenience be improved through pymdown-extensions? Indent sublists two space not four(Typora).
Previously discussed issues
https://github.com/Python-Markdown/markdown/issues/1229

### Benefits

Beneficial for users of Typora editor, not just for Markdown code users

**Comment by facelessuser** [comment]
Python Markdown is not a CommonMark parser, it is an old school parser. Pymdown Extensions was created to mainly add functionality that I wanted when I was creating documents, it is not meant to house all extensions to address everyone's preferences. I have no intention to add an extension to address indentation preferences for lists.

I'd check out other 3rd party extensions to see if any fit your requirements. I do vaguely remember one being out there that may address your request, but I do not know its name off the top of my head.
