### ISSUE TITLE
Code block snippet lines render blank code block, when it's just the first line 

### ISSUE THREAD

**Issue by shaedrich** [facelessuser/pymdown-extensions#2361]
### Description

When I embed a snippet in a code snippet, restricting the lines to `:1:1`, the code block is rendered empty. This can temporarily be fixed by writing `::1` (which should be equivalent), so it's not urgent or anything, but I thought, you might want to fix that.

### Minimal Reproduction

1. Create the following code block:
```pony
--8<-- "some-code-snippet-file-path.pony:1:1"
```
2. Build your site and check the result for the code block

### Version(s) & System Info

- Operating System: ¯\\\_(ツ)\_/¯ 
- Python Version: 3.8
- Package Version: 10.8

**Comment by facelessuser** [comment]
It's actually just a problem with specifying `1` as the start. So even ranges of something like `1:4` will exclude the first line. I know what the issue is and the fix is pretty straight forward.

Thanks for brining this to my attention.

**Comment by shaedrich** [comment]
Sounds good, looking forward to it 👍🏻
