### ISSUE TITLE
Bold + Italic text does not work at the end of a block with `betterem`

### ISSUE THREAD

**Issue by jmsmkn** [facelessuser/pymdown-extensions#2466]
### Description

Having bold + italic text does not work when at the end of a string (example 3):

```Markdown
***I'm bold and italic!** I am just italic.*

*I'm italic. **I'm bold and italic.** I'm also just italic.*

*I am just italic. **I'm bold and italic!***
```

### Expected:

***I'm bold and italic!** I am just italic.*

*I'm italic. **I'm bold and italic.** I'm also just italic.*

*I am just italic. **I'm bold and italic!***

### Result

<img width="332" alt="Screenshot 2024-09-25 at 08 39 09" src="https://github.com/user-attachments/assets/6acaf9c3-472e-4539-9d06-114625884347">

### Minimal Reproduction

Use the above example with `betterem` enabled

### Version(s) & System Info

- Operating System: macos
- Python Version: 3.12
- Package Version: 10.10.1

**Comment by facelessuser** [comment]
I seem to have a viable solution that doesn't break any existing, tested cases. I'll likely test it a bit more to make sure I'm happy with it, but it looks like we will likely have a workable fix.

**Comment by jmsmkn** [comment]
Awesome, thank you!
