### ISSUE TITLE
Allow indexing from end

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [facelessuser/pymdown-extensions#2517]
### Description

In the current state, when including specific line numbers, we can target specific lines.

1. To set starting line number: `myfile:3`
    * This will include the entire file STARTING at line number 3.
2. For lines up to a specific line: `myfile::10`
    * This will include lines 1 - 10
3. For a range of lines: `myfile:4:12`
    * This will include lines 4 - 12.
4. To include a SPECIFIC line: `myfile:3:3`
    * This will only include line number 3
    
    
BUT, what if we wanted to include the last 10 lines of the file. There currently is not a way to index from the end of the file.

### Benefits

Easy feature, which adds more utility, for potentially niche use-cases.

### Solution Idea

Add the ability to do negative indexing:

Given, a file that is 100 lines long-

1. To set starting line number: `myfile:-3`
    * This will include lines 97-100
 2. For lines up to a specific line: `myfile::-51`
    * This will include lines 1 - 49
3. For a range of lines: `myfile:4:-25`
    * This will include lines 4 - 75.
4. To include a SPECIFIC line: `myfile:-0:-0`
    * This will only include the very last line.

**Comment by XtremeOwnageDotCom** [comment]
The idea, is from a relatively new feature in c#

Related Docs:

* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/ranges
* https://blog.ndepend.com/c-index-and-range-operators-explained/

**Comment by facelessuser** [comment]
Just noting that I've seen this and will be considering it. I don't recall if there are any complications involved here, but generally, it feels like a reasonable request, assuming the logic fits well with what we are doing.

**Comment by facelessuser** [comment]
> ### Solution Idea
> Add the ability to do negative indexing:
> 
> Given, a file that is 100 lines long-
> 
> 1. To set starting line number: `myfile:-3`
>    
>    * This will include lines 97-100
> 2. For lines up to a specific line: `myfile::-51`
>    
>    * This will include lines 1 - 49
> 3. For a range of lines: `myfile:4:-25`
>    
>    * This will include lines 4 - 75.
> 4. To include a SPECIFIC line: `myfile:-0:-0`
>    
>    * This will only include the very last line.

Some comments on the proposal.

- Negative indexes will be converted from negative indexes to positive indexes based on the total number of lines. If you have a 100 lines, -1 is equivalent to line 100, etc.

- Negative zero has no significance. Lines increment from 1 to the end, so snippets reference lines with that assumption. When a user specifies zero in Snippets, it is currently clamped to 1 just for sanity, that will not change for a negative -0. As far as snippets is concerned, zero is zero, and you should not use zero, but if you do, it will be clamped to 1. So don't use zero.

- Snippets, previously, did not account for trailing, empty newlines in snippets. This will be rectified to help avoid confusion when viewing a file in an editor and trying to decide what the last line actually is.
