### ISSUE TITLE
Caption ID anchor not recognized by MkDocs anchor validation

### ISSUE THREAD

**Issue by joapuiib** [facelessuser/pymdown-extensions#2529]
### Description

I'm writing a MkDocs page with the following content:

```md
![Exemple de canonades entre processos](img/pipe.png)
/// figure-caption
Exemple de canonades entre processos
///

More text...

Aquest exemple realitzarà la canonada que es mostra a la [Figura 1](#__figure-caption_1).
```

When I build the site, the following message is shown:

```
INFO    -  Doc file 'apunts/01_process/020_comunicacio.md' contains a link '#__figure-caption_1', but there is no such anchor on this page.
```

I've checked that the link with an anchor works and the ID in the figure is generated correctly.

---

After investigating a bit, I've found that MkDocs anchor validation is done via a markdown TreeProcessor with priority 5:

https://github.com/mkdocs/mkdocs/blob/7e4892ab2dd4a52efd95a9de407eee63310e0780/mkdocs/structure/pages.py#L342-L343

Caption Extension is registered with pritority 4:

https://github.com/facelessuser/pymdown-extensions/blob/20be2fc43981a376923482d7be447a2e7c910cc3/pymdownx/blocks/caption.py#L391-L392

Could it be that MkDocs anchor validation is executed before the Caption Extension and the corresponding `<figure id="..">` has not rendered yet?

---

After modifying it in my fork and changing Caption Extension TreeProcessor priority to 6, the warning message disappears.

I can open a PR, but I don't why you have chosen priority 4 and if changing it would break something.

### Minimal Reproduction

1. Configure a MkDocs site and add `pymdownx.blocks.caption` to its extensions.
2. Write a `figure-caption` block.
3. Write a link that references the id `__figure-caption_1`
4. Serve or build the site

### Version(s) & System Info

- Operating System: Fedora
- Python Version: Python 3.12.7
- Package Version: 
    - `pymdown-extensions==10.12`
    - `mkdocs==1.6.1`

**Comment by facelessuser** [comment]
But there is.

```html
Pymdown Extensions Version: 10.12
Markdown Version: 3.7
-----
<figure id="__figure-caption_1">
<p><img alt="Exemple de canonades entre processos" src="img/pipe.png" /></p>
<figcaption>
<p><span class="caption-prefix">Figure 1.</span> Exemple de canonades entre processos</p>
</figcaption>
</figure>
<p>More text...</p>
<p>Aquest exemple realitzarà la canonada que es mostra a la <a href="#__figure-caption_1">Figura 1</a>.</p>
```

This seems like a MkDocs issue, not an us problem. I'm happy to resolve anything that actually points at us as a problem though.

**Comment by facelessuser** [comment]
I cannot help the assumptions MkDocs may or may not make, but I can say, whatever they are doing is not sufficient. This is not the only extension I have that does things as this does. Tabs, Caption, and more all do this. There is nothing fundamentally wrong with what I'm doing either, this is likely poor assumptions on their part in the hopes they'll catch everything they want.

**Comment by facelessuser** [comment]
Yep, no worries. My initial reaction is to do nothing, but after I thought about it a little, I was like yeah, it's a small thing we can do  if it causes no issues.

**Comment by joapuiib** [comment]
Seems that there's already an issue there, stating the same thing.

- https://github.com/mkdocs/mkdocs/issues/3690

**Comment by facelessuser** [comment]
Thanks for pointing this out.

**Comment by facelessuser** [comment]
I refreshed myself on the reasoning as to why Tabs specifies the priority it does. It allows IDs  to be created from tab titles, so it tries to ensure unique IDs.

Caption doesn't create IDs in this way, but instead just uses more rare IDs via `__` prefix. Technically, we may get away with just moving priority, but the issue still remains with Tabs, and I cannot resolve that issue. MkDocs should move their check until the latest possible time, that is the real fix. We can probably mitigate the issue for Captions though, but it isn't something we "have" to do as the real issue is with MkDocs.

**Comment by joapuiib** [comment]
Since MkDocs has to solve it either way, maybe there's no point of changing anything in Captions.

We can just wait 😄

**Comment by facelessuser** [comment]
Looks like they are in agreement with me. I will consider this an upstream issue. Thanks for bringing this up as it seems it help their stale issue to start moving.

**Comment by joapuiib** [comment]
Also, I should have checked in MkDocs before creating this issue here.

**Comment by facelessuser** [comment]
It's tough to always know where the issue is. In this case, because it is MkDocs complaining, that's where I would have checked first, but I have a lot of experience in this area 🙂.
