### ISSUE TITLE
`betterem` extension does not understand italic nested inside of bold, if italic is used later on the same line

### ISSUE THREAD

**Issue by Viicos** [facelessuser/pymdown-extensions#2546]
### Description

```python
import markdown

markdown.markdown("***italic and bold* bold**", extensions=['pymdownx.betterem'])
# '<p><strong><em>italic and bold</em> bold</strong></p>'

markdown.markdown("***italic and bold* bold**: foo bar *italic*", extensions=['pymdownx.betterem'])
# '<p><em><strong>italic and bold* bold</strong>: foo bar *italic</em></p>'

# Workarounds:
markdown.markdown("__*italic and bold* bold__: foo bar *italic*", extensions=['pymdownx.betterem'])
markdown.markdown("***italic and bold* bold**: foo bar _italic_", extensions=['pymdownx.betterem'])
```

I'm currently using one of the workarounds, but maybe this should still be addressed considering it can be pretty confusing.

### Minimal Reproduction

see above

### Version(s) & System Info

- Package Version: 10.12

**Comment by facelessuser** [comment]
This is most likely a sequence problem with `***text*text**` vs `***text**text*`. I imagine we need to swap priority.

**Comment by facelessuser** [comment]
I think I have a fix locally. I'll get a PR up and merged over the weekend.

**Comment by facelessuser** [comment]
I ended up running some more exhaustive tests on these complex, mixed cases, above and beyond the cases in the opening post. I ended up refactoring how cases like these are generally treated. Generally, the patterns needed to be more limited to keep them from greedily creating non-intuitive matches. Moving forward, these should behave more sanely.
