### ISSUE TITLE
Superfence : mathjax inside a code block

### ISSUE THREAD

**Issue by franckl** [facelessuser/pymdown-extensions#270]
Hi,

Is there a way to render LaTeX via mathjax located inside a code block ?
See example below : 

```cpp
int a = pi; // add $\pi$ to the integer a
``` 
Instead of $\pi$ we should see
![image](https://user-images.githubusercontent.com/3875803/38087945-61489d8c-335a-11e8-96aa-784c5d1112b1.png)

**Comment by facelessuser** [comment]
I think by default, MathJax avoids certain code blocks, such as code etc.  You'd have to configure MathJax to target syntax in these elements specially.

Keep in mind, different components of Python Markdown are working on code blocks vs LaTeX math. For instance, I usually use the Arithmatex extension to handle math, and SuperFences to handle code blocks. SuperFences as long parsed the code blocks before Arithmatex gets to it.

You could create special blocks like the [documentation](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#custom-fences) shows for `flow` and `sequence`. I can't promise you'll get exactly what you are looking for, but it does allow you to extend SuperFences to handle special blocks.  I leave that up to the user to read the documentation and push it in the direction they want (or at least push it as far as its capabilities allow).

**Comment by facelessuser** [comment]
As there is no actionable item here, I will close the issue.
