### ISSUE TITLE
`Arithmatex`: Allow disabling of "smart dollars"

### ISSUE THREAD

**Issue by RoyiAvital** [facelessuser/pymdown-extensions#297]
Create an operation mode which protects Math Blocks as in LaTeX.
Namely it should target advanced users who are aware of the edge cases.
It should work well when `MathJaX` is configured to handle only given elements and not scan the `body` for delimiters.

### Inline Math 
 - `\( ... \)` / `\(...\)`.
 - `$ ... $` / `$...$`.

### Display Math
 - `\[ ... \]` / `\[...\]`.
 - `$$ ... $$` / `$$...$$`.

Take care of cases there is line separating them. Something like:
```
$$
...
$$
```

### Environments
 - `\begin{envName} ... \end{envName}` / `\begin{envName}...\end{envName}`
 - Separated by line:
```
\begin{envName}
...
\end{envName}
```

There is also the cases environment is embedded inside *Display Math*:

```
$$\begin{envName}
...
\end{envName}$$
```

Or

```
$$ \begin{envName}
...
\end{envName} $$
```

### Dollar Sign
The Dollar Sign should be escaped: `\$` as in LaTeX.

If needed, I can create an `md` file as a test case.

**Comment by facelessuser** [comment]
Please create a markdown file with edge cases, and I will evaluate with a summary of what will and will not be supported.  A quick glance at what you've written, the only case I currently see is the inability to parse `$ ... $` with spaces.

**Comment by RoyiAvital** [comment]
@facelessuser ,
I will create such file and will share it.

Regarding the `$ ... $` case.
I think that if you take under consideration that the Dollar Sign will appear only as `\$` it should become easy. All needed is to identify `$` and then take the next one as the end. In case of odd number just drop the last one.

**Comment by facelessuser** [comment]
This should already be in place for `\$`. We just need a more relaxed capture pattern when we turn off "smart dollars". Once I have the test markdown file, I'll evaluate it.

Again, this will assume generic mode is false (which is the default), and that MathJax is configured without the `tex2jax` extension.  Generic mode would require plain text parsing with MathJax's `tex2jax` and create weird cases of passing through escaped characters as mentioned earlier: `\\\s` and `\\\\(`. This would still work with generic, but you'd have to take these things into consideration.

**Comment by RoyiAvital** [comment]
@facelessuser ,

Yes, all is fair assumptions (As I wrote above):
1. The dollar sign will be escaped `\$`.
2. `MathJaX` is configured to work with pre defined elements and not with scan mode.
3. `Arithmatex` will be configured in `LaTeX` mode.

I created a GIST - [`MarkDownMathParsing.md`](https://gist.github.com/RoyiAvital/dd319e5d7858e75b195cb6880c2b8e4c).

**Comment by RoyiAvital** [comment]
Could you please share the configuration for the above result?

Both the User Settings and the `math_config.js`.

Thank You.

P. S.
Working in that mode won't kill the Numbering and Tagging features of MathJaX, right?

**Comment by facelessuser** [comment]
I'll share the config when I'm at my computer again. I don't think it'll mess up numbering.

**Comment by facelessuser** [comment]
#300 address this issue.  See a [generic setup](https://github.com/facelessuser/pymdown-extensions/pull/300/files#diff-1dce4448b59b9d2c5d91d63545c45d85R10) in the pull request:. See HTML output for the [MathJax config](https://github.com/facelessuser/pymdown-extensions/pull/300/files#diff-9d7d778c82b508bc3ea52ba39f351b90R44).  Notice in the config we don't enable `$...$` scanning in MathJax, but `$...$` still works fine.

To use a non-generic approach (the recommended) by not enabling `generic` and disabling `smart_dollar`. You would then use a config like [this](https://github.com/facelessuser/pymdown-extensions/blob/master/tests/extensions/arithmatex/arithmatex.txt#L65) for MathJax which doesn't use the plain text scanner `tex2jax` .

**Comment by RoyiAvital** [comment]
@facelessuser , I'm a bit confuse.

What's the best configuration (Of `Arithmatex`) to render all cases in the Test Case?
I don't mind (Even prefer) turning off `tex2jax` as now `Arthimatex` is taking care of the parsing.

By the way, I think you should upgrade to `MathJax` 2.7.4 in the CDN.

**Comment by facelessuser** [comment]
The best setup (and recommended) would be:

1. Do not set `generic`. Leave it set to the default `False`.
2. A MathJax config similar to this (it does not use `tex2jax`): https://github.com/facelessuser/pymdown-extensions/blob/master/tests/extensions/arithmatex/arithmatex.txt#L65.  Feel free to tweak alignment or other features.
3. Turn off `smart_dollar` (default is `True`).

Just an FYI, while the work has been completed, his has not been released yet.

**Comment by facelessuser** [comment]
> By the way, I think you should upgrade to MathJax 2.7.4 in the CDN.

Thanks for the heads up. I will make a note and update the documents and tests to use the latest.

**Comment by RoyiAvital** [comment]
If `smart_dollar` turned off then `$ ... $` will work?
I'm just not sure about the settings of `Arithmatex`.
What each settings does in practice.

I know the model is not let `MathJax` do parsing but to tag HTML blocks which marks them for `MathJax` treatment.
This is done by not using `tex2jax`.

**Comment by facelessuser** [comment]
Yes, smart_dollar controls *how* arithmatex handles dollar, it doesn't control whether it recognizes dollar. Please read arithmatex's documentation to learn more.

Reading up in this, you might be able to continue using tex2jax if you add `processClass` in the MathJax config and set it to `arithmatex`. Haven't tried it yet, but it sounds like it will solve issues related to using it.

**Comment by facelessuser** [comment]
No worries, what seems intuitive to one is not always intuitive to another.

In the paragraph, I may rephrase stating that disabling smart_dollar disables the aforementioned whitespace requirements. I may issue with your suggestion as well.

**Comment by RoyiAvital** [comment]
I'd be honored if you take something from me :-).

I know developers hate this, but any ETA when I will be able to use this feature?
It's the only show stopper I have in order to start using Sublime Text as my sole MarkDown editor.

**Comment by facelessuser** [comment]
FYI, to use `tex2jax` you have to use two options.  First you must ignore any element with any class and any element with no class.  Then, you provide an exception telling it to process any element with the `arithmatex` class.  That way you basically tell it to only process elements with `arithmatex`.  This makes escape handling a bit better from Markdown to HTML `\$` will ignore dollar in markdown and then become just `$` in HTML.  But it shouldn't get processed by `tex2jax` because arithmatex didn't wrap it in a span with an `arithmatex` class.  It is still recommended to not use `tex2jax`, but this is how you can use it without issue (based on my limited testing).

```
    ignoreClass: ".*|",
    processClass: "arithmatex"
```
> I know developers hate this, but any ETA when I will be able to use this feature?

When the release is done 😄 .  I have one feature in the pipe #302 .  It is contingent on a Mkdocs Material issue.  As soon as the new feature is confirmed to need no changes, I plan on cutting a new release.
