### ISSUE TITLE
[Q] Critics has no any background color  when using with Mkdocs?

### ISSUE THREAD

**Issue by Guang1234567** [facelessuser/pymdown-extensions#310]
Hello dev:

I use Critics into Mkdocs (default theme), but no green background when i write

```
 {++insert one++} 
```

in my markdown file?

**Comment by facelessuser** [comment]
You'll need to add your own custom CSS to document theme. Please read over the documentation as it describes the HTML output.

**Comment by Guang1234567** [comment]
@facelessuser

Thanks a lot.

I fix it in:
 https://github.com/Guang1234567/MyNotebook/commit/2cef2778732fdbf40ff3a0951faa24b57ced4b4f

Hope it help other people.

**Comment by Guang1234567** [comment]
In addition:

When i use `progressbar` extension, i write 

```
[=0%]{: .thin}
[=5%]{: .thin}
[=25%]{: .thin}
[=45%]{: .thin}
[=65%]{: .thin}
[=85%]{: .thin}
[=100%]{: .thin}

```

into my markdown file for test.

Then maybe has some bug like below:

![20180612141558](https://user-images.githubusercontent.com/8240718/41273226-31385606-6e4b-11e8-963f-ecc0222584e6.png)

**Comment by facelessuser** [comment]
@Guang1234567, it isn't a bug as the document's examples use this very feature, and we have tests for it as well, but it is most likely just not clearly explained in the documentation.  `markdown.extensions.attr_list` must be enabled for this feature to work.

- In our tests, we enable it as you can see [HERE](https://github.com/facelessuser/pymdown-extensions/blob/master/tests/extensions/progressbar/tests.yml#L8).
- You can see in our tests we use the feature [HERE](https://github.com/facelessuser/pymdown-extensions/blob/master/tests/extensions/progressbar/progressbar.txt#L1).
- And the results are [HERE](https://github.com/facelessuser/pymdown-extensions/blob/master/tests/extensions/progressbar/progressbar.html#L9).

**Comment by facelessuser** [comment]
As the original question was answered, I will close this issue. Please open a new issue for discussion of new topics moving forward.
