### ISSUE TITLE
Is it possible to have processed markdown content inside of tabbed code blocks?

### ISSUE THREAD

**Issue by markpiller** [facelessuser/pymdown-extensions#313]
This is not an issue, but more of a question. Tabbed code blocks work great for us except for the scenario where a tab content is more than just code and includes other markdown content. We see that in those cases, the markdown content is not getting processed and shows up as-is in a `<pre>` element.

**Comment by facelessuser** [comment]
I don't think I understand your question.  What do you mean by the following?

> Tabbed code blocks work great for us except for the scenario where a tab content is more than just code and includes other markdown content.

This doesn't quite make sense to me what you are asking.  Are you doing something contrary to the spec?  Can you give examples?

**Comment by markpiller** [comment]
Thank you for your response. Perhaps we're doing something that's not supported. Here's a sample of the markdown:
`````
````tab="Using Java Map"
#### Blocking API

```
public void updateContact()
{
 // sample code here
}
```

#### Non-Blocking API

```
public void updateContact()
{
 // sample code here
}
```

````

````tab="Custom Class"
 Consider the following class: 

```java
package com.sample;

public class Contact
{
 // sample code
}
```

````
`````

This is what it looks like once it is rendered:
![Alt text](https://monosnap.com/image/wqOToCPLclRSF6HWlDVtXfO0ntJaXQ.png)

**Comment by facelessuser** [comment]
This seems as I would expect.  I'm going to make a guess as to what the confusion could be.

What I think is happening is a misunderstanding of what the **tab** feature for superfences is. The feature is not a *special fence* for tabs, but a **special attribute** applied to a fence. It is no different than the attribute **linenums**.  What it does is say this fenced code block is also a tab.  In post processing, SuperFences finds these tabs and groups them together in a tabbed interface.

This feature was meant to accommodate common use cases as seen in the example [here](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#tabbed-fences).  You just specify consecutive code blocks, and note that they are all tabs so they get grouped together.

Now, is there a way to trick SuperFences into handling your use case? Technically you could trick it into handling other content if you know how it works under the hood.  Now what I'm going to show you, I will not guarantee will remain this way in future iterations, and if you tell anyone I told you this, I will deny it :smile:.  Technically you could put something like this in (it assumes you are using https://facelessuser.github.io/pymdown-extensions/extensions/extrarawhtml/, which is just the component from Python Markdown's `extra` extension that is compatible with `pymdown-extensions`).

````
<superfences>
<input name="__tabs_%(index)s" type="radio" id="__tab_%(index)s_%(tab_index)s" %(state)s/>
<label for="__tab_%(index)s_%(tab_index)s">My Title</label>
<div class="superfences-content" markdown="1">

### Header

```python
import test
```
</div>
</superfences>
````

I **do not** recommend doing this as this is undocumented and I offer no guarantees that I won't change this.  Also, if you are using the Mkdocs Material theme, I don't think the theme accounts for anything in tabs except code blocks, so styling may be weird as well.  But technically, you could trick it, but please don't 😄 .

**Comment by markpiller** [comment]
Thanks, @facelessuser . That does the trick! I want to be cautious though and will take your word of advice. We will come up with another alternative (i.e. raw html) for the scenario when tab's content is more than just code
