### ISSUE TITLE
[Feature Request] - Better Table of Content [TOC] Implementation - Let the User Set Which Header Level Are Included

### ISSUE THREAD

**Issue by RoyiAvital** [facelessuser/pymdown-extensions#318]
Hello,

The current Python Markdown supports Table of Content generation as a built in feature.
Yet it is very limited in its customization.

I would like have a different TOC Plug In which enables one more feature - Let the user have the choice which header levels will get into the Table of Content.

For instance have a variable named `activeHeaderLevels` which is a list.  
For `activeHeaderLevels = {2, 3, 5}` only headers of level 2, 3, and 5 (Generated by `##`, `###` and `#####`) will be in the TOC while other will be ignored.

**Comment by facelessuser** [comment]
It is doubtful that i will essentially fork the TOC code here.  I honestly have no interest in taking on the maintenance cost for that plugin here.

This could most likely be implemented as a Treeprocessor that runs right after Toc. It would look for and filter out certain headers from the built table of contents that Toc creates.  I *think* it could be done without having to fork or create a whole separate Toc handler.

I'm generally more agreeable when it comes to adding a feature into something I already support, but when it comes to creating a whole new extension, I really have to be vested, meaning I plan to use the extension myself.  Unfortunately, I do not currently have a use for such a feature.

I **might** play around with how easy it would be to create a filter extension, but it is very uncertain whether I would commit to maintain such an extension myself.

**Comment by RoyiAvital** [comment]
@facelessuser , I totally understand.
Hopefully you find it is easy to do.

By the way, are you involved in the [Python Markdown project](https://github.com/Python-Markdown/markdown)?
Maybe you can make them interested in implementing directly there?

**Comment by facelessuser** [comment]
For now, I'm passing on this as I've yet to have a need for this.

@gir-bot add S: wontfix
