### ISSUE TITLE
Fix links to Python Markdown documentation

### ISSUE THREAD

**Issue by kylebarron** [facelessuser/pymdown-extensions#327]
In several places, such as [this page](https://facelessuser.github.io/pymdown-extensions/extensions/extra/) there are links to the Python Markdown documentation, i.e. 
```
https://pythonhosted.org/Markdown/extensions/footnotes.html
```

The Python Markdown documentation sometime switched websites and is now hosted at  python-markdown.github.io. So these links should be switched to i.e.:
```
https://python-markdown.github.io/extensions/footnotes/
```

**Comment by facelessuser** [comment]
Cool.  Pull requests are welcome, but if no one gets to it, I'll eventually get it updated. Thanks!
