### ISSUE TITLE
[Feature Request] MagicLink to repository files

### ISSUE THREAD

**Issue by jdumas** [facelessuser/pymdown-extensions#362]
Hi.

I was wondering if it'd be possible to link to specific files in a repository tree (e.g. on github). Either the latest version of the file (master/...), or a specific commit (181c06d1f1...). Right now it doesn't seem that MagicLink supports this kind of operation? Would it be easy to add?

**Comment by facelessuser** [comment]
Can you elaborate what syntax you'd expect to work? Is this idea based on existing  GFM  support?

**Comment by jdumas** [comment]
Hmm right, I suppose it's not in GFM because you can already use [relative urls](https://stackoverflow.com/questions/40422790/relative-link-to-repos-root-from-markdown-file) (works for the main branch, or to link to another branch).

Right now I'm just looking for a convenient way to reference a url to a file in the repository associated to a website build with mkdocs. The MagicLink plugin offers a convenient way to use shortlinks for issues and whatnot. But I don't have a specific syntax in mind for files. Maybe something like `[filename](master:path/to/file.cpp)` or `[filename]{sha1:path/to/file.cpp}` (the latter being less likely to conflict?).

**Comment by facelessuser** [comment]
Most of MagicLinks' links are pulled either from [GitHub's](https://help.github.com/articles/autolinked-references-and-urls/) or [GitLab's](https://docs.gitlab.com/ee/user/markdown.html#special-gitlab-references).  In all honestly, MagicLink has borrowed more heavily from GitLab in most recent iterations. I'm basically trying to provide solutions via already familiar solutions.  People are most familiar with GitHub as it is the most popular, and GitLab has borrowed heavily from GitHub, but IMO has added/altered some other very cool linking on top of what GitHub has, but even then, I haven't added everything GitLab has done (not all of it is practical for an extension that is not connecting to their online API).

Obviously we've also added some of our own syntax sugar to provide linking to different repo hosts as well with the general aim to keep the spirit of the syntax in tact.

None of the current big git hosting sites really provide such a shorthand at the moment, not even [Bitbucket](https://confluence.atlassian.com/bitbucketserver/markdown-syntax-guide-776639995.html).  They all require a direct link to the file.

I could develop my own syntax style for such a feature, but it could become obsolete if a more standard and familiar way was adopted by one of the big hosting sites as that has been MagicLink's primary goal.  I would be less keen on `[filename](master:path/to/file.cpp)`, but I'm still not certain that I want to go down this road with `[filename]{sha1:path/to/file.cpp}` either. Let me think about this.  I make no promise whether we will adopt our own methodology on this, but I'd like some time at least to consider this proposal. This would be an easier decision if there was a preexisting  model to base this off of as that has primarily been MagicLink's approach.

**Comment by jdumas** [comment]
Sure. I would also prefer if there were a standard solution for this, but I am not aware of a standard syntax. Right now I've hacked your `pathconverter.py` plugin for my personal use to provide a replacement based on a user-provided dict `(key, value)`. E.g. it will replace links like this `[filename]({{ from }}/folder/file.cpp)`. However, with version 1.0 of mkdocs it generates warnings as urls as interpreted as internal links, but the replacement happens at postprocessing after the html has been generated.

**Comment by facelessuser** [comment]
At this point in time, I believe I'm gong to pass on this request.  My motivation when taking on features is usually, does it make it more configurable (which allows more freedom and save me from developing new features in the future), or will I use it.  In this case, this doesn't extend flexibility of existing features, nor is it something I have a need to personally use at this time.

In the future my needs may change, and maybe I will reconsider this.  Or if there becomes a general standard adopted by git providers, I may also reconsider as that would fall more in line with what magiclink is trying to provide (a familiar set of link related features to what git providers provide).
