### ISSUE TITLE
snippets not evaluating markdown extra data

### ISSUE THREAD

**Issue by perezd** [facelessuser/pymdown-extensions#529]
I'm using mkdocs-markdownextradata-plugin==0.0.5 to reference extra values in my markdown. When I use snippets to include another file I'm noticing that the evaluation of my extra data stopped working as intended. Any ideas on how to workaround?

**Comment by perezd** [comment]
Further analysis: Other types of extensions are being evaluated, such as superfences and details.

**Comment by facelessuser** [comment]
Do you have an example for reproduction?

**Comment by facelessuser** [comment]
Also, I don't know what mkdocs-markdownextradata-plugin is.

**Comment by perezd** [comment]
[repro.zip](https://github.com/facelessuser/pymdown-extensions/files/2950048/repro.zip)

That is a repro of the issue.

**Comment by perezd** [comment]
This the plugin: https://pypi.org/project/mkdocs-markdownextradata-plugin/

**Comment by facelessuser** [comment]
Can you also explain more how your variables stopped working? I don't yet have a clear understanding of what you expect to happen vs what actually happens. Are you saying variable replacement doesn't work everywhere? Just in snippet content? Please provide specific details.

**Comment by perezd** [comment]
Sorry, to be clear the variables work normally everywhere except within the
snippet. If you give my repro a run I show a simple example of it rendering
the variable as it should and a snippet with the very same variable not
rendering.


It seems like a necessary pass isn't running within the snippet extension
processor from what I can tell.

Did the repro zip help?

**Comment by facelessuser** [comment]
From what you describe, it sounds like the variables are applied before the snippet is. I suspect they try to run their as early as possible, while we try to run early as well. Sounds like they are running first.

**Comment by facelessuser** [comment]
Ah, theirs is a mkdocs plugin. It is run before the markdown parser. I can never run before that. You'd need a mkdocs plugin that basically does the same thing as our snippet extension and have it run before the mkdocs plugin.

**Comment by perezd** [comment]
FWIW for other readers passing by:
https://github.com/mkdocs/mkdocs/issues/304#issuecomment-460058741
There is a workaround.

**Comment by facelessuser** [comment]
Glad you got something working!
