### ISSUE TITLE
How to set TOC links at left with chain icon?

### ISSUE THREAD

**Issue by soronpo** [facelessuser/pymdown-extensions#609]
I tried to find in the documentation and couldn't. The documentation's own TOC links are different than the default mkdocs-material. They appear on left and with the chain icon. How is this done?

![image](https://user-images.githubusercontent.com/8167952/60751377-647b9700-9fbc-11e9-828f-80fc7415f379.png)

**Comment by facelessuser** [comment]
This is done with this styling: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/_headeranchors.scss. And this setting https://github.com/facelessuser/pymdown-extensions/blob/master/mkdocs.yml#L64.

I just preferred this look, so I maintain the styling in my personal documentation. You can probably dig out the converted scss style as CSS from the converted CSS file: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/theme/extra-30d8e6755c.css.

**Comment by soronpo** [comment]
Many thanks!
