### ISSUE TITLE
How to use e.g. Emoji extensions for Sphinx and not MkDocs

### ISSUE THREAD

**Issue by Naereen** [facelessuser/pymdown-extensions#62]
Hi,

First, thanks and :clap: for your project, it's neat and awesome!

Second, a quick question: you describe in details in your project documentation how to use your extensions for MkDocs.
Do you know if they could also be used for Sphinx doc ?

So far, I use recommonmark's markdown parser to add support for Markdown in Sphinx doc, but maybe using [Python Markdown](https://pythonhosted.org/Markdown/) should also be possible, and so using your extensions (especially the Emoji one) should be possible.

> See [this question I asked on StackOverflow](https://stackoverflow.com/questions/42087466/sphinx-extension-to-use-github-markdown-emoji-in-sphinx) and [that comment](https://stackoverflow.com/questions/42087466/sphinx-extension-to-use-github-markdown-emoji-in-sphinx#comment73617151_42256239).

Thanks in advance!

**Comment by facelessuser** [comment]
> First, thanks and 👏 for your project, it's neat and awesome!

Thanks!

> Do you know if they could also be used for Sphinx doc ?

I'm not sure if it is directly usable for Sphinx docs as I don't use Sphinx.  If Sphinx can use Python Markdown, then I would say yes, if not, then no.

I just don't have any experience with Sphinx, so I really can't answer this.  Sorry.  I hope you get your answer though.

**Comment by Naereen** [comment]
Hi,
Thanks for your quick reply.

My two hacks (cf. « 2 partial solutions » in [my partial answer](http://stackoverflow.com/q/42087466/)) don't satisfy me completely, so I will try to find a better (and cleaner) way to do what I wanted.

Ideally, it should be a Sphinx extension to provide Emoji.
Don't really know when, but I will try !

**Comment by facelessuser** [comment]
Makes sense.  For now, I will close this issue as there is no real actionable item for pymdown-extensions to do.

**Comment by Naereen** [comment]
Alright.
