### ISSUE TITLE
Container-extension?

### ISSUE THREAD

**Issue by berot3** [facelessuser/pymdown-extensions#630]
Hi! I am not sure if I am right here but I am looking for extension for mkdocs which allows "containers" like the one from [markdown-it-container](https://github.com/markdown-it/markdown-it-container).

```
::: warning
*here be dragons*
:::
```

Demo can be seen here: https://markdown-it.github.io/

If it is not done yet, maybe you can do it? :)

Ultimately I would like to use it in mkdocs-material! I think it would be a great addition.

**Comment by facelessuser** [comment]
Pymdown-Extensions is mainly extensions I have a current need for. It isn't really a catch-all for any extension. Unless I have an immediate need for an extension, I don't implement them.

The only containers I have potential plans for are tabbed containers.

I personally don't really see much of a use for the kind of containers you are describing as there are already ways to get essentially the same thing:

1. [Admontions](https://python-markdown.github.io/extensions/admonition/) really fill this void already.

    ```
    !!! warning
        *here be dragons*
    ```

2. If Admontions aren't your thing, you can easily use something like [Extra](https://python-markdown.github.io/extensions/extra/) or [extrarawhtml](https://facelessuser.github.io/pymdown-extensions/extensions/extrarawhtml/) and just do something like:

    ```html
    <div class="warning" markdown="1">

    *here be dragons*

    </div>
    ````

There may be other extensions somewhere that allow something you are looking for, but you can also write your own 😉 .
