### ISSUE TITLE
Arithmatex math fences example not rendered properly

### ISSUE THREAD

**Issue by emddudley** [facelessuser/pymdown-extensions#691]
The [Arithmatex math fences](https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/#alternative-math-blocks) example code is not being rendered properly in the live documentation. The ampersand is displayed as `amp;` but it should not be visible. Using Arithmatex without math fences works fine.

![math-fences](https://user-images.githubusercontent.com/389629/66844962-3d2e5180-ef3d-11e9-9832-53a19bbcaaef.png)

**Comment by facelessuser** [comment]
Thanks for the report. I know what is causing this. For fences we are escaping the bare minimum of symbols to entities. We place it in a script tag and It gets parsed. Unfortunately, I thought MathJax was smart enough to handle this. Scripts on occasion still need to allow escapes to avoid `</script>`. 

I'll have to play around with this. To be honest, the other method probably should have escaped these characters as well, but it looks like that got overlooked.

Anyways, I'll sort it out.

**Comment by facelessuser** [comment]
Yeah, there appears to be nothing builtin to MathJax that parses HTML entities in script tags.

The format `<script type="math/tex">` which MathJax recognizes, would need us to pre-process entities. Consider how unlikely it is that someone would enter `</script>` into these blocks, I'm just going to not escape the content in this scenario.
