### ISSUE TITLE
Include a file content into superfences blocks

### ISSUE THREAD

**Issue by hason** [facelessuser/pymdown-extensions#718]
I want to import a file into superfences block e.g.:

<pre>
```plantuml include=diagram/deploy.plantuml
```
</pre>

Includes all lines from second line
<pre>
```python include="module/file.py 2:-1"
```
</pre>

**Comment by facelessuser** [comment]
I feel like this could already be done with custom fences. The syntax wouldn't be exactly the same, but I feel like you could still do it. I'm not sure this really needs any effort from me.

I'd check out SuperFences documentation on custom fences and see if you can role your own. I'm happy to answer any questions you may have if you get stuck.

@gir-bot remove triage
@gir-bot add feature wontfix

**Comment by facelessuser** [comment]
@gir-bot add feature wontfix

**Comment by facelessuser** [comment]
Whoops, command was wrong

@gir-bot add feature, wontfix

**Comment by facelessuser** [comment]
I'm going to close this as I'm fairly certain something could be implemented with custom fences. For now I will leave it as an exercise for the user to explore.
