### ISSUE TITLE
Docs: no extension names

### ISSUE THREAD

**Issue by twardoch** [facelessuser/pymdown-extensions#737]
The pymdownx documentation seems not to include the actual names of the extensions anywhere. It’s hard to figure out how they’re called. For example, that in order to use Snippets, I need to refer to `pymdownx.snippets`

**Comment by facelessuser** [comment]
Yeah, some of them have examples that show this, but some do not. I need to fix that.

@gir-bot add T: maintenance, C: docs
@gir-bot remove S: triage
