### ISSUE TITLE
The mark extension with Chinese

### ISSUE THREAD

**Issue by rapon233** [facelessuser/pymdown-extensions#751]
While wirting w/ mkdocs and pymdown-extensions 'Mark', I found that
```
abcde==fghi==jklmn  
abcde ==fghi== jklmn
```
would produce differently.
It's natural for languages with spaces to seperate words, but for Chinese 
```
Chinese sentences are like:
这是一个中文实例。
After mark,
这是一个==中文==实例。
这是一个 ==中文== 实例。
```
It's a little bit abnormal, would u pls fix that or give me some suggestion?

I use the latest VSCode and mkdocs, BTW.

**Comment by facelessuser** [comment]
So, if I understand, you don't want "Mark" to be sensitive to space? You can try disabling "smart" logic:  https://facelessuser.github.io/pymdown-extensions/extensions/mark/#options.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by rapon233** [comment]
Thanks! Problem solved.
