### ISSUE TITLE
AttributeError: module 'markdown.extensions.extra' has no attribute 'MarkdownInHtmlProcessor'

### ISSUE THREAD

**Issue by retsyo** [facelessuser/pymdown-extensions#771]
actually I am using https://github.com/ncornette/Python-Markdown-Editor, 
I have installed latested cloned `markdown` and `pymdown-extensions`

which says
```
>e:\prg\py\Anaconda3_64\python.exe -u "markdown_edit.py"
Traceback (most recent call last):
  File "markdown_edit.py", line 108, in <module>
    main()
  File "markdown_edit.py", line 95, in main
    markdown_processor = markdown.Markdown(**options)
  File "e:\prg\py\Anaconda3_64\lib\site-packages\markdown-3.2.dev0-py3.6.egg\markdown\core.py", line 97, in __init__
  File "e:\prg\py\Anaconda3_64\lib\site-packages\markdown-3.2.dev0-py3.6.egg\markdown\core.py", line 125, in registerExtensions
  File "e:\prg\py\Anaconda3_64\lib\site-packages\markdown-3.2.dev0-py3.6.egg\markdown\extensions\__init__.py", line 77, in _extendMarkdown
  File "e:\prg\py\pure_pylib\_io\_markdown\facelessuser\pymdown-extensions\pymdownx\extrarawhtml.py", line 30, in extendMarkdown
    extra.MarkdownInHtmlProcessor(md.parser), 'markdown_block', 105
AttributeError: module 'markdown.extensions.extra' has no attribute 'MarkdownInHtmlProcessor'
```

I fix the problem by modify `pymdownx\extrarawhtml.py`
1. change
```python
from markdown.extensions import extra
```
to
```python
from markdown.extensions import md_in_html
```

2. change
```python
extra.MarkdownInHtmlProcessor(md.parser), 'markdown_block', 105
```
to
```python
md_in_html.MarkdownInHtmlProcessor(md.parser), 'markdown_block', 105
```

**Comment by facelessuser** [comment]
You are using a dev version of Python Markdown which is not currently supported.

**Comment by facelessuser** [comment]
The extrarawhtml extension was originally added to expose the raw HTML logic so you could include it without including all of the built-in extra extension. In Python Markdown 3.2.dev, the md_in_html extension does that now. Extrarawhtml is no longer needed as its existence is now made redundant with the addition of md_in_html.

While I will as some logic at some point to handle this change, I will also add a deprecation warning for extrarawhtml at the same time.

If you are using Python Markdown 3.2.dev, you should just use md_in_html as extrarawhtml will go away in the future.

**Comment by facelessuser** [comment]
Next version should will handle 3.2, but it may not release until 3.2 does.

https://github.com/facelessuser/pymdown-extensions/pull/773
