### ISSUE TITLE
Add support for server-based plantuml diagrams

### ISSUE THREAD

**Issue by chbndrhnns** [facelessuser/pymdown-extensions#779]
Would you consider adding support for [this](https://github.com/mikitex70/plantuml-markdown) plugin?

I am following a everything-as-code philosophy and would also like to keep my diagrams as code.

**Comment by facelessuser** [comment]
I'm not sure I understand the request. You want me to support a 3rd party extension with one of my extensions?  Can't you just use the 3rd party extension?

@gir-bot remove S: triage
@gir-bot add S: more-info-needed

**Comment by chbndrhnns** [comment]
I guess I missed the part that all extensions provided here are yours (and no 3rd party extensions).
It is perfectly fine for me to use the 3rd party extension directly. What I envisioned was to install just a single package and have everything I need.

**Comment by facelessuser** [comment]
Everything in pymdown-extensions was created by me. It is essentially a collection of extensions that I wanted for my own purposes. It is a bit too much work to take on support for everyone's favorite extensions.

**Comment by chbndrhnns** [comment]
Yep, I totally understand that.
