### ISSUE TITLE
MagicLink: Single-word hostnames not recognised as links.

### ISSUE THREAD

**Issue by willstott101** [facelessuser/pymdown-extensions#794]
We tend to give intranet servers a single-part hostname such as george so URLs end up being like this: https://george/wiki/

Links with hostnames like this are recognised and hyperlinked by GitLab and GitHub markdown. However this implementation does not recognise them as links.

I noticed this whilst using your sublime extension. When switching to an API back-end this was an obvious difference for me. I'd love to be able to use this when preparing docs for our local GitLab instance, without having to make network requests.

Thanks for your work btw, lots of small commits to format a doc correctly drives me crazy :)

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add T: bug, S: confirmed
