### ISSUE TITLE
Version consistency

### ISSUE THREAD

**Issue by yochananmarqos** [facelessuser/pymdown-extensions#811]
The Github release is 6.3.0 while the PyPI version is 6.3.

**Comment by facelessuser** [comment]
Yes, I always tag it as 6.3.0, 7.0.0, 8.2.1, etc. But versions always package and report as 6.3, 7.0, 8.2.1. This is expected.

**Comment by facelessuser** [comment]
For reference: https://github.com/facelessuser/pymdown-extensions/blob/master/tests/test_versions.py#L13

**Comment by yochananmarqos** [comment]
I'm not following. Other packages don't have this issue.

**Comment by facelessuser** [comment]
The releases on PyPI are very consistent. They always follow the same pattern.

The tag is arbitrary, I've chosen to tag them in a similar way, but yes, it is not exact. Is this causing some kind of issue for you?

It is unlikely that I will retroactively re-tag all previous releases to match the distribution. In the future, I may consider matching them, but I am curious as to how this is an issue.

**Comment by facelessuser** [comment]
Just for clarity. PyPI are the official releases: https://pypi.org/project/pymdown-extensions/#history.

GitHub releases is just a mechanism for me to tag a hash to kick off the deployment. It is also convenient for me if I ever need to do another bug fix on an old major version once I've released a new major version.  Some projects don't even tag the hash when releasing and rely on PyPI to be the archive for the releases: https://bitbucket.org/mrabarnett/mrab-regex/src/hg/.

But yes, many projects do make sure their GitHub releases align exactly with the versioning scheme.

**Comment by yochananmarqos** [comment]
I see, thanks for the explanation. It was just because the AUR package was using GitHub releases instead of PyPI releases. I've asked the AUR maintainer to use PyPI releases instead. No worries, It just makes it easier overall for me writing PKGBUILDs no matter what source is used.

**Comment by facelessuser** [comment]
Ah, I am unaware of how others use tags and such outside of my own little world here. I don't mind considering moving forward with a similar naming scheme as what is done in PyPI, but I don't want to trigger new PyPI releases by re-tagging (most likely they'd be denied as the release already exists).

**Comment by yochananmarqos** [comment]
Again, no worries. Your reasoning makes sense. No need to change it, nevermind me
