### ISSUE TITLE
Provide example for tabbed code blocks

### ISSUE THREAD

**Issue by wilhelmer** [facelessuser/pymdown-extensions#846]
Could you provide a sample for tabbed code blocks using `pymdownx.tabbed` in the docs? I can't get it to work with Material v5.

Is it supposed to work like this?

````
=== "Bash Tab"
    ```Bash
    #!/bin/bash
    STR="Hello World!"
    echo $STR
    ```

=== "C Tab"
    ```C
    #include 

    int main(void) {
    printf("hello, world\n");
    }
    ```
````

But then, the "Bash" and "C" after the triple backticks get added to my code sample. Also, codehilite doesn't work.

**Comment by facelessuser** [comment]
There are examples on the `pymdownx.tabbed` document page: https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/#syntax.

Now keep in mind that Material Beta 3 is currently styling the background of code blocks the same as non code blocks which can be confusing. I'm currently talking with the author to try and come up with some kind of different styling.

**Comment by wilhelmer** [comment]
None of the examples show a tabbed code block, they all show standard Markdown (text) content.

So is the syntax of my example above correct?

**Comment by facelessuser** [comment]
You just use a language identifier as  normal. If you look at the raw source, you can see under the settings details (bottom of page), we use language identifiers: https://raw.githubusercontent.com/facelessuser/pymdown-extensions/master/docs/src/markdown/extensions/tabbed.md.

There's no special syntax for code vs any other content under a tabbed container.

**Comment by wilhelmer** [comment]
Then why doesn't it work 😕 

Output for my example above:

![tabbed-output](https://user-images.githubusercontent.com/2234833/76210208-f13dbb00-6203-11ea-8590-a5d697bf44cc.jpg)

Is that really all related to Material? I'd assume that at least the ```"Bash" being written to the container is some issue with the extension.

**Comment by wilhelmer** [comment]
Oh my, of course you have to have both `tabbed` **and** `superfences` enabled in your config for this to work. I though "OK, superfences is deprecated, I'll replace it with tabbed". Sorry, my bad.

**Comment by facelessuser** [comment]
Yeah, tabbed is general purpose content, while the old way was SuperFences' specific. This is why the latter is deprecated to make way for the more flexible, general purpose solution.

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add T: support
