### ISSUE TITLE
Suggestion: Add extension for Rest API methods

### ISSUE THREAD

**Issue by Andre601** [facelessuser/pymdown-extensions#847]
MkDocs is (kinda obviously) used for API documentation including those of Rest APIs

I think it would be a useful addition to have an extension to implement the different Rest actions into the documentation (like into headers and such

I can't really think of a proper syntax, but maybe something like this?
```
## {GET} /img/cat
```

`{GET}` would be replaced with a "GET" that is in a specific colour (and maybe with some background? idk)

If there is already an extension implementing such stuff and that could be used along with pymdown extensions, let me know.

**Comment by facelessuser** [comment]
While I understand the desire for something like this, it is important to note that I am not a web developer, so something as specific as an extension for Rest APIs does not directly appeal to me.

Pymdown-extensions was specifically created to fill a void for certain functionality I needed in my own documentation. For this reason, I am very selective when I add new extensions. The collection is not meant to contain every extension that any user may want, but more extensions that I have find useful. 

I unfortunately do not have the time to support an infinite collection of extensions for people, so I mainly support extensions that I know I'll use.

I would suggest you take a look around and see what is available, or it may be an area you'd like to develop one for.

@gir-bot remove S: triage
@gir-bot add T: feature, S: wontfix
