### ISSUE TITLE
Feature request: easier highlighting

### ISSUE THREAD

**Issue by ofek** [facelessuser/pymdown-extensions#878]
https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#highlighting-lines

I suggest we allow multiple ranges like `hl_lines="4-6 9-15"`

**Comment by facelessuser** [comment]
Yup, that's reasonable. For a long time I didn't tweak this because I was keeping parity with `fenced_code`, but we are fully separated from that now.

@gir-bot add T: feature
@gir-bot lgtm

**Comment by facelessuser** [comment]
Highlight ranges are go!

![jXQnkZjXkM](https://user-images.githubusercontent.com/1055125/78844065-e5d7de00-79c1-11ea-9b6c-ae5dd575e6ba.gif)

**Comment by ofek** [comment]
Oh snap!!! Awesome
