### ISSUE TITLE
SuperFences and CodeHilite problem

### ISSUE THREAD

**Issue by TJProgrammer** [facelessuser/pymdown-extensions#893]
Hello!

I have a Mkdocs project with CodeHilite and SuperFences.
I notice that CodeHilite doesn't show anymore the line numbers (it is true globally).
So I remove one by one the extensions and plugins and discover that SuperFences somehow disables the line numbers.
There is some problem between the extensions?

**Comment by facelessuser** [comment]
A long time ago, SuperFences used CodeHilite to do highlighting, much like `markdown.extensions.fenced_code` does. But we wanted to implement things that CodeHilite could not, so we created [Highlight](https://facelessuser.github.io/pymdown-extensions/extensions/highlight/).

We didn't want to break people, so for a while, if CodeHilite was being used, and Highlight was not explicitly configured, we would copy CodeHilite options over to Highlight to configure it. It was always meant to be temporary. But even during this temporary time in which we mirrored the options, we were not using CodeHilite anymore, but we were using Highlight. Well, the temporary time is over, we no longer look at CodeHilite options. You need to configure Highlight instead.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by TJProgrammer** [comment]
Thank you.
