### ISSUE TITLE
Spoilers question

### ISSUE THREAD

**Issue by gkphilip** [facelessuser/pymdown-extensions#90]
Hi @facelessuser. I have implemented the new Spoilers extension in my documentation and it works great. Thanks! I have a quick question. Do you know of any way that I could use Spoilers where the answers are only revealed after a certain length of time? The context being that sometimes we only want to provide the answers/spoilers at the end of a workshop after the students have first made an attempt at answering questions and also so that they have the answers for future use (while the trainers have access to answers all the time!). I have thought about the possibility of having some code that distinguishes between two URLs, where one basically hides all the answers if '?showanswers' is not found in the url or some such. I realise this would only be "security through obscurity" (i.e. the answers could be seen by looking at the source code), however that doesn't really concern me too much. Do you know of another way that would be more sensible to do this with the spoilers function? We maintain two documents at the moment, one with spoilers and one without and are happy to continue to do this is if there is no easy way. Many thanks for all your help.

**Comment by facelessuser** [comment]
There are probably lot's of things that *could* be done.  It depends on the infrastructure you have to work with.  I don't really know what what kind of setup you have or anything.  But, if you are looking to have a dynamic setup where after a set amount of time it shows the answers, I feel like you would have to implement something with JavaScript, and possibly some back end code, but I think it is possible it could be done with just frontend code.

Anyways, I'm honestly not a web developer.  My experience is really in firmware, but I dabble here and there with hobby projects like this one. I'd have to research possibilities if I were to give a definitive answer, so unfortunately, I don't have a real answer except I think it is possible, but I can't give you any help implementing your desired end product at this time.

Hopefully you'll be able to come up with a solution that works well for you.  Good luck!

**Comment by gkphilip** [comment]
No worries. Thank you for your reply - I just wanted to pass it by you in case you had an idea off the top of your head of a sensible way to do this using spoilers. I will chat about it with web developers that I have access to locally and see if I can come up with a solution that works well. Thanks again for implementing a Spoilers extension.
