### ISSUE TITLE
Disable linenums thoroughly

### ISSUE THREAD

**Issue by lufficc** [facelessuser/pymdown-extensions#902]
When using `pymdownx.highlight` and set `linenums` to `False`, users can still enable `linenums` like this:

<pre><code>
```linenums="1"
 code
```
</code></pre>

How can I prevent this?

**Comment by facelessuser** [comment]
Is there a reason that it must be disabled fully? Generally, if line numbers are not needed, I would just avoid using `linenums`. I guess you are somehow exposing the syntax to other people, but is there a reason that this is problematic?

I can an explicit disabling of it, but I'm trying to understand the issue it introduces.

**Comment by lufficc** [comment]
A comment system that support markdown may have this problem when you don't want to support `linenums `. Users can input anything...

**Comment by facelessuser** [comment]
We can do what CodeHilite does then. We will set it to `None` by default which will allow the user to manually specify line numbers in fence headers, but if `False` is explicitly defined, we will not render line numbers. `True` will enable it globally of course.
