### ISSUE TITLE
Allowing using URLs in place of filename

### ISSUE THREAD

**Issue by Passiday** [facelessuser/pymdown-extensions#903]
Talking about the snippet-plugin:
Perhaps this is implemented intentionally that only the files from the local filesystem can be included. I was just wondering that allowing to use http/https URLs in place of filename would bring enormous power. Including a file from a public git repo would be a typical example. Or, a more advanced use case — I could create a server-side script that dynamically generates svg, using some querystring parameters as input, host that script, and then refer to this script in my md file, several times, with different parameters.
Is this something that could be implemented in future versions? I am aware, of course, that I could just alter the Python code on my local machine to handle this, but that would be bad practice, as the md source would not be parsed in other user's environment.

**Comment by facelessuser** [comment]
I am uncertain to exactly what you are referring to. Can you elaborate? Which feature are you referring to that you wish could take URLs?

@gir-bot remove S: triage
@gir-bot add S: more-info-needed

**Comment by Passiday** [comment]
Here's an example of md code that I'd like to be parsed:

--8<-- "https://raw.githubusercontent.com/facelessuser/pymdown-extensions/master/README.md"

Currently it throws an error.

**Comment by facelessuser** [comment]
Ah, so this is in regards to snippets. Snippets was put together to make life easier for me in regards to content I may want to reference in multiple places, and sometimes inclusion of pre-rendered stuff. As noted it is pretty basic. It simply includes local snippets.

So, in answer to your question, it is currently working as expected. Personally, I'm struggling to find a reason I would use this functionality. From a MkDocs perspective (obviously from my own personal usage) I have never needed to pull in a gist file (or other files for that matter). If I do need to, it would be for information purposes, for instance, to simply to reference the source as an example, never to render it into my docs. So much could change, and I don't have control over those external files, and if I do, I can't see why I wouldn't just include it locally.

In general, while powerful, having my docs scattered like this seems undesirable. Is this something you actually have a need for? I'm not certain if I want to go this route, but I'm interested to hear of a real world scenario where this is desirable.

**Comment by Passiday** [comment]
Current real world scenario where this need popped up is a resource material for programming tutors for grades 4 to 12. MkDocs is used to build the main site, but there are number of problems and projects that are referred to throughot the docs. While we can keep the code (JavaScript, Python) for the problems in the same repo where the md sources are, we'd nevertheless like to keep the projects each in their own repo. Bringing in the files from those project repos is what's currently not possible with the snippets plugin. Of course, some kind of hack can be devised, like adding git-cloning of those projects in the render script so that their files are available at local path, but that's kind of ugly. Much cleaner way would be simply to import the content from a given URL.

**Comment by facelessuser** [comment]
Hmm, this is a very unique case, and I doubt very common. I would have to think about this. I'm usually open to things that I feel would be more broadly used, but often when presented with usage cases that only a very small percentage need, I'm more hesitant to add.

Just as a general comment, if this were to be included, there are some conceptual things that I don't think translate well to HTTP includes. Snippets allows for recursive includes. Since you are specifying a base path, all snippets share a common context. Content being local makes more sense with recursive include behavior. If you pull in external, HTTP sources that context no longer makes sense. I guess you could always restrict recursive includes if pulling in an HTTP source, but I think this is something that doesn't translate well.

Regardless, I'm hesitant to add this as I feel this is a case where it might make more sense for you to develop your own personal extension based off of Snippets to fulfill your very specific use case, than it would be for me to add it. I will consider this proposal though and post my final thoughts once I come to a conclusion.

@gir-bot remove S: more-info-needed
@gir-bot add S: needs-decision

**Comment by facelessuser** [comment]
Thinking about this more, this would most likely not work as you would expect. The way Snippets works now, it uses the context of the file the snippet is being inserted in. What this means is that if you had an image in a snippet that referenced a relative image, the image would be resolved relative to the file it is being inserted in, not relative to the snippet. The snippet is just plain text that gets inserted into a Markdown file, it is not evaluated by itself, but with the whole file that it is including it.

In your case, if we insert a readme from a foreign source, we cannot resolve images and such from that external source, and most likely, you expect that it would. This will not work as you would hope. I think this is just not a good fit for Snippets as it works today.

@gir-bot remove S: more-info-needed
@gir-bot add S: wontfix

**Comment by facelessuser** [comment]
@gir-bot remove S: needs-decision

Removed wrong label

**Comment by darkdragon-001** [comment]
Isn't this how snippets are supposed to work like? Being evaluated in the context they are inserted into? Otherwise it's not a snippet, but a reference.

So just downloading and inserting the snippet would be the way I expect the feature to work...

**Comment by facelessuser** [comment]
@darkdragon-001, I would generally agree. Most of the extensions I have in this bundle where mainly written to solve specific problems I wanted to solve. Snippets was generally made to insert something that I may need to do in multiple pages. For instance, I often use it to include external references, abbreviations, etc. at the bottom of many of my documents so I can update those external links in one place. I've also found other uses for them as well, but that is a big way that I use them.

In general, they are pretty "dumb", and currently that is how I like it. Some have suggested maybe making them more like  a template, and while I am potentially open to it, I haven't fully evaluated whether I will yet. I don't think I'll ever allow the them to be evaluated though except in the context they are inserted in.

**Comment by darkdragon-001** [comment]
Templates are often useful but follow a different paradigm. Therefore this should be kept separately and named accordingly (namely creating a different plugin with the name `template`).

Templates only make sense when you have variables to substitute into the template placeholders. This needs to be passed as an additional option (maybe together with a curated set of default ones like filename, environment variables, OS information etc.).
