### ISSUE TITLE
MathJax font is diminishing from the 2nd tab onwards

### ISSUE THREAD

**Issue by rahulsriram404** [facelessuser/pymdown-extensions#911]
While using MathJax in each of the tabs, the 1st tab is rendering the font precisely, but from the 2nd tab onwards, the font size is diminished.

=== "Math.log(x)"

    Returns the value of natural logarithm of `x`, i.e., $\log_e{x}

    $\text{Ex : }\log_{e}{e} = 1.0, \ln{1} = 0.0$

    ```java
    Math.log(Math.E); // 1.0
    Math.log(0); // -Infinity
    Math.log(1); // 0.0
    ```

=== "Math.log10(x)"

    Returns the value of $\log_{10}{x}$

    $\text{Ex : }\log_{10}{10} = 1.0, \log_{10}{1} = 0.1$

    ```java
    Math.log10(10); // 1.0
    Math.log10(0); // 
    Math.log10(1); // 0.1
    ```

Please copy the code and try it. I encountered this issue while using mkdocs-material

**Comment by facelessuser** [comment]
Not sure what I can tell you except this is a MathJax issue, not an Arithmatex issue. MathJax calculates the font size, and it apparently it calculates it different if the element is hidden vs not hidden. The same issue exists when using an admonition vs a closed details element.

Doing something like the following can force it to be consistent.

```css
mjx-container {
  font-size: inherit !important;
}
```

I don't provide any special styles, I simply preserve the math so it can be processed by MathJax. The rest is up to MathJax, and how you as the user choose to style it.

@gir-bot  remove S: triage
@gir-bot add S: wontfix

**Comment by facelessuser** [comment]
I guess you could also set it to a specific percentage if you'd like it a little bigger.

Anyways, closing this issue as it is an upstream problem with MathJax.
