### ISSUE TITLE
Arithmatex only works with escaped blocks

### ISSUE THREAD

**Issue by alping** [facelessuser/pymdown-extensions#917]
Hi!

```
pymdown-extensions==7.1
(mkdocs==1.1)
```

When using Arithmatex with MkDocs, the only way I can get equations to work is when I escape the `\` when starting and ending equations. The `$` and `$$` do not work at all. And if I have multiple `_` in an equation, this gets interpreted as markdown _italics_. `\begin` and `\end` work fine unescaped.

I have created a GitLab repository with a minimal example:
https://gitlab.com/alping/test-mkdocs-pymdownx

The result can be seen here:
https://alping.gitlab.io/test-mkdocs-pymdownx/

The build process is documented in the `.gitlab-ci.yml` file and should be reproducible with the python docker image.

I have followed the documentation to the best of my abilities, but it is entirely possible that this is a user error on my part.
https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/
https://www.mkdocs.org/user-guide/configuration/#markdown_extensions

This might be related to:
https://github.com/facelessuser/pymdown-extensions/issues/842
https://github.com/squidfunk/mkdocs-material/issues/1481#issue-575110404

**Minimal Markdown Example:**

```markdown
# Test MkDocs

## Not working

$\alpha$

\(\alpha\)

$$
\alpha
$$

\[
\alpha
\]

\\[
\underbrace{a}_{a} = \underbrace{b}_{b}
\\]

## Working because escaped

\\(\alpha\\)

\\[
\alpha
\\]

\\[
\underbrace{a}\_{a} = \underbrace{b}\_{b}
\\]

## Begin/End is also working

\begin{align}
    p(v_i=1|\mathbf{h}) & = \sigma\left(\sum_j w_{ij}h_j + b_i\right) \\
    p(h_j=1|\mathbf{v}) & = \sigma\left(\sum_i w_{ij}v_i + c_j\right)
\end{align}

```

**Comment by facelessuser** [comment]
This is not what I get at all, so I imagine you either are not setting up Arithmatex correctly and/or are not setting up MathJax proper.

This is what I get:

![chrome_0hqw7e6m8F](https://user-images.githubusercontent.com/1055125/80756198-58cf0300-8aef-11ea-9daf-00f97887c6cb.png)

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by facelessuser** [comment]
Noted that your underbrace example was escaped in both examples, so none of those worked.

**Comment by alping** [comment]
You are correct.

I didn't realize that the config for MathJax had to go before the MathJax library for the extra_javascript in the mkdocs.yml file. I stumbled upon it in the documentation for the Material MkDocs Theme:
https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#arithmatex-mathjax

If anyone else has this issue, the mkdocs.yml file should look like this (note that the config.js entry comes first):

```yml
site_name: My Site

markdown_extensions:
  - pymdownx.arithmatex

extra_javascript:
  - config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
```

Where the contents of the config.js can be found here:
https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/#loading-mathjax

```js
window.MathJax = {
  options: {
    ignoreHtmlClass: 'tex2jax_ignore',
    processHtmlClass: 'tex2jax_process',
    renderActions: {
      find: [10, function (doc) {
        for (const node of document.querySelectorAll('script[type^="math/tex"]')) {
          const display = !!node.type.match(/; *mode=display/);
          const math = new doc.options.MathItem(node.textContent, doc.inputJax[0], display);
          const text = document.createTextNode('');
          const sibling = node.previousElementSibling;
          node.parentNode.replaceChild(text, node);
          math.start = {node: text, delim: '', n: 0};
          math.end = {node: text, delim: '', n: 0};
          doc.math.push(math);
          if (sibling && sibling.matches('.MathJax_Preview')) {
            sibling.parentNode.removeChild(sibling);
          }
        }
      }, '']
    }
  }
};
```

Everything works for me now.

Thank you for the quick reply and for this project!
