### ISSUE TITLE
[SmartSymbols] User-defined replacement list

### ISSUE THREAD

**Issue by darkdragon-001** [facelessuser/pymdown-extensions#919]
What about allowing the user to pass a replacement list (python list of pairs) as a plugin option. I collected a lot of such UTF-8 replacements in [SpecialCharGetter:chars.ini](https://github.com/darkdragon-001/SpecialCharGetter/blob/master/chars.ini).

_Previously suggested in leohemsted/smartypants.py#17._

**Comment by facelessuser** [comment]
I do not think this is a route I'd like to go with SmartSymbols. It was never meant to be an extension to replace every conceivable  symbol. It was mainly an extension to add conventions I've seen around that I really liked, and more importantly use. 

I realize the suggestion is meant to allow users to define what **they** want, so it wouldn't affect me personally if I didn't define them, but that is really out of scope for what SmartSymbols was written for. It was simply written to provide a small curated set of symbols that I had seen common conventions around that I liked, that is really it.

If I were to add this, I'd also have to consider adding code to insert user symbols before or after other symbols so they could control the order of evaluation, and it is simply more than I'd like to maintain at this time. I would suggest that you potentially use SmartSymbols a guide and maybe develop your own personal symbol replacement extension.

@gir-bot remove S: triage
@gir-bot add S: wontfix

**Comment by facelessuser** [comment]
Additionally, some of these features are already available via things like subscripts and superscripts (yes it doesn't use the Unicode character, but it subscripts or superscripts whatever content you need), emoji can insert all sorts of expressive symbols, many which satisfy a lot of symbol needs.

Honestly, you can probably piggy back off the emoji extension and create your own custom index that adds new symbol names `:alpha:` (if that name isn't already taken), and you could process them to simply output the Unicode symbol you desire. All of this is already available.

**Comment by facelessuser** [comment]
Closing  for the reasons stated above.

**Comment by darkdragon-001** [comment]
I was busy the last days writing a replacement extension. 

Here it is :tada: https://github.com/darkdragon-001/smartusersymbols

Since this is my first python-markdown extension, I still don't know about all the internals of python-markdown extension system, but it seems to work for me so far.

**Can you please have a look and give me some feedback?**

---

### Details

First checkout the `README.md`. It should contain all information on how to use the plugin. You can also output a nice table with all the symbols supported by default.

The core of my extension is the auto-generation of regex patterns based on [this](https://stackoverflow.com/a/765835/3779655). It is found in `smartusersymbols_patterns.py:formatPattern()`.

All regex patterns except for ordinals are generated with this function.

Apart from this, my code contains a lot of comments including some open questions or bugs.

While I was researching HTML entities, I stumbled over [`html.entities`](https://docs.python.org/3/library/html.entities.html) which contains dictionaries with all available HTML entities. So it was easy to create additional substitutions based on them. When activating the HTML5 entities (which includes characters like `:` and `\n`), the parsing failed. When I was dumping the `data` variable in `handleMatch()`, it showed me some cryptic sequences, probably used by `treeprocessor` somehow. Further, I noticed that [some escaping with deficits is performed by the core](https://github.com/Python-Markdown/markdown/issues/952). Furthermore, HTML tags don't seem to be processed by them and additional ones can only be registered with a call to `self.md.htmlStash.store()`. Can you please tell me, which elements the regex is actually executed on?

**Comment by facelessuser** [comment]
I'll take a look maybe in the next couple of days. I just finished moving today, so I'm pretty tired, but I'd be happy to at least take a look and give you my initial impression.

**Comment by darkdragon-001** [comment]
Did you move in well? How is it going?

**Comment by facelessuser** [comment]
Yeah, thanks, we are moved in. I kind of forgot about this, so thanks for the gentle reminder. I now have it on my todo list :slightly_smiling_face:.
