### ISSUE TITLE
[PathConverter] Allow setting the scheme in base_url

### ISSUE THREAD

**Issue by darkdragon-001** [facelessuser/pymdown-extensions#921]
My document uses relative paths (e.g. `doc/file.html`). I would like to create absolute paths with explicitly setting the scheme by specifying `base_path = "file:///foo/bar"`.

https://github.com/facelessuser/pymdown-extensions/blob/e7320bf2a92b170b87af194ac1b0f26ed2809f31/pymdownx/pathconverter.py#L103

The following line returns `file:/foo/bar/doc/file.html`. Instead it should be `/foo/bar/doc/file.html`. You should also `util.parse_url(base_path)` and set `scheme` from `base_path` when it is not already set by `m.group()`.

**Comment by facelessuser** [comment]
Why do you need `file://`? Is there something preventing you from simply using `/foo/bar`? That would be my one question before I'd consider doing something like this.

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add S: more-info-needed

**Comment by darkdragon-001** [comment]
I am displaying rendered markdown in a `WebKit2.WebView` instance. Now I would like to switch links between local/web by just specifying the protocol in the `base_path`. Further, since the html content was just injected as string, the other browser behavior like links needs to be modified.

**Comment by facelessuser** [comment]
> I am displaying rendered markdown in a `WebKit2.WebView` instance

I'm not sure if this is relevant. Does this explicitly require the links to be in the form `file://`?

> Now I would like to switch links between local/web by just specifying the protocol in the `base_path`.

So if I understand, you want `file://` to force absolute paths, and the absence to use relative? What about when a path starts with `/` or on Windows starts with `C:/`?

> Further, since the html content was just injected as string, the other browser behavior like links needs to be modified.

I'm not following, can you elaborate?

**Comment by darkdragon-001** [comment]
> > I am displaying rendered markdown in a `WebKit2.WebView` instance
> 
> I'm not sure if this is relevant. Does this explicitly require the links to be in the form `file://`?

No, but I am using this to change behavior between local links and global links (open in web view or open web browser).

> > Now I would like to switch links between local/web by just specifying the protocol in the `base_path`.
> 
> So if I understand, you want `file://` to force absolute paths, and the absence to use relative? What about when a path starts with `/` or on Windows starts with `C:/`?

The behavior should be like an evaluation of the file at `base_path` (e.g. `base_protocol://base_host/base_path`). See [definition on Wikipedia](https://en.wikipedia.org/wiki/File_URI_scheme). The following links should be treated as follows:
- `protocol://host/path/file` --> `protocol://host/path/file`
- `//host/path/file` --> `base_protocol://host/path/file`
- `/path/file` --> `base_protocol://base_host/path/file`
- `file` --> `base_protocol://base_host/base_path/file`

> > Further, since the html content was just injected as string, the other browser behavior like links needs to be modified.
> 
> I'm not following, can you elaborate?

I think this is not really important, but since you were asking for my use-case:
I am using `WebView` to render the HTML generated from `markdown()`. Since I am not opening a stored file on disk, but instead opening an HTML string, the browser doesn't know how to resolve relative links. I want it to be possible to follow links as well (e.g. navigating a Markdown wiki). Further, I want local files to be opened in WebView (this way, I can also parse Markdown files there) but global files should be opened in the webbrowser. You can check out the [source code](https://github.com/darkdragon-001/gedit-markdown) if you want.

**Comment by facelessuser** [comment]
Couldn't you just add `target="_blank"` to external links that you are defining? Seems like it may be an easier route. You could do it with the `attr_list` extension that is included by default in Python Markdown.

```
[some link](../some/link.html){: target="_blank"}
```

What I'm struggling with is potentially changing how the extension currently works for one user's workflow.

With that said, it is important to note that PathConverter is meant to parse paths, it avoids `https://` and other various protocols. It does not expect to parse protocols because it expects it is dealing with local files. I may consider allowing it to identify `file://` though as it does describe local files.

This would be pretty low priority for me to look into, but I'll consider handling `file://`.

@gir-bot remove S: more-info-needed
@gir-bot add T: feature, P: maybe

**Comment by darkdragon-001** [comment]
> Couldn't you just add `target="_blank"` to external links that you are defining? Seems like it may be an easier route. You could do it with the `attr_list` extension that is included by default in Python Markdown.
> 
> ```
> [some link](../some/link.html){: target="_blank"}
> ```

I mostly use it to view existing files (e.g. `doc` directory of various Github projects). They are shipped without this addition.

Citing from [your documentation](https://facelessuser.github.io/pymdown-extensions/extensions/pathconverter/) (emphasis mine):

> **The references existence is not verified**, but the it is analyze to determine if it is a relative path, and if so, it is eligible for conversion. In the case of absolute mode, the relative Markdown references would be converted to absolute paths.

Since files are never accessed, I see no problem why it shouldn't work for remote files.

> What I'm struggling with is potentially changing how the extension currently works for one user's workflow.

Which part of the current behavior would actually change?

If there would be indeed any significant change in behavior, I suggest deprecating the current extension and replacing it with one named `UriConverter` with the behavior described previously.

**Comment by facelessuser** [comment]
We will only support local files, we will not be supporting any protocal, so only something like `file://` would make sense as a base path. If anything is done, only the base path option would change, and only to recognize `file://` and handle it properly.

**Comment by darkdragon-001** [comment]
I created [UriConverter](https://github.com/darkdragon-001/pymdx-dd001) based on your plugin. Since one is working with links, one should treat them as links anyway. There are many nice library functions to make life easy (most transformations are just one-liners).

The most basic usage would be to call it with `base` parameter set to `pathlib.Path(/CURRENT/FILE/PATH.EXT).as_uri()`.

Check out the tests to see which transformations are supported.

`absolute` is True automatically, when `base` is not empty and `relative_base` is empty.
Apart from this, it should be compatible with PathConverter when the above transformation is used.

If you are interested in including it into your suite, just tell me.

**Comment by facelessuser** [comment]
Well, it sounds like you have what you need. I don't really need the ability to handle to different protocols as this extension was meant to help with dealing specifically with local files. `file://` is not very important as this is a very specific use case that you need. The extension was always clear that is was handling file paths not URI, so I feel if people need URI, they can use your extension or create their own. I'll leave this open for now as I decide whether I will handle `file://` or not.

**Comment by darkdragon-001** [comment]
I am still interested in your use case and want to check if it is possible to handle it with my extension:

Can you please elaborate which settings you pass to your plugin and which format your links have in the document?

**Comment by facelessuser** [comment]
Links need to be relative paths to be converted. If any protocal is found, it is assumed it needs no conversion. So a `file://` or `ftp://` link needs no conversion as they are not relative path links.

Base path specifications are expected to be  absolute paths. It was designed so that I could generate Markdown previews, or serve up simple static sites. That's it. I've never had a need for `file://` as a base path as it really doesn't make sense it context. The base paths are mainly to make sure we can find resources and properly resolve then to an absolute path or a bath relative to the specified relative base.

**Comment by darkdragon-001** [comment]
All of this is handled by `urllib.parse.urljoin()`:

    $ urllib.parse.urljoin('/root/base/doc.md','relative/file')

    '/root/base/relative/file'

or

    $ base = pathlib.PureWindowsPath('C:\\User\\file.doc').as_uri()
    $ urllib.parse.urljoin(base, 'relative/file')
    
    file:///C:/User/file.txt

**Comment by facelessuser** [comment]
Are you suggesting we output the paths as URI by default? That is a different request. I am aware that we can parse base as URI. What I'm trying to understand is what is the end desired result, to parse a base with `file://` specified or to ensure the output of the extension is always a `file://` URI?

I have no interest in `https://` parsing as the extension is meant to handle local files, `https://` makes no sense in this context. Resolving a file relative to an `https://` makes no sense. You could parse it as an absolute I guess, but this is meant to resolve files in a local context, not an external context. I described above the use cases in which I considered when I wrote this.

Out of all the suggestions, outputting as a `file://` URI is maybe the one that makes the most sense. You gain nothing by parsing the base path as a URI if you are treating the base path with the context in which the extension was designed. Formatting the file as a URI maybe makes sense though.

**Comment by darkdragon-001** [comment]
My goal: Allow everything as base and produce the correct output (when it is defined).

Just play around with my plugin. It should handle all cases (yours and others) well and easy by using standard python functions. It is supposed to be a generalization of yours. I am just wondering if any case is not supported. Therefore, I am asking you for concrete examples to test them with my plugin.

**Comment by facelessuser** [comment]
Understood, but I have no interest in protocols such as `https://`, `ftp://`, etc. Those our out of scope for what the extension was designed for. The whole point of the extension is to resolve local file paths, that's it. I don't plan on extending it beyond that. I understand that it can be done, but that is beyond the intention of the extension. I am open to outputting the result as a file URI if that is what is desired, but outside of that, I don't think I plan on deviating from the current intention.

**Comment by darkdragon-001** [comment]
So your use-case can be solved with my generalization?

**Comment by facelessuser** [comment]
I guess my use case is already solved is my point.

Your generalization may keep the the status quo of what the extension currently does, but it also extends its scope beyond the intended design. PathConverter converts local paths to either absolute paths or paths relative to some other given path. That's all it is meant to do. Converting a local path relative to an https base doesn't make sense in the context of the plugin.

**Comment by darkdragon-001** [comment]
Just for completeness, UriConverter can also convert paths to the relative counterpart!

Let me know, if you are interested in deprecating your PathConverter in favor of UriConverter.
