### ISSUE TITLE
Images in snippets

### ISSUE THREAD

**Issue by louisguitton** [facelessuser/pymdown-extensions#922]
I'm including my `readme.md` as my `docs/index.md`

```md
<!-- docs/index.md -->
--8<-- "readme.md"
```

```md
<!-- readme.md -->
# Hello

> world

![](image.png)
```
(the image is placed at the root)

```yml
# mkdocs.yml
markdown_extensions:
  - pymdownx.snippets
```

The file is included just fine, but the image is missing. 

Is there a way to get the image working both in the Readme.md and the index page of the site?

**Comment by facelessuser** [comment]
I'll try this out, but it is important to note that snippets inserts the content before images are evaluated. After that, it's just parsed as normal Markdown. All snippets does is ensure the content of the shipper is inside the file that references it before the other processors get run.

I'll try it myself, but if there is an issue, it is most likely not the Snippets extension itself.

**Comment by facelessuser** [comment]
If you are expecting the image to use the relative location of the snippet, that will not work, it will use the relative location of the file you insert it into. This follows what I described in the previous post.

**Comment by louisguitton** [comment]
Alright yeah that's what I thought. Then no worries.

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add S: wontfix

Closing as this is currently working as expected.
