### ISSUE TITLE
Extend/Improve table extension

### ISSUE THREAD

**Issue by darkdragon-001** [facelessuser/pymdown-extensions#923]
It would be nice to see the default table extension improved upon a little.

Specifically, I would like the following
- Don't require the header row and separater row
- Allow multi-column cells  
  Adding the HTML [attribute](https://python-markdown.github.io/extensions/attr_list/#the-list) like `{: colspan='2' }` still forces the markdown processor to include the additional cell on the right.
- Allow multi-row cells  
  A different format would be needed: Header separater `=`, cell separater `-` would be required between all rows.

**Comment by facelessuser** [comment]
Unfortunately I do not often take new extension requests. I am open to improvements on existing extensions as long as I feel they are within the scope of the existing extension. Pymdown Extensions are not meant to be a one stop shop for all Python Markdown extensions, just what I have generally had a need for.

On rare occasions I have added extensions based on suggestions (`tabbed` and `keys`), but both of those are also features I had kind of been thinking about prior to the suggestions.

Unfortunately, I am not looking to maintain another extension unless it is something that directly contributes to my current needs. I support a lot of projects, and I'm not looking to increase the scope of what I am maintaining here at this time.

It is an interesting suggestion though, and I'm pretty sure there may be an older extension that allows for  something more advanced with tables, though I cannot recall the name.

@gir-bot remove S: triage
@gir-bot add S: wontfix

**Comment by darkdragon-001** [comment]
> It is an interesting suggestion though, and I'm pretty sure there may be an older extension that allows for something more advanced with tables, though I cannot recall the name.

I found two projects:
- [cell-row-span](https://github.com/Neepawa/cell_row_span) _([suggested](https://github.com/Neepawa/cell_row_span/issues/3) [PyPI](https://pypi.org/) release)_
- [mdx-spantables](https://github.com/Griffon26/mdx_spantables)

_In my opinion, this should be the default behavior._

Furthermore, an implementation of GridTables:
- [markdown-gridtables](https://github.com/smartboyathome/Markdown-GridTables/)

Thanks for your effort with this project anyways!
