### ISSUE TITLE
Embedding external resources (CSS, JS) by default

### ISSUE THREAD

**Issue by darkdragon-001** [facelessuser/pymdown-extensions#925]
I suggest embedding external resources needed for the extension to work to be automatically embedded by default. Add an option to disable it in case that the user wants to embed it himself. See [markdown-katex](https://gitlab.com/mbarkhau/markdown-katex) for an example on how I suggest it to work.

This would also avoid many issues posted by users who are confused at first why this extension is not working:
- arithmatex
- highlight
- progressbar (fix #912)
- tabbed (#871)
- _probably other extensions..._

**Comment by facelessuser** [comment]
Styles vary from site to site. Python Markdown does not render a full HTML, simply the partial with the content. Both styles and scripts should be managed by the user not the extensions.

@gir-bot remove S: triage
@gir-bot add S: wontfix

**Comment by darkdragon-001** [comment]
In my case, the user has only control over which plugins to load, not to configure them. So these plugins just don't work. Providing a default often makes sense. In case the user want to customize it, one should be able to deactivate it with an option or simply overwrite the few parts which need modification...

**Comment by facelessuser** [comment]
None of the extensions, in either the default extensions or this extension pack provide any styling or scripts. On rate occasion they provide some inline styling through style attributes, but generally styling and scripting are done by the user. You should set up your environment accordingly.

I will not manage versions of MathJax and user configs for such libraries or general subjective styling requests. Users should be responsible for setting up their environment the way they like it. I provide general examples and users should do as they like.

**Comment by facelessuser** [comment]
Again, your environment can inject styles as needed, but these extensions will not. You can provide defaults with your own extension if you desire, but no styling is provided by any if these on purpose. That should be in your HTML template in which the HTML partial are inserted in.

**Comment by darkdragon-001** [comment]
For me it's a preview. I don't care *how* it looks, it just has to *work*. Further, it's shipped as an extension to another product, so the end-user usually doesn't even know what `python-markdown` or even HTML/CSS/JS *is*. Further, 3rd-party extensions like yours are not enabled by default. Enabling them should just be as easy as adding the extension name to the config.

My template looks like this:
```
<head>
  <link href="https://sindresorhus.com/github-markdown-css/github-markdown.css" rel="stylesheet"></link>
</head>
<body class="markdown-body">
%s
</body>
```

**Comment by facelessuser** [comment]
I give example CSS that can generally be copied and pasted. You can copy that into a style block to get the behavior you desire. Some tweaking may be required.

When I started these extensions I had limited HTML, CSS, and JavaScript knowledge. I am not a web developer, but often with programming, you have to dig into unfamiliar areas and learn a bit more along the way.

You can join the discord channel and ask general questions as you dig into this further, as I have time I can answer. If you find that some of the example CSS needs improvements, I can help improve that.

**Comment by darkdragon-001** [comment]
The hurdle is just very high - especially when you never programmed before. Most people just don't use it because it is nice to have but not a requirement. Same for me: I enabled all your extensions, tried them with the first example and removed the ones which didn't work. Based on the issues I linked, other people also expect it to behave like this. And starting from a working default is a lot easier than starting with something which is not working and you have to figure out why.

**Comment by facelessuser** [comment]
If there is a problem with the examples, you can ask questions and we can help. I am open to helping people work through the examples I've given and improve documentation if necessary. If you are having a specific issue, you can post questions. But this is the way it has been for years, and many projects have used it just fine.
