### ISSUE TITLE
Using headers in tabs causes ToC to render wrong

### ISSUE THREAD

**Issue by Andre601** [facelessuser/pymdown-extensions#940]
I'm not sure if this is 100% caused by the tabbed extension or if it could be caused by MkDocs-Material not handling the headers properly.

The issue is, that when you use Headers in Tabs will it mess up the Table of Content (ToC) by not displaying any of the following headers after the tab.

For example would the following setup...
```markdown
# Header

!!! info
    === "Tab 1"
        Some text
    
    === "Tab 2"
        # Another Header

# Yet another Header
```

Only show "Header" on the ToC while "Yet another Header" and any following header aren't.
Removing the header from the tab fixes this and displays the headers as they should.

CC @squidfunk in case this is on MkDocs-Material's side (Which I honestly doubt being the case)

**Comment by facelessuser** [comment]
It's a MkDocs thing. You can only have 1 level 1 header per page, and that should be the title. You can have as many level n + 1 (where n is greater than 0) headers though.

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add T: support

**Comment by Andre601** [comment]
Okay. I suppose I have to look at this then

**Comment by Andre601** [comment]
The only question I now have is, why this header causes the ToC to no longer display any other Hn + 1 header, considering it only displays level 2 or higher headers.

**Comment by facelessuser** [comment]
Your asking the wrong guy. This is an implementation detail of MkDocs. What I do know is TOC gets messed up anytime you start using more than 1 level 1 header. Outside of that, I'd take it to MkDocs. But the Tabbed extension doesn't touch the TOC extension in anyway. It doesn't do anything special to headers. All content in a tab is treated without respect to the content inside.

**Comment by Andre601** [comment]
After some investigation does this seem to be more related to the MkDocs-Material theme, because when using the default mkdocs theme, does the Toc display all H1 and H2 headers with no issues. Just H3 and lover aren't displayed here.
