### ISSUE TITLE
Minor problems with rendering tasklist items properly

### ISSUE THREAD

**Issue by Andre601** [facelessuser/pymdown-extensions#941]
I face some minor issues, where task list entries are rendered with a large gap between the icon and the text itself.

For example is the following markdown...
```
Things to do:

- [x] Buy milk
- [x] Make laundry
- [ ] Take over the world
```

...rendered like this:
![image](https://user-images.githubusercontent.com/11576465/82121134-13ffc900-978b-11ea-94be-e48512212d00.png)

As you may noticed do I use a dark theme for the site.
The CSS for it is here: https://hasteb.in/ecaludob.css

Other CSS files I use:
- tabbed.css for the Tabbed extension: https://hasteb.in/zejosoti.css
- tasklist.css for the Tasklist extension: https://hasteb.in/junowesi.css

I also have `custom_checkbox` set to true and `clickable_checkbox` set to false, but hovering over the icon makes the cursor appear as if you can click the icon.

**Comment by facelessuser** [comment]
Looks like you need to adjust some margins and such.  Unfortunately I cannot spend time debugging everyone's custom CSS issues.

With that said, If I remember correctly, you are using Material for MkDocs? And if so, you don't need to provide full tasklist CSS from the tasklists documentation when using a dark mode, you would just need to tweak some colors as I do: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/extensions/_tasklist.scss. Material already provides tasklist CSS.

The tasklist example CSS that I provide in my documentation assumes that you don't already have custom tasklist CSS (Material does have custom tasklist CSS). There is no way I can provide a CSS that will 100% work in all scenarios with all of people's custom CSS, it should be looked at as an example to get you started, but not necessarily a complete solution as people's environments may vary. This is also why I do not inject CSS by default into any rendered content. I cannot ensure that any CSS I would provide will work in all content.

That is probably about as much guidance as I can give.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by facelessuser** [comment]
Closing as there is no actionable items moving forward, and the question has been answered.
