### ISSUE TITLE
Interlinks between tabbed headers

### ISSUE THREAD

**Issue by danierutu** [facelessuser/pymdown-extensions#947]
I'm using something like this, but the interlinks don't work when they're in different tabs.

```
=== "Tab 1"
    ## H1
    [Go to H2](#h2)

=== "Tab 2"
    ## H2
    [Go to H1](#h1)
```
I don't know if this is possible to implement.

**Comment by facelessuser** [comment]
You may need some JavaScript to do so. As pymdown-extensions doesn't directly inject any CSS or JavaScript, that is kind of left up to the user to provide, but with that said, I'd be more than happy to provide examples in the documentation if someone can help provide some.

**Comment by danierutu** [comment]
> You may need some JavaScript to do so. As pymdown-extensions doesn't directly inject any CSS or JavaScript, that is kind of left up to the user to provide, but with that said, I'd be more than happy to provide examples in the documentation if someone can help provide some.

I'd be utterly grateful if anyone knew how to do this and provided some documentation. Personally, I have no idea of JS...

**Comment by facelessuser** [comment]
I may be able to cobble something together *if I have time*. We'll see, but hopefully someone can jump in and help out.

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add T: support

**Comment by squidfunk** [comment]
I already solved that for `details` in Material for MkDocs:
https://github.com/squidfunk/mkdocs-material/blob/387f2c2c670798e41a7c881deb18cc30570c484b/src/assets/javascripts/patches/details/index.ts#L83-L94

Probably not too hard to solve for tabs, too.

**Comment by facelessuser** [comment]
Thanks @squidfunk! Clearly this issue slipped my mind and I never got around to answering it 😬. I think this is probably the best answer. The solution would most likely be very similar to this.

I'm not nearly as familiar with TS and the libraries being used, but the basic idea is to capture the `window.location.hash` reference and find the closest parent and ensure (in the case of tabs) is selected. I guess you'd go all the way up the chain. The same for details as well, except you'd open them.

What I'm hazy on is what event do you trigger on? I know you can trigger on content load for the initial page load, but I'm not sure how you capture once inter page jumps.

**Comment by facelessuser** [comment]
As this has basically been answered, I'll go ahead and close this.
