### ISSUE TITLE
Add Repository Code File with Snippets

### ISSUE THREAD

**Issue by flywire** [facelessuser/pymdown-extensions#972]
The [snippets example](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/) uses a `.md` file. Can it be used to include external repository program code files?

**example.md**

~~~
...
--8<-- "/url/source.py"
...
~~~

**/url/source.py**

~~~
import tensorflow as tf
~~~

**Result**

~~~
...
import tensorflow as tf
...
~~~

**Comment by facelessuser** [comment]
Yes it can. Snippets does not care what the extension or the content of the file is. It simply injects the content in the location specified.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by facelessuser** [comment]
As the question has been answered and there is no actionable item for us, we are closing the issue.

**Comment by squidfunk** [comment]
Can it be used inside fenced code blocks?

**Comment by facelessuser** [comment]
@squidfunk Yeah, it doesn't matter. It happens before everything.

**Comment by squidfunk** [comment]
That's super awesome! We should definitely advertise it in the docs, as I'm pretty sure its a rather common use case.

**Comment by facelessuser** [comment]
Just remember, it's a simple file inclusion, no fancy templating or anything.

**Comment by flywire** [comment]
@facelessuser - Could  https://facelessuser.github.io/pymdown-extensions/extensions/snippets/ examples include one file that is not `.md`?

**Comment by facelessuser** [comment]
I mean we could, but notice in the documentation, in the first two paragraphs, we mention it doesn't have to be Markdown, but can also be HTML (these are the two most common things people normally import, at least that is what I do).

But we even go on to say, you can import inside a code block:

> Snippets is an extension to insert markdown or HTML snippets into another markdown file. Snippets is great for situations where you have content you need to insert into multiple documents. For instance, this document keeps all its hyperlinks in a separate file. Then includes those hyperlinks at the bottom of a document via snippets. If a link needs to be updated, it can be updated in one location instead of updating them in multiple files.
>
> Snippets is run as a preprocessor, so if a snippet is found in a fenced code block etc., it will still get processed. If the specified file cannot be found, the the markup will be removed. If you need to show a snippet example in fenced code, please escape it as listed in Snippets Notation.

The extension is really irrelevant, but if you are importing anywhere in the Markdown that is not in a code block, you usually want to do HTML or Markdown as it will not get cleanly through the Markdown parser otherwise.

**Comment by flywire** [comment]
I'm a minimalist. Thinking replace:

> `--8<-- "filename.md"`

with:

> `--8<-- "filename.ext"` Snippets does not care what the extension or the content of the file is.

Maybe a url example too.

**Comment by facelessuser** [comment]
We can change all the extensions if you like to ext, but I don't know what you mean by URLs. Snippets does not accept URLs.

**Comment by flywire** [comment]
I'd only change the first extension to `.ext`, the others are good examples. Maybe one example with an extension other than `.md`.

ok re URLs, I wasn't sure, I don't recall seeing anything about them.

btw, Thank you for a very nice project. I'll leave you alone.

**Comment by facelessuser** [comment]
Feel free to make a pull if you'd like :slightly_smiling_face:.

> btw, Thank you for a very nice project. I'll leave you alone.

You're welcome!

**Comment by flywire** [comment]
Hmm

> The snippets example uses a `.md` file. Can it be used to include _external_ repository program code files?

Files are in [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) and response noted that [Snippets does not accept URLs](https://github.com/facelessuser/pymdown-extensions/issues/972#issuecomment-640130733).

Do you have any suggestions or comments for [use case](https://github.com/flywire/travis_cpp_tutorial)? Seems one issue is rendering pages off-line.

**Comment by facelessuser** [comment]
Snippet files must be local files. If you'd like to include submodules, they must be available locally.
